kubernetes-sigs/descheduler

- pkg/rescheduler/strategies/duplicates.go
- pkg/rescheduler/strategies/duplicates_test.go
/cc @aveshagarwal This covers the unit tests for duplicatePod removal strategy.
> unit tests for duplicate pods elimination

- pkg/rescheduler/strategies/duplicates_test.go
- pkg/rescheduler/strategies/lownodeutilization.go
- pkg/rescheduler/strategies/lownodeutilization_test.go
/cc @aveshagarwal test case for low node utilization strategy.
> Low node utilization test cases.

- pkg/rescheduler/node/node_test.go
- pkg/rescheduler/pod/pods_test.go
- pkg/rescheduler/strategies/duplicates_test.go
- pkg/rescheduler/strategies/lownodeutilization_test.go
- test/test_utils.go
/cc @aveshagarwal. I wasn't sure about the node ready condition(https://github.com/aveshagarwal/rescheduler/blob/master/pkg/rescheduler/node/node.go#L80). For the rest, I refactored and reorganized functions. Please let me know your feedback.
> Changes and file reorganization

- .travis.yml
/cc @aveshagarwal. This is for travis ci integration. I can include a code coverage badge as well from coversall.io. Let me know what you think about it?
> Travis integration for unit tests

- .travis.yml
@ravisantoshgudimetla can you check if these changes are ok? Also the changes you had are really needed.
> Fix travis yaml file.

- pkg/descheduler/strategies/lownodeutilization.go
@ravisantoshgudimetla can you review this as I noticed that at one place where pods are evicted, the count was not increased?
> Fix computation of number of evicted pods.

- cmd/descheduler/app/server.go
- cmd/descheduler/descheduler.go
- pkg/descheduler/node/node.go
- pkg/descheduler/policyconfig.go
- pkg/descheduler/strategies/duplicates.go
- pkg/descheduler/strategies/lownodeutilization.go
Conversion to glog.
cc @aveshagarwal.
> Conversion to glog

- .travis.yml
- cmd/descheduler/app/server.go
- cmd/descheduler/descheduler.go
- hack/verify-gofmt.sh
- pkg/descheduler/node/node.go
- pkg/descheduler/policyconfig.go
- pkg/descheduler/strategies/lownodeutilization.go
- test/test_utils.go
@aveshagarwal This PR introduces gofmt for travis CI and also changes some files that are don't have gofmt.
> Introducing gofmt

- README.md
@ravisantoshgudimetla in case if you have any feedback.
> Update readme with description to run descheduler as a job inside a pod.

- pkg/descheduler/strategies/duplicates.go
- pkg/descheduler/strategies/lownodeutilization.go
@ravisantoshgudimetla see if you have any feedback.
> Fix glog messages.

- Makefile
- cmd/descheduler/app/version.go
- cmd/descheduler/descheduler.go
/cc @aveshagarwal. For versioning.
> Introducing versioning in descheduler

- examples/policy.yaml
- pkg/descheduler/descheduler.go
- pkg/descheduler/strategies/pod_antiaffinity.go
- pkg/descheduler/strategies/pod_antiaffinity_test.go
/cc @aveshagarwal Initial commit for pod anti-affinity strategy. Please review whenever you find time.
> Pod antiaffinity strategy

- cmd/descheduler/app/server.go
- pkg/descheduler/descheduler.go
- pkg/descheduler/node/node.go
- pkg/descheduler/node/node_test.go
> Fix to not process empty node list and also fix error reporting in other places.

- pkg/descheduler/node/node_test.go
@ravisantoshgudimetla can you check why you had this code as it was unused as I tested?
> Remove unused test code.

- cmd/descheduler/app/options/options.go
> kubeconfig file correction

- pkg/descheduler/node/node.go
- pkg/descheduler/node/node_test.go
- pkg/descheduler/strategies/lownodeutilization.go
- pkg/descheduler/strategies/lownodeutilization_test.go
/cc @aveshagarwal @containscafeine - This should fix #42
> Changes to fix low node utilization strategy

- README.md
/cc @aveshagarwal - Go report included.
> Go report included

- README.md
/cc @aveshagarwal - Updated Readme to reflect pod anti-affinity strategy.
> Read me updated with changes for pod anti-affinity

- README.md
/cc @aveshagarwal - Compability matrix. Fixes #29
> Compatibility matrix for kube version

- Makefile
- cmd/descheduler/app/options/options.go
- pkg/apis/componentconfig/types.generated.go
- pkg/apis/componentconfig/types.go
- pkg/apis/componentconfig/v1alpha1/types.generated.go
- pkg/apis/componentconfig/v1alpha1/types.go
- pkg/apis/componentconfig/v1alpha1/zz_generated.conversion.go
- pkg/descheduler/descheduler.go
- pkg/descheduler/strategies/duplicates.go
- pkg/descheduler/strategies/duplicates_test.go
- pkg/descheduler/strategies/lownodeutilization.go
- pkg/descheduler/strategies/lownodeutilization_test.go
- pkg/descheduler/strategies/node_affinity.go
- pkg/descheduler/strategies/node_affinity_test.go
- pkg/descheduler/strategies/pod_antiaffinity.go
- pkg/descheduler/strategies/pod_antiaffinity_test.go
- pkg/descheduler/strategies/util.go
- test/e2e/e2e_test.go
Building on top of https://github.com/kubernetes-incubator/descheduler/pull/69
> Max pods per node

- pkg/descheduler/strategies/node_affinity.go
@ravisantoshgudimetla @ingvagabund
> Fix dryRun issue and avoid unnecessary log msg when node affinity strategy is disabled.

- .travis.yml
- hack/verify-gofmt.sh
> Bump Travis go version to 1.9.1

- SECURITY_CONTACTS
Fix https://github.com/kubernetes-incubator/descheduler/issues/98
> Add SECURITY_CONTACTS file.

- kubernetes/configmap.yaml
- kubernetes/job.yaml
- kubernetes/rbac.yaml
Here is a working setup with yaml files ready to be applied with
`kubectl apply -f .`
Version#2, out of v1beta1 and in v1.
> Yaml files for kubernetes

- README.md
> update readme to fix unused path

- cmd/descheduler/app/options/options.go
- pkg/apis/componentconfig/types.generated.go
- pkg/apis/componentconfig/types.go
- pkg/apis/componentconfig/v1alpha1/types.generated.go
- pkg/apis/componentconfig/v1alpha1/types.go
- pkg/apis/componentconfig/v1alpha1/zz_generated.conversion.go
- pkg/descheduler/pod/pods.go
- pkg/descheduler/strategies/duplicates.go
- pkg/descheduler/strategies/duplicates_test.go
- pkg/descheduler/strategies/lownodeutilization.go
- pkg/descheduler/strategies/lownodeutilization_test.go
- pkg/descheduler/strategies/node_affinity.go
- pkg/descheduler/strategies/node_affinity_test.go
- pkg/descheduler/strategies/pod_antiaffinity.go
- pkg/descheduler/strategies/pod_antiaffinity_test.go
An earlier PR before squashing https://github.com/kubernetes-incubator/descheduler/pull/120
> Added support to evict pods that use local storage.

- Makefile
Run below commands to build and push
a staging image to staging-k8s.gcr.io.
```
$ make push
```
Run below commands to build and push
a release image to k8s.gcr.io.
```
$ git checkout v0.9.0
$ VERSION=v0.9.0 REGISTRY=k8s.gcr.io make push
```
> Push Container Images To k8s.gcr.io

- pkg/descheduler/strategies/duplicates_test.go
Fixes #157.
Note for reviewer: renamed `tests` to `testCases` because of `test` import collision.
> Improved logic for duplicates testing

- pkg/descheduler/strategies/lownodeutilization.go
Signed-off-by: sph <shepenghui1@huawei.com>
> Fix golint errors

- README.md
- pkg/descheduler/descheduler.go
- pkg/descheduler/strategies/node_taint.go
- pkg/descheduler/strategies/node_taint_test.go
PR to address: https://github.com/kubernetes-incubator/descheduler/issues/131
> Strategy to consider taints and tolerations in Descheduler

- OWNERS
I've authored and reviewed several PRs for this codebase, and would like to continue in a reviewer role.
PRs I've worked on:
https://github.com/kubernetes-sigs/descheduler/pull/188
https://github.com/kubernetes-sigs/descheduler/pull/192 
https://github.com/kubernetes-sigs/descheduler/pull/175
https://github.com/kubernetes-sigs/descheduler/pull/186
https://github.com/kubernetes-sigs/descheduler/pull/161
https://github.com/kubernetes-sigs/descheduler/pull/183
/cc @ravisantoshgudimetla
> Add damemi to reviewers

- kubernetes/job.yaml
Intentation is wrong on job yaml
> Fix intentation on yaml

- README.md
- examples/descheduler-job.yaml
- examples/descheduler.yaml
Added documentation for the compile, since just checking out the repo and running make didnt work for me.
Also, combined the steps in the readme to integrate descheduler as job into a cluster into two kubernetes yaml files to create service accounts, cluster roles and to create the job.
> Documentation for compile and example yaml files for creation of kubernetes resources

- .travis.yml
* Update to kubectl 1.17.0
* Update to kind 0.6.1
> Update Travis With Latest Kind and Kubectl Versions

- Makefile
The container registry now defaults to the correct staging registry.
> Use correct GCR staging registry

- pkg/descheduler/node/node.go
- pkg/descheduler/node/node_test.go
- pkg/descheduler/strategies/lownodeutilization.go
There is also an inconsistency in the test utilities where it is capitalized as "Un_S_chedulable", I left that alone.
> Fix typo in function name

- Dockerfile
- Dockerfile.dev
> Fix email address in docker files.

- CONTRIBUTING.md
https://git.k8s.io/community/contributors/guide/contributor-cheatsheet.md
> fix broken link :

- pkg/descheduler/strategies/node_taint.go
- pkg/descheduler/strategies/node_taint_test.go
Removing duplicated code. Broken down the changes into smaller steps for easier review.
@damemi @seanmalloy PTAL
> Tolerations taints code cleanup

- README.md
Cherry pick commit 435674fb44cad61de7af98fb6fcc400252d5845e to the release-1.18 branch.
> Cherry Pick: Update Compatibility Matrix in README

- kubernetes/cronjob.yaml
- kubernetes/job.yaml
Cherry pick commit 8c7267b3791c82bf546b5c82a84ebba8c1008074 to the `release-1.18` branch.
> Update Install Manifests For Release v0.18.0

- pkg/descheduler/evictions/evictions.go
* 7680e3d - minor code refactor
* 4ff533e - add eviction reason to k8s events
Implements #320.
/kind feature
> Add Pod Eviction Reason To Events

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/misc_request.md
Initially users can open a bug report, feature request, or misc request.
Bug reports and feature requests will have the "kind" label
automatically added.
> Add initial GitHub issue templates

- test/e2e/e2e_test.go
- test/run-e2e-tests.sh
Trying to fix e2es after they were added to prow in https://github.com/kubernetes/test-infra/pull/18292
> Update e2e script to use Kind setup

- test/e2e/e2e_test.go
> Clean e2e test so it's easier to extend it

- charts/descheduler/README.md
Ref https://github.com/kubernetes-sigs/descheduler/issues/248
> Update helm chart name in docs

- README.md
- charts/descheduler/README.md
* db501da34d8fa0e112c186dc9eb72a315e98ff82 - add link from main README and the install command
* 8d5ab05aa0f3f520d5a2f64695c5dd2690357ff9 - add helm badge to README
> More Helm Documentation

- README.md
- kubernetes/cronjob.yaml
- kubernetes/job.yaml
* Added v0.19 references to README
* Update k8s manifests with v0.19.0 references
> Update Docs and Manifests for v0.19.0

- cmd/descheduler/app/server.go
- pkg/descheduler/descheduler.go
- pkg/descheduler/evictions/evictions.go
- pkg/descheduler/node/node.go
- pkg/descheduler/policyconfig.go
- pkg/descheduler/strategies/lownodeutilization.go
- pkg/descheduler/strategies/node_affinity.go
- pkg/utils/predicates.go
> Convert logs to use structured logs

- pkg/descheduler/strategies/lownodeutilization.go
> [release-1.19] LowNodeUtilization: log when a node is unschedulable

- pkg/descheduler/strategies/lownodeutilization.go
> [release-1.18] LowNodeUtilization: log when a node is unschedulable

- pkg/descheduler/node/node.go
- pkg/descheduler/strategies/duplicates.go
- pkg/descheduler/strategies/lownodeutilization.go
- pkg/descheduler/strategies/node_affinity.go
- pkg/descheduler/strategies/node_taint.go
- pkg/descheduler/strategies/pod_antiaffinity.go
- pkg/descheduler/strategies/pod_lifetime.go
- pkg/descheduler/strategies/toomanyrestarts.go
Towards https://github.com/kubernetes-sigs/descheduler/issues/347
> Flip Info/Infof/Error to InfoS/ErrorS

- pkg/descheduler/node/node.go
- pkg/descheduler/strategies/duplicates.go
- pkg/descheduler/strategies/lownodeutilization.go
- pkg/descheduler/strategies/node_affinity.go
- pkg/descheduler/strategies/node_taint.go
- pkg/descheduler/strategies/pod_antiaffinity.go
- pkg/descheduler/strategies/pod_lifetime.go
- pkg/descheduler/strategies/toomanyrestarts.go
Builds on top of https://github.com/kubernetes-sigs/descheduler/pull/407
> Change klog info messages after a strategy is exited into error messages

- docs/user-guide.md
- examples/low-node-utilization.yml
- examples/pod-life-time.yml
> Add use case for lowNodeUtilization

- Dockerfile
> Bump To Go 1.15.2

- charts/descheduler/README.md
Helm 3 omits `--name` flag for release name.
> Helm chart README fix

- pkg/descheduler/pod/pods.go
- pkg/descheduler/strategies/lownodeutilization.go
Signed-off-by: Mateusz Gozdek <mgozdekof@gmail.com>
> pkg/descheduler/strategies: fix typo

- README.md
> Add missing parameter in README

- pkg/descheduler/strategies/lownodeutilization.go
From unit tests (after s/klog.V(2)/klog `klog.V(2).InfoS("Node is underutilized|overutilized|appropriately utilized` lines):
```
$ go test -v sigs.k8s.io/descheduler/pkg/descheduler/strategies -run TestLowNodeUtilization
=== RUN   TestLowNodeUtilization
=== RUN   TestLowNodeUtilization/no_evictable_pods
I1118 14:50:43.281224 3774981 lownodeutilization.go:274] "Node is appropriately utilized" node="n3" usage=map[cpu:0 memory:0 pods:0] usagePercentage=map[cpu:0 memory:0 pods:0]
I1118 14:50:43.281265 3774981 lownodeutilization.go:271] "Node is overutilized" node="n1" usage=map[cpu:2400m memory:0 pods:6] usagePercentage=map[cpu:0.75 memory:0 pods:0.6666666666666666]
I1118 14:50:43.281275 3774981 lownodeutilization.go:268] "Node is underutilized" node="n2" usage=map[cpu:0 memory:0 pods:0] …
```
> LowNodeUtilization: show node usage in percentage as well

- README.md
- kubernetes/cronjob/cronjob.yaml
- kubernetes/job/job.yaml
* Added v0.20 references to README
* Update k8s manifests with v0.20.0 references
> Update Docs and Manifests for v0.20.0

- pkg/descheduler/strategies/duplicates.go
- pkg/descheduler/strategies/duplicates_test.go
Fixes: #263
Previous work:
- https://github.com/kubernetes-sigs/descheduler/pull/269
- https://github.com/kubernetes-sigs/descheduler/pull/398
- https://github.com/kubernetes-sigs/descheduler/pull/420
> RemoveDuplicatePods: evict uniformly

- charts/descheduler/README.md
- charts/descheduler/templates/cronjob.yaml
- charts/descheduler/values.yaml
Fixes https://github.com/kubernetes-sigs/descheduler/issues/479
> Add nodeSelector to cronJob helm chart

- kubernetes/cronjob/cronjob.yaml
- kubernetes/job/job.yaml
> Update Job and CronJob YAML to run as non-root

- pkg/descheduler/strategies/lownodeutilization_test.go
To complement https://github.com/kubernetes-sigs/descheduler/pull/493.
> LowNodeUtilization: unit test resourceUsagePercentages to validate percentages are computed correctly

- charts/descheduler/templates/cronjob.yaml
> Update Helm Chart to run as non-root

- charts/descheduler/values.yaml
A couple of lines had an extra whitespace.
> Fix indentation in values.yaml

- cmd/descheduler/app/options/options.go
Fixes https://github.com/kubernetes-sigs/descheduler/issues/487
/kind bug
> Add default logging-format value

- README.md
- docs/user-guide.md
- examples/high-node-utilization.yml
- pkg/descheduler/descheduler.go
- pkg/descheduler/strategies/nodeutilization/highnodeutilization.go
- pkg/descheduler/strategies/nodeutilization/highnodeutilization_test.go
- pkg/descheduler/strategies/nodeutilization/lownodeutilization.go
- pkg/descheduler/strategies/nodeutilization/lownodeutilization_test.go
- pkg/descheduler/strategies/nodeutilization/nodeutilization.go
- pkg/descheduler/strategies/nodeutilization/nodeutilization_test.go
- test/e2e/e2e_test.go
Adds HighNodeUtilization strategy
Closes #196
> Highnodeutilization strategy

- README.md
- pkg/descheduler/strategies/nodeutilization/highnodeutilization.go
- pkg/descheduler/strategies/nodeutilization/highnodeutilization_test.go
Extending https://github.com/kubernetes-sigs/descheduler/pull/550 with https://github.com/kubernetes-sigs/descheduler/pull/559
> HighNodeUtilization: add NodeFit feature

- charts/descheduler/README.md
- charts/descheduler/templates/cronjob.yaml
- charts/descheduler/values.yaml
This pull request adds support for private registry creds
> Add support for private registry creds

- docs/release-guide.md
**What this PR does / why we need it:**
Needed for https://github.com/kubernetes/k8s.io/issues/1597
**Which issue(s) this PR fixes (optional, using fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when the PR gets merged):**
Needed for https://github.com/kubernetes/k8s.io/issues/1597
> Rename master to main

- .gitignore
🙈 Happened again. This time I'm adding it to `.gitignore` so it won't happen again.
> Remove kind binary from repo

- charts/descheduler/README.md
- charts/descheduler/templates/cronjob.yaml
- charts/descheduler/values.yaml
Add tolerations to cronjob in helm chart
> Add tolerations to cronjob in helm chart

- hack/e2e-gce/gcloud_create_cluster.sh
Clean up extra spaces, although these errors are not important, they affect the code specification.
> Clean up extra spaces

- README.md
Per https://github.com/kubernetes-sigs/descheduler/pull/610#discussion_r680105312
> Update README to remove redundant list of strategies

- pkg/descheduler/strategies/node_affinity_test.go
Fix duplicate code in node_affinity_test.go.
> fix duplicate code in node_affinity_test.go

- README.md
- charts/descheduler/Chart.yaml
- docs/user-guide.md
- kubernetes/cronjob/cronjob.yaml
- kubernetes/deployment/deployment.yaml
- kubernetes/job/job.yaml
- pkg/descheduler/strategies/failedpods.go
- pkg/descheduler/strategies/failedpods_test.go
- pkg/descheduler/strategies/validation/strategyparams.go
- test/e2e/e2e_failedpods_test.go
- test/e2e/e2e_test.go
- test/e2e/e2e_topologyspreadconstraint_test.go
Summary of changes:
- Include changes from PR #632
- Update Helm chart to v0.22.1
- Update Docs and Manifests to use Image 0.22.1
> Release 1.22.1

- pkg/descheduler/strategies/topologyspreadconstraint.go
- pkg/descheduler/strategies/topologyspreadconstraint_test.go
Closes https://github.com/kubernetes-sigs/descheduler/issues/618
> Ignore pods being deleted

- metrics/metrics.go
- pkg/descheduler/evictions/evictions.go
Add node name label to improve pod eviction metrics.
> Add node name label to the counter metric for evicted pods 

- charts/descheduler/README.md
- charts/descheduler/templates/_helpers.tpl
- charts/descheduler/values.yaml
Adding the ability to add common labels for resources. Currently we can't use the chart as is since we require extra custom labels.
> commonLabels value for chart

- pkg/descheduler/evictions/evictions.go
Dry mode currently does not report metrics when the eviction succeeds
Missing change in https://github.com/kubernetes-sigs/descheduler/pull/677
> Evictor: report successful eviction independently of the dry-mode

- cmd/descheduler/app/server.go
- pkg/descheduler/descheduler.go
using root context cancellation from sigint sigterm to control our http server and our run loop.
noticed the todo context while going through the code, figured we should use the sigterm signal to cancel it.
> Use the root context cancellation

- charts/descheduler/values.yaml
> fix: Remove deprecated parameters from cmdOptions and add the parameters under policy

- docs/user-guide.md
- kubernetes/cronjob/cronjob.yaml
- kubernetes/deployment/deployment.yaml
- kubernetes/job/job.yaml
Docs/manifest updates to include references to new image
> [release-1.23] Update manifests and doc for v0.23.1

- docs/user-guide.md
- kubernetes/cronjob/cronjob.yaml
- kubernetes/deployment/deployment.yaml
- kubernetes/job/job.yaml
Docs/manifest updates to include references to new image
> Update manifests and doc for v0.23.1

- docs/user-guide.md
> fix doc about NPD description

- docs/proposals.md
> Share links to all descheduler ehnacements proposals in the project repo

- pkg/utils/pod.go
Following issue https://github.com/kubernetes-sigs/descheduler/issues/752, I updated the taint validation workflow to add logging of the taint blocking the pod eviction
> add conflicting taint to the logs

- OWNERS
Per @damemi  @ingvagabund adding myself as a code reviewer
Sig Projects: https://github.com/kubernetes-sigs/descheduler
PR: https://github.com/kubernetes-sigs/descheduler/pulls?q=is%3Apr+is%3Aclosed+janeliul
Issues: https://github.com/kubernetes-sigs/descheduler/issues?q=is%3Aissue+janeliul
Org issue: https://github.com/kubernetes/org/issues/3306
> OWNERS: add janeliul as a reviewer

- pkg/api/types.go
- pkg/api/v1alpha1/types.go
- pkg/api/v1alpha1/zz_generated.conversion.go
- pkg/descheduler/strategies/node_taint.go
- pkg/descheduler/strategies/node_taint_test.go
> RemovePodsViolatingNodeTaints: optionally include PreferNoSchedule taint

- Makefile
- hack/verify-gofmt.sh
- pkg/descheduler/strategies/duplicates_test.go
- pkg/descheduler/strategies/nodeutilization/nodeutilization.go
- test/e2e/e2e_test.go
- test/run-e2e-tests.sh
Possibly fixing https://github.com/kubernetes-sigs/descheduler/pull/792#issuecomment-1124569018
> Update e2e test versions

- pkg/descheduler/strategies/nodeutilization/lownodeutilization.go
The code is duplicated and useless
> cleanup lownodeutilization code

- pkg/descheduler/pod/pods_test.go
Addressing previous PR feedback: https://github.com/kubernetes-sigs/descheduler/pull/833#discussion_r890913475
/cc @ingvagabund
> remove random creation timestamp from pod sort by age test

- README.md
- examples/pod-life-time.yml
- pkg/api/types.go
- pkg/api/v1alpha1/types.go
- pkg/api/v1alpha1/zz_generated.conversion.go
- pkg/api/v1alpha1/zz_generated.deepcopy.go
- pkg/api/zz_generated.deepcopy.go
- pkg/descheduler/strategies/pod_lifetime.go
- pkg/descheduler/strategies/pod_lifetime_test.go
Closes #580
This will allow users to define strategies to:
- If a Pod is stuck in container state PodInitializing for longer than ..
- If a Pod is stuck in container state ContainerCreating for longer than ..
> PodLifeTime: support container states PodInitializing and ContainerCreating

- pkg/descheduler/strategies/topologyspreadconstraint.go
- pkg/descheduler/strategies/topologyspreadconstraint_test.go
Existing contraints fix backport 1.24
> Existing contraints fix backport 1.24

- pkg/descheduler/strategies/topologyspreadconstraint.go
- pkg/descheduler/strategies/topologyspreadconstraint_test.go
Existing contraints fix backport 1.23
> Existing contraints fix backport 1.23

- OWNERS
> Remove emeritus_approvers from reviewers

- pkg/framework/plugins/nodeutilization/highnodeutilization.go
- pkg/framework/plugins/nodeutilization/lownodeutilization.go
- pkg/framework/plugins/podlifetime/pod_lifetime.go
- pkg/framework/plugins/removeduplicates/removeduplicates.go
- pkg/framework/plugins/removefailedpods/failedpods.go
- pkg/framework/plugins/removepodshavingtoomanyrestarts/toomanyrestarts.go
- pkg/framework/plugins/removepodsviolatinginterpodantiaffinity/pod_antiaffinity.go
- pkg/framework/plugins/removepodsviolatingnodeaffinity/node_affinity.go
- pkg/framework/plugins/removepodsviolatingnodetaints/node_taint.go
BalancePlugin and DeschedulerPlugin implement Plugin, we can remove it just to clean things up a little
> removing dupe plugin interface check

- charts/descheduler/values.yaml
- add RemovePodsViolatingTopologySpreadConstraint yaml to values.yaml to make chart config clearer
> Add RemovePodsViolatingTopologySpreadConstraint to values.yaml

- pkg/descheduler/strategy_migration.go
Issue #960
Signed-off-by: Vlastimil Holer <vh@fortrabbit.com>
> includeSoftConstraints not being respected for TopologySpreadConstraint

- .github/workflows/helm.yaml
- README.md
- test/run-e2e-tests.sh
> update version references in docs and readme

- Dockerfile
- Dockerfile.dev
- charts/descheduler/templates/cronjob.yaml
- charts/descheduler/templates/deployment.yaml
- kubernetes/cronjob/cronjob.yaml
- kubernetes/deployment/deployment.yaml
- kubernetes/job/job.yaml
Reverts kubernetes-sigs/descheduler#995
> Revert "Split CMD into ENTRYPOINT and CMD for Dockerfile"

- pkg/api/v1alpha1/conversion.go
- pkg/api/v1alpha1/register.go
- pkg/descheduler/descheduler.go
- pkg/descheduler/descheduler_test.go
- pkg/descheduler/policyconfig.go
- pkg/descheduler/policyconfig_test.go
Remove error handling with string comparison and use UniversalDecoder to convert v1alpha1.
Thanks a lot with all the help @knelasevero
> Fix v1alpha1 conversion to use universal decoder

- README.md
- docs/user-guide.md
- kubernetes/cronjob/cronjob.yaml
- kubernetes/deployment/deployment.yaml
- kubernetes/job/job.yaml
https://github.com/kubernetes-sigs/descheduler/pull/1108#issuecomment-1494515868
> update v0.26.1 references

- pkg/descheduler/descheduler.go
> Fix typo log message for cachedClient

- OWNERS
As per the discussion on slack, adding myself to the approver list :D
> Add knelasevero to approvers

- README.md
- docs/user-guide.md
- examples/failed-pods.yaml
- examples/high-node-utilization.yml
- examples/low-node-utilization.yml
- examples/node-affinity.yml
- examples/pod-life-time.yml
- examples/policy.yaml
- examples/topology-spread-constraint.yaml
- pkg/descheduler/policyconfig_test.go
Follow up for https://github.com/kubernetes-sigs/descheduler/pull/1120.
> Drop remaining mentions of evict extension point

- kubernetes/base/configmap.yaml
Ref https://github.com/kubernetes-sigs/descheduler/pull/1122#discussion_r1180482236
> Add missing quote to configmap

- README.md
- charts/descheduler/Chart.yaml
- docs/user-guide.md
- kubernetes/cronjob/cronjob.yaml
- kubernetes/deployment/deployment.yaml
- kubernetes/job/job.yaml
Closed #1084 
Rebased on top of #1116
> update helm chart to v0.27.0

- pkg/api/v1alpha2/conversion.go
- pkg/descheduler/policyconfig.go
- pkg/descheduler/policyconfig_test.go
cherry-pick commit "fix plugin arg conversion when using multiple profiles with same plugin" to release-1.27
> fix plugin arg conversion when using multiple profiles with same plugin

- .github/workflows/manifests.yaml
- charts/descheduler/Chart.yaml
- docs/deprecated/v1alpha1.md
- docs/user-guide.md
- kubernetes/cronjob/cronjob.yaml
- kubernetes/deployment/deployment.yaml
- kubernetes/job/job.yaml
follow-up to https://github.com/kubernetes/k8s.io/pull/5337
> bump chart to v0.27.1

- test/e2e/e2e_duplicatepods_test.go
- test/e2e/e2e_leaderelection_test.go
- test/e2e/e2e_test.go
- test/e2e/e2e_toomanyrestarts_test.go
- test/run-e2e-tests.sh
> update pause image from 'kubernetes/pause' to 'registry.k8s.io/pause'

- pkg/descheduler/pod/pods.go
- pkg/framework/plugins/removepodsviolatinginterpodantiaffinity/pod_antiaffinity.go
- pkg/framework/plugins/removepodsviolatingtopologyspreadconstraint/topologyspreadconstraint.go
- pkg/framework/plugins/removepodsviolatingtopologyspreadconstraint/topologyspreadconstraint_test.go
follow up to #1033 and apply the same in removepodsviolatingtopologyspreadconstraint
> use pod informers for listing pods in removepodsviolatingtopologyspreadconstraint and removepodsviolatinginterpodantiaffinity

- kubernetes/base/configmap.yaml
> fix: base configmap missing plugin RemoveDuplicates

- pkg/framework/profile/profile.go
Fix profile attribute "prpfile" typo in trace spans.
> profile: fix span attribute typo

- charts/descheduler/templates/cronjob.yaml
cherry-pick commit to release-1.28 branch
https://github.com/kubernetes-sigs/descheduler/pull/1229
> helm: update cronjob args argument to avoid unmarshal error

- README.md
Closes https://github.com/kubernetes-sigs/descheduler/issues/1175
> docs: fix evictableNamespaces example

- kubernetes/cronjob/cronjob.yaml
- kubernetes/deployment/deployment.yaml
- kubernetes/job/job.yaml
this was missed as part of v0.28 release
cc: @knelasevero
> update image references to point to v0.28.0

- pkg/descheduler/descheduler.go
- pkg/descheduler/descheduler_test.go
> fix: version skew compatibility for managed kubernetes providers

- OWNERS
> adding jklaw90 to reviewers

- hack/cherry_pick_pull.sh
The intention is to make cherry-picking PRs for patch releases easier.
We should also look into making prow cherry-pick work
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/cherry-picks.md
> copy cherry_pick_pull script form kubernetes/kubernetes

- .github/workflows/manifests.yaml
- charts/descheduler/Chart.yaml
- docs/deprecated/v1alpha1.md
- docs/user-guide.md
- kubernetes/cronjob/cronjob.yaml
- kubernetes/deployment/deployment.yaml
- kubernetes/job/job.yaml
> release v0.28.1: bump helm chart and images

- charts/descheduler/Chart.yaml
> update helm icon to force release of v0.28.1

- pkg/framework/plugins/defaultevictor/defaultevictor.go
Now the DefaultEvictorArgs parameters undergo redundant type conversion in DefaultEvictor, which is unnecessary.
This pr can resolve that.
> avoid redundant type conversion of DefaultEvictorArgs parameter in DefaultEvictor

- .github/workflows/manifests.yaml
- charts/descheduler/Chart.yaml
- kubernetes/cronjob/cronjob.yaml
- kubernetes/deployment/deployment.yaml
- kubernetes/job/job.yaml
last step before cutting release-1.30
> [release 1.30] update kustomize image tags and helm versions

- charts/descheduler/templates/cronjob.yaml
- charts/descheduler/templates/deployment.yaml
> Helm chart - allow 'falsey' value in cmdOption

- cmd/descheduler/app/server.go
- pkg/tracing/tracing.go
Fixes https://github.com/kubernetes-sigs/descheduler/issues/1428
> Bump otel semconv to 1.24

- pkg/descheduler/descheduler.go
/kind cleanup
- NodeLister has been initialized in newDescheduler, delete the duplicate code
- Delete unused ctx
```go
func newDescheduler(rs *options.DeschedulerServer, deschedulerPolicy *api.DeschedulerPolicy, evictionPolicyGroupVersion string, eventRecorder events.EventRecorder, sharedInformerFactory informers.SharedInformerFactory) (*descheduler, error) {
podInformer := sharedInformerFactory.Core().V1().Pods().Informer()
podLister := sharedInformerFactory.Core().V1().Pods().Lister()
nodeLister := sharedInformerFactory.Core().V1().Nodes().Lister()
namespaceLister := sharedInformerFactory.Core().V1().Namespaces().Lister()
priorityClassLister := sharedInformerFactory.Scheduling().V1().PriorityClasses().Lister()
getPodsAssignedToNode, err := …
```
> chore: cleanup duplicated code

- pkg/descheduler/client/client.go
fix: add info for error return
> fix: add info for error return

- pkg/descheduler/descheduler.go
- pkg/descheduler/descheduler_test.go
- pkg/version/version_test.go
- vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
- vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
- vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
- vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go
- vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go
- vendor/modules.txt
> fix: minor version parsing in version compatibility check

- go.mod
- go.sum
- test/e2e/e2e_test.go
- test/e2e/e2e_toomanyrestarts_test.go
- test/run-e2e-tests.sh
- vendor/github.com/ghodss/yaml/.gitignore
- vendor/github.com/ghodss/yaml/.travis.yml
- vendor/github.com/ghodss/yaml/LICENSE
- vendor/github.com/ghodss/yaml/README.md
- vendor/github.com/ghodss/yaml/fields.go
- vendor/github.com/ghodss/yaml/yaml.go
- vendor/modules.txt
TODO:
Other e2e tests will be updated separately.
> [TestTooManyRestarts] e2e: build a descheduler image and run the descheduler as a pod

- pkg/descheduler/descheduler_test.go
Check all three descheduling limits are exercised
> [unit test]: test descheduling limits

- pkg/descheduler/descheduler_test.go
RemovePodsViolatingNodeTaints requires less pods and nodes for testing than RemoveDuplicates.
> [unit test]: simplify test pod evictor reset

- .github/workflows/helm.yaml
- .github/workflows/manifests.yaml
- .github/workflows/release.yaml
- .github/workflows/security.yaml
update python EOL, helm, and github actions
> chore: upgrade python EOL and action versions

- Makefile
> chore: bump golangci-lint to latest

- charts/descheduler/Chart.yaml
Closes https://github.com/kubernetes-sigs/descheduler/issues/1491
> descheduler v0.31.0: bump helm chart

- test/e2e/e2e_duplicatepods_test.go
> [DuplicatePods] e2e: build a descheduler image and run the descheduler as a pod

- test/e2e/e2e_failedpods_test.go
> [FailedPods] e2e: build a descheduler image and run the descheduler as a pod 

- test/e2e/e2e_topologyspreadconstraint_test.go
> [TopologySpreadConstraint] e2e: build a descheduler image and run the descheduler as a pod

- test/e2e/e2e_toomanyrestarts_test.go
- test/e2e/e2e_topologyspreadconstraint_test.go
> test: construct e2e deployments through buildTestDeployment

- cmd/descheduler/app/options/options.go
- cmd/descheduler/app/server.go
So it can be later extended with init of feature gates in https://github.com/kubernetes-sigs/descheduler/pull/1466.
> DeschedulerServer: new Apply function for applying configuration

- charts/descheduler/templates/cronjob.yaml
- charts/descheduler/templates/deployment.yaml
- charts/descheduler/values.yaml
Closes https://github.com/kubernetes-sigs/descheduler/issues/1563
> Improve chart default values

- .github/workflows/manifests.yaml
- test/run-e2e-tests.sh
follow up to https://github.com/kubernetes/test-infra/pull/34045
> [release v0.32] update kubernetes kind version to 1.32

- README.md
- docs/user-guide.md
> [release v0.32] update docs/readme

- .github/workflows/manifests.yaml
- README.md
- charts/descheduler/Chart.yaml
- kubernetes/cronjob/cronjob.yaml
- kubernetes/deployment/deployment.yaml
- kubernetes/job/job.yaml
Follow up to https://github.com/kubernetes/k8s.io/pull/7656
> [release v0.32.0] bump chart and images

- .github/workflows/manifests.yaml
- charts/descheduler/Chart.yaml
- docs/user-guide.md
- kubernetes/cronjob/cronjob.yaml
- kubernetes/deployment/deployment.yaml
- kubernetes/job/job.yaml
Follow up to https://github.com/kubernetes/k8s.io/pull/7659
> [v0.32.1] patch release for CVE-2024-45337 and CVE-2024-45338

- pkg/framework/plugins/defaultevictor/defaultevictor_test.go
- add ignorePvcPods param in default evictor filter unit test
> chore: add ignorePvcPods param in default evictor filter unit test

- pkg/descheduler/policyconfig.go
- pkg/descheduler/policyconfig_test.go
- pkg/utils/predicates.go
fix: https://github.com/kubernetes-sigs/descheduler/pull/1613#discussion_r1968252706
> chore: add setDefaultEvictor return an error

- pkg/descheduler/node/node.go
- pkg/framework/plugins/nodeutilization/usageclients.go
Get resource usage only of those resources that are actually requested. Not more.
> [nodeutilization]: produce node utilization of resources that are listed in the list of resources

- pkg/framework/plugins/nodeutilization/classifier/classifier.go
- pkg/framework/plugins/nodeutilization/classifier/classifier_test.go
- pkg/framework/plugins/nodeutilization/highnodeutilization.go
- pkg/framework/plugins/nodeutilization/lownodeutilization.go
- pkg/framework/plugins/nodeutilization/nodeutilization.go
- pkg/framework/plugins/nodeutilization/nodeutilization_test.go
Move the classifier to its own package. Introduces a generic way of classifying usages against thresholds.
> feat: move classifier to its own package

- OWNERS
> chore: update owners to add me as reviewer

- README.md
- add miss evictDaemonSetPods param in README.md
> add miss evictDaemonSetPods param in README.md

- README.md
- charts/descheduler/Chart.yaml
> v0.33.0: bump helm chart

- pkg/descheduler/node/node.go
- Reordered the checks from fastest to slowest to reduce unnecessary computation.
before: `selector -> taints -> resources -> unschedulable -> anti-affinity`
after: `unschedulable -> selector -> taints -> anti-affinity -> resources`
> optimize: NodeFit function by reordering checks for performance

- pkg/framework/plugins/removepodshavingtoomanyrestarts/toomanyrestarts.go
fix: https://github.com/kubernetes-sigs/descheduler/issues/1685
> feature: sort pods by restarts count in RemovePodsHavingTooManyRestarts plugin

- pkg/framework/plugins/removepodsviolatingtopologyspreadconstraint/topologyspreadconstraint.go
move namespaces filtering logic to `New()` in `RemovePodsViolatingTopologySpreadConstraint` plugin
This logic is determined in `BuildFilterFunc`.
https://github.com/kubernetes-sigs/descheduler/blob/e466307d7cfc3d4ef3f69b27d4d734853b5e6208/pkg/descheduler/pod/pods.go#L94-L120
> chore: move namespaces filtering logic to New()

- pkg/framework/plugins/example/example.go
inspired by this pr: https://github.com/kubernetes-sigs/descheduler/pull/1688/files
- use ListPodsOnANode func in example plugin
- update comment
After the two PRs are merged, the only plugins that use the ListAllPodsOnANode method are: PodLifeTime RemoveFailedPods RemovePodsHavingTooManyRestarts plugins, because these plugins will filter internally or use the pod.Status.Phase status.
> fix(example): list only active pod

- pkg/framework/plugins/removefailedpods/failedpods.go
- pkg/framework/plugins/removepodshavingtoomanyrestarts/toomanyrestarts.go
Changing logger level/message type needs to be discussed separately.
> logger: Align with the previous logger verbosity

- charts/descheduler/templates/deployment.yaml
- charts/descheduler/values.yaml
Allow to customize annotations on deployment level.
> helm chart - Allow to add custom annotations for deployment

- cmd/descheduler/app/server.go
the `tracing.Shutdown()` uses the context so we must guarantee that the context we use is valid regardless if the original context being cancelled already. this change introduces an exclusive context for the shutdown process with an arbitrary timeout.
this is a pr created to replace https://github.com/kubernetes-sigs/descheduler/pull/1618 as we aren't seen much activity by the original pr author.
Please ensure your pull request meets the following criteria before submitting
for review, these items will be used by reviewers to assess the quality and
completeness of your changes:
> chore: give tracing.Shutdown() its own context
