pkg/rescheduler/evictions/evictions_test.go

@aveshagarwal I believe this completes the unit tests. We have 3 more files without unit tests  which are client.go, policyconfig.go, rescheduler.go and I think none of them needs unit tests. Please let me know what you think. I think, we can add a travis.yaml file and code coverage badge from covers.io or someother code coverage tool.

Evictions test case and small modification

---

pkg/descheduler/strategies/lownodeutilization.go

This commit adds log messages to be printed whenever a node is
identified as a target node from which the pods can be evicted or
as an underutilized node to which the evicted pods can be
scheduled, if at all.
This should help with debugging as well as with letting the user
know the identified nodes.

Add log messages for target, underutilized nodes

---

pkg/descheduler/strategies/lownodeutilization.go
pkg/descheduler/strategies/lownodeutilization_test.go

This commit adds checks to only allow valid resource names for the
thresholds field, which are "cpu", "memory", and "pods" right now.
For the other valid or invalid resource names, descheduler will now
throw an error.
Also, tests have been added to test the added behavior.
fix #40

Validate resource names to pass to thresholds

---

pkg/descheduler/pod/pods.go
pkg/descheduler/strategies/duplicates.go
pkg/descheduler/strategies/lownodeutilization.go
pkg/descheduler/strategies/pod_antiaffinity.go
pkg/descheduler/strategies/pod_antiaffinity_test.go

cc @aveshagarwal This is to ensure that all strategies will take into account only evictable pods. 
Fixes #48

Small refactor to accomodate descheduling only evictable pods

---

pkg/descheduler/node/node.go

Currently time duration is chosen randomly.

Fix node lister by allowing its reflector to have enough time so that listing works.

---

README.md

This should allow evictions of pods on nodes. I tested this on 1.7.6 cluster.

Fixes the serviceaccount issue by adding new eviction resources

---

pkg/descheduler/pod/pods.go
pkg/descheduler/pod/pods_test.go
test/test_utils.go

/cc @aveshagarwal - Partially fixes #8.
Added function for checking latency sensitive pods. As of now, handles GPUs after rebase to 1.8 we should be able to handle other high value resources.

Make GPU requested pods not evictable by descheduler

---

pkg/descheduler/pod/pods.go
pkg/descheduler/pod/pods_test.go
pkg/descheduler/strategies/duplicates.go
pkg/descheduler/strategies/duplicates_test.go
pkg/descheduler/strategies/lownodeutilization_test.go
pkg/descheduler/strategies/pod_antiaffinity_test.go
test/test_utils.go

/cc @aveshagarwal  - Since creatorRef is removed in 1.9, switching to ownerRef now. This works with both 1.8 and 1.9, I have tested it against a running 1.9 cluster. Fixes #52

Owner ref switch

---

pkg/descheduler/descheduler.go

This ensures that no strategy is run in first place when the cluster size is 1.
/cc @aveshagarwal @containscafeine

Descheduler should not run when cluster size is 1

---

Dockerfile
Dockerfile.dev
Makefile
README.md

By disabling CGO, we can use the scratch image instead of the fedora
image, allowing a lighter weight image.
By setting up a multistage docker build, we can create the container image
in a single command. This eliminates external setup and allows us to build
this automatically on registries.

Scratch image + multistage builds.

---

README.md
examples/node-affinity.yml
pkg/api/types.generated.go
pkg/api/types.go
pkg/api/v1alpha1/types.generated.go
pkg/api/v1alpha1/types.go
pkg/api/v1alpha1/zz_generated.conversion.go
pkg/api/v1alpha1/zz_generated.deepcopy.go
pkg/api/zz_generated.deepcopy.go
pkg/descheduler/descheduler.go
pkg/descheduler/node/node.go
pkg/descheduler/node/node_test.go
pkg/descheduler/strategies/node_affinity.go
pkg/descheduler/strategies/node_affinity_test.go
pkg/utils/predicates.go

Yikes, @aveshagarwal @ravisantoshgudimetla, honestly, I've really not thought this through. Currently, it's more of a hack to just get it barely working. The code is bad, and there are no tests, but if you pass a YAML like the following, then it works.
How to test -
1. label a node x=y
2. schedule pods on it using node affinity as requiredDuringSchedulingIgnoredDuringExecution
3. remove label from the node and set it to another node 
4. run the descheduler, and if the new node is schedulable, it evicts the pods
```yaml
apiVersion: "descheduler/v1alpha1"
kind: "DeschedulerPolicy"
strategies:
"RemovePodsViolatingNodeAffinity":
enabled: true
params:
nodeAffinityType:
- "requiredDuringSchedulingIgnoredDuringExecution"
```
Would love the comments on design for this new strategy.
To Do:
P. S. …

add requiredDuringSchedulingIgnoredDuringExecution for RemovePodsViolatingNodeAffinity strategy

---

.travis.yml
Makefile
hack/e2e-gce/gcloud_create_cluster.sh
hack/e2e-gce/gcloud_sdk_configure.sh
hack/e2e-gce/install_gcloud.sh
hack/e2e-gce/kubeadm_preinstall.sh
test/e2e/e2e_test.go
test/run-e2e-tests.sh

@aveshagarwal I am able to create a 3 node cluster in gce with pod being evicted for lownodeutilization case.  Please review when you find time. I believe, travis ci might complain because of encrypted file(client.json.enc) which will probably not be decrypted on this repo. 
Some changes:
- Now instead of running unit-tests, travis will run unit-tests + e2e's when using `make test`.
- Before running `make test`, we need to ensure that gcloud_create_cluster.sh has been run. I have included that in the run-tests.sh(file renamed from run-unittests.sh)
Sample Output after running e2e:
`evicting pods from node %#v with usage: %#v descheduler-b148f4c6-bd94-11e7-8e84-c85b76333877 map[cpu:2264 memory:263.78542244169597 pods:81.81818181818181]`

E2E using gce first pass

---

hack/lib/init.sh
hack/update-codecgen.sh
test/run-e2e-tests.sh
test/run-unit-tests.sh

Given the repository is build and about-to-be tested under openshift organization
we need to change the kubernetes-incubator into openshift. Yet, keeping both repos still in sync.

Allow to override repository organization

---

hack/e2e-gce/gcloud_create_cluster.sh

As of now, e2es in CI are broken because of kubeadm not able to install 1.9.4 cluster. Bumping the testing kube cluster to 1.11.1.
Error msg in CI:
`Flag --skip-preflight-checks has been deprecated, it is now equivalent to --ignore-preflight-errors=all
this version of kubeadm only supports deploying clusters with the control plane version >= 1.10.0. Current version: v1.9.4`

Fix broken e2e tests

---

pkg/descheduler/strategies/lownodeutilization.go
pkg/descheduler/strategies/lownodeutilization_test.go
test/test_utils.go

This PR introduces the notion of priority while evicting pods. Also, updated existing test cases to reflect the same. Some of the e2e's may fail which I will work on.

Low node utilization to respect priority while evicting pods

---

hack/e2e-gce/gcloud_create_cluster.sh

I am seeing the following errors in CI continuously.
Flag --skip-preflight-checks has been deprecated, it is now equivalent to --ignore-preflight-errors=all
This should fix the behaviour.

Fix deprecated warning in CI

---

README.md

Descheduler 0.4+ should work with kube 1.9+.
/cc @aveshagarwal

Update the compatibility matrix

---

README.md

Removing production usage warning to encourage more users to try using descheduler and since descheduler has been stable so far.
/cc @aveshagarwal

Remove production usage warning

---

hack/e2e-gce/gcloud_create_cluster.sh

Latest versions of kubeadm(1.12 and 1.13) are failing with errors when etcd running as static pod is using public ip with following error:
`2018-12-14 19:11:51.664216 I | embed: peerTLS: cert = /etc/kubernetes/pki/etcd/peer.crt, key = /etc/kubernetes/pki/etcd/peer.key, ca = , trusted-ca = /etc/kubernetes/pki/etcd/ca.crt, client-cert-auth = true
2018-12-14 19:11:51.664266 C | etcdmain: listen tcp <public_ip>:2380: bind: cannot assign requested address`
So made it to run on private IP and bumped the kube version.
/cc @aveshagarwal

Run apiserver on private ip and bump kube version installed to 1.13

---

pkg/descheduler/strategies/duplicates.go
pkg/descheduler/strategies/duplicates_test.go
test/test_utils.go

PR fixes #147.
In short, added ownerRef.UID in addition to ownerRef.Kind and ownerRef.Name when evaluating duplicates. On clusters with multiple Namespaces that have an identical Deployment or StatefulSet (think `dev` and `test` namespaces), the added UID ensures that only Pods that are managed by the same ReplicaSet are considered for eviction.
Tested on a 3-node DigitalOcean cluster:
```
$ kubectl get rs --all-namespaces | grep nginx
default       nginx-7db9fccd9b             3         3         3       8m57s
testing       nginx-7db9fccd9b             3         3         3       74s
$ ./_output/bin/descheduler --kubeconfig k8s-1-14-2-do-0-fra1-1558715482863-kubeconfig.yaml --policy-config-file policyfile.yaml --v=3
I0524 18:48:54.138997    7838 reflector.go:202] Starting reflector …
```

Added ownerRef.UID for evaluating duplicate Pods

---

.travis.yml
hack/kind_config.yaml
hack/verify-gofmt.sh
test/e2e/e2e_test.go

/kind flake
The e2e test was hardcoded to selecting the 3rd node as default leastLoadedNode. This hard coding does not guarantee to select the least loaded node if the testing cluster is set up differently.
Fixes # This fix help selects the actual least loaded node based on the number of pods assigned to each node after RC is set up. It also skips the master node.
/cc @ravisantoshgudimetla

Remove hardcoded node selection in E2e test 

---

pkg/descheduler/strategies/lownodeutilization.go

Fixes a small typo observed when checking job logs for low node utilization

Fix small typo in output for thresholds

---

README.md
pkg/descheduler/pod/pods.go
pkg/descheduler/pod/pods_test.go
test/e2e/e2e_test.go

This PR adds new functionality, which enables special pod annotation. 
User can control which pods can be evicted by setting annotation descheduler.alpha.kubernetes.io/evict. With this annotation user can override checks, which prevents descheduler to evict pods (user should know what he is doing).
This PR is POC for this proposal: https://github.com/kubernetes-sigs/descheduler/issues/185
/cc @MarSik, @fromanirh, @aveshagarwal, @k82cn, @ravisantoshgudimetla

Evict annotation

---

kubernetes/job.yaml
kubernetes/rbac.yaml

Fix small typo in cluster binding role and an extra space in job.yaml

Fix typos in kubernetes example

---

pkg/descheduler/client/client.go

* a blank import should be only in a main or test package, or have a comment justifying it
* add comment for blank import of clientauth in client.go

Normalize blank import

---

.travis.yml
Dockerfile
hack/update-gofmt.sh
hack/verify-gofmt.sh

Starting with Kubernetes release 1.17 Go >= 1.13.4 is required.
https://github.com/kubernetes/kubernetes/pull/82809

Update To Go 1.13.5

---

README.md
examples/descheduler-job.yaml

Support for using the `scheduler.alpha.kubernetes.io/critical-pod` annotation was
deprectated in 1.13 and finally removed in 1.16
Also alignes the format of the yaml-blob for descheduler-job.yaml in readme.md to the one in examples/descheduler-job.yaml 
I'm not sure if there was made consiuous decision made around the `image:` property here; is there a reason they differed? I kept that difference for the time being atleast.

Update examples to support v1.16.0+

---

cmd/descheduler/app/options/options.go
pkg/descheduler/descheduler.go
test/e2e/e2e_test.go

Fixes https://github.com/kubernetes-sigs/descheduler/issues/220
This wires the `--descheduling-interval` flag to actually run the descheduler on a loop in the interval specified. If the value is unset (which defaults to `0`) the descheduler only runs once, maintaining consistency with the current expectation. 
One benefit to this is that it removes the need to use a CronJob for a continuously running controller.

Wire --descheduling-interval to run descheduler on a loop

---

cloudbuild.yaml
docs/releasing.md

Adds a GCB(Google Cloud Build) configuraiton file that automates the
building and pushing of descheduler container images to the official
Google Container Registry for k8s.
Reference documentation:
https://github.com/kubernetes/test-infra/blob/master/config/jobs/image-pushing/README.md

Automate Container Image Builds Using GCB

---

Dockerfile

The kubernetes project updated to Go 1.13.6, so it's time to update the
descheduler too.
https://github.com/kubernetes/kubernetes/pull/87106

Update to Go 1.13.6

---

README.md

Newer versions of k8s(>= 1.16) no longer support the critical-pod
annotation. Setting the priorityClassName is the correct way to mark a
pod as critical.
https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods

Remove reference to critical-pod annotation from documentation

---

pkg/descheduler/pod/pods_test.go
pkg/descheduler/strategies/duplicates_test.go
pkg/descheduler/strategies/lownodeutilization_test.go
pkg/descheduler/strategies/node_taint_test.go
test/test_utils.go

Fixes: https://github.com/kubernetes-sigs/descheduler/issues/228

Critical pod annotation scheduler.alpha.kubernetes.io/critical-pod has been drop, no need to set it anymore in the tests

---

README.md

was probably missed in https://github.com/kubernetes-sigs/descheduler/pull/182

fix Build and Run GOPATH dir

---

kubernetes/rbac.yaml

The descheduler creates a k8s event for each pod that it evicts. When
the code to create events was added the RBAC ClusterRole was not updated
to allow creating events. Users would see the below error in the
descheduler log when it tried to create an event.
"system:serviceaccount:kube-system:descheduler-sa" cannot create resource
"events" in API group "" in the namespace "xxxx-production"' (will not retry!)'
This change fixes this error by updating the ClusterRole to allow
creation of k8s events.
Fixes #229

Update ClusterRole To Allow Creating Events

---

.travis.yml

Enable a build matrix in Travis CI to run the e2e tests against multiple k8s versions. Additionally update kind to v0.7.0 which adds support for k8s v1.17.
Replaced command "kind get kubeconfig-path" with "kind get kubeconfig" because the "kubeconfig-path" subcommand is not valid with kind v0.7.0.

Run e2e Tests Against Multiple k8s Versions

---

kubernetes/cronjob.yaml
kubernetes/job.yaml

The correct location for the official descheduler container image is
us.gcr.io/k8s-artifacts-prod/descheduler/descheduler:TAG_NAME.

Fix GCR Image Location In Job and CronJob YAML

---

docs/releasing.md

Add a link to the test grid dashboard for automated container image builds,
and documents useful gcloud commands for woking with the staging registry.
This documentation is useful for project maintainers that are creating
releases and publishing container images. The chance of remembering
these commands and links is slim to none. Therefore documenting this
information will be very useful.

Add notes section to release documentation

---

README.md
docs/README.md
docs/contributor-guide.md
docs/release-guide.md
docs/user-guide.md

This pull requests cleans up the README.md file, creates a user guide, and creates a contributor guide. The user and contributor guides could use some additional improvements, but I believe in their current state will provide value to end users.

Documentation Refresh

---

pkg/descheduler/descheduler.go
pkg/descheduler/descheduler_test.go
pkg/descheduler/node/node.go
pkg/descheduler/node/node_test.go
test/e2e/e2e_test.go

Also, refactor the code a bit so it can be tested without checking for eviction support.
Fixes: https://github.com/kubernetes-sigs/descheduler/issues/245

List nodes through informer in every iteration

---

pkg/descheduler/strategies/lownodeutilization.go
pkg/descheduler/strategies/lownodeutilization_test.go
pkg/utils/pod.go
pkg/utils/predicates.go

If a node has a taint and is under-utilised, the descheduler will evict pods based on qos, priority etc but doesn't check if these "suitable" pods tolerate this taint, thus evicting and goes into an infinite loop of "reshuffling". This PR adds this check.
If multiple Nodes are under-utilised and both have taints, all the descheduler cares about if pods can tolerate taints of one of the nodes as then the default scheduler will schedule it onto one of the nodes.

Respect Node taints with tolerations (if exist)

---

Dockerfile

Kubernetes releases 1.15 through 1.19 have been updated
to Go 1.13.8, so it's time to update the descheduler too.
https://github.com/kubernetes/release/issues/1134

Update to Go 1.13.8

---

Dockerfile

Kubernetes releases 1.16 through 1.19 have been updated
to Go 1.13.9, so it's time to update the descheduler too.

Update to Go 1.13.9

---

pkg/descheduler/node/node.go
pkg/descheduler/node/node_test.go

The `PodFitsAnyNode` function returned `false` early if it hit any node with matched the selectors but was also unschedulable (before finding a suitable node).
This PR also includes vendor updates that weren't committed earlier, in order to compile.

Fix early return from PodFitsAnyNode check

---

README.md

Compared to https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#node-affinity the strategy kinda implements requiredDuringSchedulingRequiredDuringExecution node affinity type for kubelets. Only addition to kubelet is the strategy checks whether there is at least another node capable of respecting the node affinity rules.
When requiredDuringSchedulingRequiredDuringExecution node affinity type is implemented in kubelet, it's likely the strategy either gets removed or re-implemented. Stressing the relation with requiredDuringSchedulingRequiredDuringExecution will helps consumers of descheduler to keep in mind the kubelet will eventually take over the strategy when implemented.

readme: RemovePodsViolatingNodeAffinity: reword description of the strategy

---

pkg/descheduler/descheduler_test.go
pkg/descheduler/evictions/evictions_test.go
pkg/descheduler/node/node_test.go
pkg/descheduler/pod/pods_test.go
pkg/descheduler/strategies/duplicates_test.go
pkg/descheduler/strategies/lownodeutilization.go
pkg/descheduler/strategies/lownodeutilization_test.go
pkg/descheduler/strategies/node_affinity_test.go
pkg/descheduler/strategies/node_taint_test.go
pkg/descheduler/strategies/pod_antiaffinity_test.go
test/test_utils.go

Only over utilized nodes need clasification of pods into categories. Thus, skipping categorizing of pods which saves computation time in cases where the number of over utilized nodes makes less than 50% of all nodes or their fraction.
Also, refactoring the test code a bit in order to make lownodeutilization testing table driven.

Order pods by priority only over over utilized nodes

---

pkg/descheduler/descheduler.go
pkg/descheduler/strategies/duplicates.go
pkg/descheduler/strategies/duplicates_test.go
pkg/descheduler/strategies/lownodeutilization.go
pkg/descheduler/strategies/lownodeutilization_test.go
pkg/descheduler/strategies/node_affinity.go
pkg/descheduler/strategies/node_affinity_test.go
pkg/descheduler/strategies/node_taint.go
pkg/descheduler/strategies/node_taint_test.go
pkg/descheduler/strategies/pod_antiaffinity.go
pkg/descheduler/strategies/pod_antiaffinity_test.go
pkg/descheduler/strategies/toomanyrestarts.go
pkg/descheduler/strategies/toomanyrestarts_test.go
test/e2e/e2e_test.go

Removing `sigs.k8s.io/descheduler/cmd/descheduler/app/options` dependency from all strategies so they can be run independently of `options.DeschedulerServer`.
Building on top of https://github.com/kubernetes-sigs/descheduler/pull/266

Drop descheduler server from strategies

---

OWNERS

I have been a reviewer for some time now and plan to remain active in the descheduler (and the rest of the scheduling sig). 
I am invested in this project as part of my day job and obviously a genuine interest in seeing it grow. I believe my active status in the rest of sig-scheduling also benefits this project.
I look forward to continuing to improve the descheduler as an active maintainer and assisting and encouraging others to contribute as well.

Add damemi to approvers

---

pkg/api/types.go
pkg/api/v1alpha1/types.go
pkg/api/v1alpha1/zz_generated.conversion.go
pkg/api/v1alpha1/zz_generated.deepcopy.go
pkg/api/zz_generated.deepcopy.go
pkg/descheduler/strategies/toomanyrestarts.go
pkg/descheduler/strategies/toomanyrestarts_test.go

Similar to https://github.com/kubernetes-sigs/descheduler/pull/240
This changes the PodsHavingTooManyRestarts params to be a pointer field, in order to prevent empty fields being serialized into JSON for unrelated strategies

Switch PodsHavingTooManyRestarts params to pointer

---

.gitignore
README.md
docs/user-guide.md
examples/pod-life-time.yml
pkg/api/types.go
pkg/api/v1alpha1/types.go
pkg/api/v1alpha1/zz_generated.conversion.go
pkg/api/v1alpha1/zz_generated.deepcopy.go
pkg/api/zz_generated.deepcopy.go
pkg/descheduler/descheduler.go
pkg/descheduler/strategies/pod_lifetime.go
pkg/descheduler/strategies/pod_lifetime_test.go

The new PodLifeTime descheduler strategy can be used to evict pods that were created more than the configured number of seconds ago.
In the below example pods created more than 24 hours ago will be evicted.
````
apiVersion: "descheduler/v1alpha1"
kind: "DeschedulerPolicy"
strategies:
"PodLifeTime":
enabled: true
params:
maxPodLifeTimeSeconds: 86400
````
Implements feature #205.

Add New PodLifeTime Strategy

---

.travis.yml

Cherry pick commit 4941f6a16becfa611ec31685632e4308633fc384 to the `release-1.17` branch.

Update Travis CI build matrix with latest k8s point releases

---

pkg/descheduler/evictions/evictions.go
pkg/descheduler/evictions/evictions_test.go
pkg/descheduler/strategies/duplicates.go
pkg/descheduler/strategies/lownodeutilization.go
pkg/descheduler/strategies/node_affinity.go
pkg/descheduler/strategies/node_taint.go
pkg/descheduler/strategies/pod_antiaffinity.go
pkg/descheduler/strategies/pod_lifetime.go
pkg/descheduler/strategies/toomanyrestarts.go

* 3a204dec97f3c4f020ef11d3e97e1aa6686e944d - all strategies log error from EvictPod method
* 55de4417949b59c204b388b1175f2173b7de280a - add pod namespace to pod eviction log messages

Add Additional Details To Pod Eviction Log Messages

---

pkg/descheduler/evictions/evictions.go

Indicate whether a pod is only virtually evicted so there's no confusion
with the real eviction.

Mention pod eviction is in dry mode when set

---

docs/release-guide.md

Starting with descheduler v0.18 a release branch will be created for
each descheduler minor release. The release guide has been updated with
the steps to create release branches.

Update Release Guide

---

docs/release-guide.md

This newly documented URL can be used to view the descheduler staging
registry in a web browser. This is easier to browse if the gcloud
command is not available.

Add URL For Viewing Staging Registry

---

README.md

The matrix has been updated with the soon the be released v0.18
details. Also, clarified the descheduler and k8s version compatibility
requirements and recommendations.

Update Compatibility Matrix in README

---

.travis.yml
Makefile

So CI can run 'make verify-gofmt' instead of ./hack/verify-gofmt in case the script location changes.

Add verify-gofmt make target

---

pkg/descheduler/node/node.go

These helpers are called in the node affinity strategy:
https://github.com/kubernetes-sigs/descheduler/blob/d7e93058d49f36afce55ae7a3cd9ff8ff624d53e/pkg/descheduler/strategies/node_affinity.go#L47
However at their current loglevels this leads to confusing logs, because if a pod doesn't fit on the current node that message is always logged. But if it doesn't fit on any node, that may not be logged unless log level is >=2 (see https://github.com/kubernetes-sigs/descheduler/blob/d7e93058d49f36afce55ae7a3cd9ff8ff624d53e/pkg/descheduler/node/node.go#L115). This leads to the confusing implication that eviction was intended, but not possible for some other reason.
Since these are used in the same check, they should have the same log levels for their relevant messages.

Standardize node affinity strategy logs

---

pkg/descheduler/strategies/lownodeutilization.go

`strategy.Enabled` is checked before calling `LowNodeUtilization`
/kind cleanup

Clean up code in LowNodeUtilization

---

README.md
pkg/descheduler/strategies/lownodeutilization.go
pkg/descheduler/strategies/lownodeutilization_test.go

We should stop evicting pods when any of totalCPU/totalMem/totalPods ran out, otherwise we may make underutilized nodes overutilized which is not efficient. To do this, there should be a value of totalCPU/Mem if their targetThreshold is not configured, here I set it to all of the remaining resources 
on these nodes.

Change break condition and thresholds validation for lowUtilization

---

pkg/descheduler/strategies/lownodeutilization_test.go

https://github.com/kubernetes-sigs/descheduler/pull/285 got merged before re-running the unit tests.

Add missing address of api.StrategyParameters

---

.travis.yml
Makefile

This adds a `make verify` target which will run all of the other `*-verify` targets. This would simplify our CI and make future changes to it easier as well

Add parent make verify target

---

Makefile

Follow up to https://github.com/kubernetes-sigs/descheduler/pull/307, the `make lint` target fails in CI with `make: golangci-lint: Command not found`. This should fix it
Currently we check if the binary exists in `$PATH`, but we download it directly to GOPATH if not. This could provide different results between local and CI runs (if a different version of the binary exists somewhere else in the path). This standardizes that and downloads it directly to the temporary `_output` directory, so as also not to interfere with any local copies of `golangci-lint` that may exist in developers' GOPATHs

Download golangci-lint to _output/bin directory

---

README.md
pkg/descheduler/pod/pods.go

This makes the `IsEvictable` check more verbose at `logLevel=4`, but breaking each check into its own conditional and logging errors for each one, finally outputting the full list if the pod does not also have the "evictable" annotation.
This gives output like this:
```
I0529 16:14:06.044444       1 pods.go:60] Pod dedicated-nodes-vkr8s in namespace test-ns is not evictable: Pod lacks an eviction annotation and fails the following checks: [pod is critical, pod does not have any ownerrefs]
```

Add more verbose logging to IsEvictable checks

---

.travis.yml

These tests are now covered by k8s test-infra prow tests.

Remove redundant tests from Travis CI

---

pkg/descheduler/strategies/lownodeutilization.go
pkg/descheduler/strategies/lownodeutilization_test.go

In lowNodeUtilization, only try to evict pods when we found evictable pods on node, otherwise, just skip and try next node.

Skip evicting when no evictable pod found on node

---

OWNERS

Based on https://github.com/kubernetes/community/blob/master/community-membership.md#requirements-1:
The following apply to the part of codebase for which one would be a reviewer in an OWNERS file (for repos using the bot).
> member for at least 3 months
For a couple of years now
> Primary reviewer for at least 5 PRs to the codebase
https://github.com/kubernetes-sigs/descheduler/pull/285
https://github.com/kubernetes-sigs/descheduler/pull/275
https://github.com/kubernetes-sigs/descheduler/pull/267
https://github.com/kubernetes-sigs/descheduler/pull/254
https://github.com/kubernetes-sigs/descheduler/pull/181
> Reviewed or merged at least 20 substantial PRs to the codebase
https://github.com/kubernetes-sigs/descheduler/pulls?q=is%3Apr+is%3Aclosed+assignee%3Aingvagabund
> Knowledgeable about …

Add myself to project reviewers

---

pkg/descheduler/descheduler.go
pkg/descheduler/evictions/evictions.go
pkg/descheduler/evictions/evictions_test.go
pkg/descheduler/pod/pods.go
pkg/descheduler/pod/pods_test.go
pkg/descheduler/strategies/duplicates.go
pkg/descheduler/strategies/duplicates_test.go
pkg/descheduler/strategies/lownodeutilization.go
pkg/descheduler/strategies/lownodeutilization_test.go
pkg/descheduler/strategies/node_affinity.go
pkg/descheduler/strategies/node_affinity_test.go
pkg/descheduler/strategies/node_taint.go
pkg/descheduler/strategies/node_taint_test.go
pkg/descheduler/strategies/pod_antiaffinity.go
pkg/descheduler/strategies/pod_antiaffinity_test.go
pkg/descheduler/strategies/pod_lifetime.go
pkg/descheduler/strategies/pod_lifetime_test.go
pkg/descheduler/strategies/toomanyrestarts.go
pkg/descheduler/strategies/toomanyrestarts_test.go
test/e2e/e2e_test.go

`evictLocalStoragePods` is (effectively) only used by the functions `ListEvictablePodsOnANode` and `IsEvictable`, both of which make sense to be methods of `PodEvictor`.
In addition, passing this field to every strategy when it is really a component-level configuration option is cumbersome and unnecessary (this was discussed in https://github.com/kubernetes-sigs/descheduler/pull/305 and the PRs related to it).
So I think it makes sense to have this be a property of `PodEvictor`. Each strategy already accepts a `PodEvictor` if they want to access it directly and this minimizes their function signatures.

Make evictLocalStoragePods a property of PodEvictor

---

pkg/descheduler/evictions/evictions.go
pkg/descheduler/strategies/duplicates.go
pkg/descheduler/strategies/lownodeutilization.go
pkg/descheduler/strategies/node_affinity.go
pkg/descheduler/strategies/node_taint.go
pkg/descheduler/strategies/pod_antiaffinity.go
pkg/descheduler/strategies/pod_lifetime.go
pkg/descheduler/strategies/toomanyrestarts.go

Related to the changes in https://github.com/kubernetes-sigs/descheduler/pull/287, because the PodEvictor logs when a pod is successfully evicted (either in dry-run or normal mode) this message becomes redundant and confusing when in dry run. For example, it currently looks like:
```
I0528 09:23:48.664691       1 evictions.go:100] Evicted pod in dry run mode: "hello1-54d7977cd-l8wx7" in namespace "test"
I0528 09:23:48.664700       1 pod_antiaffinity.go:50] Evicted pod: "hello1-54d7977cd-l8wx7" because of existing anti-affinity
```
This extra message doesn't provide much information, though it may be reasonable to add an extra "reason" parameter to `podEvictor.EvictPod` to give context on what strategy specifically caused the eviction (since all eviction logs now just originate from …

Remove redundant eviction log message and add "Reason" param to EvictPod

---

README.md
pkg/descheduler/pod/pods.go
pkg/descheduler/pod/pods_test.go
pkg/descheduler/strategies/lownodeutilization.go
pkg/descheduler/strategies/lownodeutilization_test.go
pkg/descheduler/strategies/pod_antiaffinity.go
pkg/descheduler/strategies/pod_antiaffinity_test.go
test/test_utils.go

As #294  mentioned, we may need to sort pods in other strategies, so I moved this func to pod util.

Move sortPodsBasedOnPriority to pod util

---

examples/policy.yaml

Fix incorrect example causing following error in runtime:
```
I0628 12:23:46.112073       1 toomanyrestarts.go:36] PodsHavingTooManyRestarts thresholds not set
```

examples: fix typo

---

pkg/descheduler/strategies/lownodeutilization.go

fix #331 
My initial thought was using [list func](https://github.com/kubernetes-sigs/descheduler/blob/7ece10a643906874bd3377a36fe5d8641db95804/pkg/descheduler/pod/pods.go#L34:6) to get all evictable pods on node rather than [classifyPods](https://github.com/kubernetes-sigs/descheduler/blob/7ece10a643906874bd3377a36fe5d8641db95804/pkg/descheduler/strategies/lownodeutilization.go#L412), but as this list func will get pods from apiserver and may have some conflicts with [NodePodsMap](https://github.com/kubernetes-sigs/descheduler/blob/7ece10a643906874bd3377a36fe5d8641db95804/pkg/descheduler/strategies/lownodeutilization.go#L44) which descheduler uses to calculate node's usage, I refactor `classifyPods` to only divide pods into `nonRemovable` and `removable`.

Support only one sorting strategy in lowNodeUtilization

---

pkg/descheduler/evictions/evictions.go
pkg/descheduler/strategies/duplicates_test.go
pkg/descheduler/strategies/lownodeutilization_test.go
pkg/descheduler/strategies/node_affinity_test.go
pkg/descheduler/strategies/node_taint_test.go
pkg/descheduler/strategies/pod_antiaffinity_test.go
pkg/descheduler/strategies/pod_lifetime_test.go
pkg/descheduler/strategies/toomanyrestarts_test.go

As mentioned in [comment](https://github.com/kubernetes-sigs/descheduler/blob/7ece10a643906874bd3377a36fe5d8641db95804/pkg/descheduler/strategies/lownodeutilization_test.go#L57), `expectedPodsEvicted` represents both expected result and evictor's limitation, it may make testcases pass unexpectedly, so I added another param `maxPodsToEvictPerNode` here. And I found two testcases are affected by this change, I gave an limitation to `without priorities`, and changed another's expected result.

Add maxPodsToEvictPerNode to LowNodeUtilization testcase struct

---

pkg/descheduler/strategies/duplicates.go

Currently, appending `podContainerKeys` to `duplicateKeysMap[podContainerKeys[0]]` is inside the for loop, so it may append same keys multiple times.

avoid appending list multiple times in RemoveDuplicates

---

Makefile
test/run-e2e-tests.sh

This moves the kind setup (previously used by Travis) to the e2e runner script
to accomodate the switch to Prow. This provides a KIND_E2E env var to specify
whether to run the tests in kind, or (by default) to run locally).
Backporting https://github.com/kubernetes-sigs/descheduler/pull/340

Move kind setup to e2e script

---

.github/workflows/release.yaml
Makefile
charts/descheduler/.helmignore
charts/descheduler/Chart.yaml
charts/descheduler/README.md
charts/descheduler/templates/NOTES.txt
charts/descheduler/templates/_helpers.tpl
charts/descheduler/templates/clusterrole.yaml
charts/descheduler/templates/clusterrolebinding.yaml
charts/descheduler/templates/configmap.yaml
charts/descheduler/templates/cronjob.yaml
charts/descheduler/templates/serviceaccount.yaml
charts/descheduler/values.yaml

This PR adds a native _Helm_ chart to this repository at `charts/descheduler` and uses [GitHub Actions](https://github.com/features/actions), specifically the [Helm actions](https://github.com/helm?q=action&type=&language=), to validate and release the chart (see the following rules).
- PRs with changes to `charts/**` will trigger the _lint-test_ action
- Tags with the pattern `chart-*` will trigger the _release_ action
**IMPORTANT** - For this PR to work the `helm/chart-releaser-action` [pre-requisites](https://github.com/helm/chart-releaser-action#pre-requisites) need to be completed.

Add Helm chart

---

charts/descheduler/Chart.yaml
docs/release-guide.md

The descheduler now has an official helm chart. This change documents the
process to release a new helm chart artifact.

Update Release Documentation For Helm Charts

---

.github/workflows/release.yaml
Makefile
charts/descheduler/.helmignore
charts/descheduler/Chart.yaml
charts/descheduler/README.md
charts/descheduler/templates/NOTES.txt
charts/descheduler/templates/_helpers.tpl
charts/descheduler/templates/clusterrole.yaml
charts/descheduler/templates/clusterrolebinding.yaml
charts/descheduler/templates/configmap.yaml
charts/descheduler/templates/cronjob.yaml
charts/descheduler/templates/serviceaccount.yaml
charts/descheduler/values.yaml
docs/release-guide.md

Cherry pick the below commits from the master branch:
* 4507a90bb6b40a93993c9b0a04bcccfd7252ba3b - initial helm chart
* c7692a2e9fa59765bcbc769b3875415296891b4c - release docs for helm charts
* ca8f1051ebeed94e3ef82c8d8b3656d5f5a22446 - change helm chart version to 0.18.0
After this is merged the proposed release process in #351 could be executed to release to first official descheduler helm chart.

Cherry Pick: Add helm chart release-1.18

---

charts/descheduler/Chart.yaml

This still represents Descheduler v0.18.0, but this is to make a small change
in order to try triggering the Helm chart-releaser action.

Bump Helm chart to version 0.18.1

---

.github/workflows/release.yaml
charts/descheduler/Chart.yaml
docs/release-guide.md

Basing this action on push to `chart-*` tags doesn't work: the action itself
creates the new release tag, so trying to push the changes to a tag ends up
with the releaser comparing the changes to themself (and failing).
This also renames the chart from "descheduler" to "descheduler-helm-chart", to
avoid confusion with automated releases.

Update Helm release action to work on release branches

---

.github/workflows/release.yaml
charts/descheduler/Chart.yaml
docs/release-guide.md

Basing this action on push to `chart-*` tags doesn't work: the action itself
creates the new release tag, so trying to push the changes to a tag ends up
with the releaser comparing the changes to themself (and failing).
This also renames the chart from "descheduler" to "descheduler-helm-chart", to
avoid confusion with automated releases.

[release-1.18] Update Helm release action to work on release branches

---

docs/user-guide.md

Add documentation on combining descheduler, NPD and CA to autoheal Node problems. This is a real-world use case in production at my organization. We have even written some custom NPD plugins specific to our internal infrastructure and observed those problems be autohealed with this setup.

Add NPD+CA autohealing use case to user guide

---

pkg/descheduler/strategies/lownodeutilization_test.go

If we fix these spaces, there will be no misspell errors in go report

remove unnecessary line feed  in log messages

---

Makefile

With the new Helm chart releaser action, `descheduler-helm-chart` tags are getting parsed as the most recent tag and pushed to our [staging repo](https://console.cloud.google.com/gcr/images/k8s-staging-descheduler/GLOBAL/descheduler?gcrImageListsize=30) on automated builds. You can see this by running `make image` locally:
```
$ make image
docker build -t descheduler:descheduler-helm-chart-0.18.1-11-g5bb038953 .
...
```
This update makes it so the latest *image* version is only considered if it's prefixed with `v`. New output:
```
$ make image
docker build -t descheduler:v0.18.0-79-g597089902 .
```
Because [Helm chart releases are separate from Descheduler releases](https://github.com/kubernetes-sigs/descheduler/pull/298#issuecomment-648683361) I think it's important that our image …

Update version parsing to exclude helm-chart tags

---

charts/descheduler/README.md
charts/descheduler/values.yaml
docs/user-guide.md
kubernetes/cronjob.yaml
kubernetes/job.yaml

The k8s project recently cut over to the new official k8s.gcr.io
container registry. The descheduler image can now be pulled from
k8s.gcr.io. This is just a new DNS name for the container registry. The
previously documented DNS names for the registry still work, but
require more typing.

Update Container Registry to k8s.gcr.io

---

pkg/descheduler/strategies/pod_antiaffinity.go

The validation func is not called in `RemovePodsViolatingInterPodAntiAffinity`.

Add missing validation in PodAntiAffinity

---

pkg/descheduler/strategies/duplicates.go

This fixes a panic that occurs if a pod has no ownerrefs
later on in the strategy. If a pod has no ownerrefs, there's
nothing for us to do with it.
For reference, the panic that occurs looks like this:
```
E0807 13:35:30.950616       1 runtime.go:78] Observed a panic: runtime.boundsError{x:0, y:0, signed:true, code:0x0} (runtime error: index out of range [0] with length 0)
goroutine 1 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x159d940, 0xc000958400)
/go/src/sigs.k8s.io/descheduler/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
/go/src/sigs.k8s.io/descheduler/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x159d940, 0xc000958400) …
```

Add check for ownerref length in DuplicatePods strategy

---

README.md
charts/descheduler/templates/clusterrole.yaml
kubernetes/rbac.yaml
pkg/api/types.go
pkg/api/v1alpha1/types.go
pkg/api/v1alpha1/zz_generated.conversion.go
pkg/api/v1alpha1/zz_generated.deepcopy.go
pkg/api/zz_generated.deepcopy.go
pkg/descheduler/evictions/evictions.go
pkg/descheduler/evictions/evictions_test.go
pkg/descheduler/strategies/duplicates.go
pkg/descheduler/strategies/lownodeutilization.go
pkg/descheduler/strategies/node_affinity.go
pkg/descheduler/strategies/node_taint.go
pkg/descheduler/strategies/pod_antiaffinity.go
pkg/descheduler/strategies/pod_lifetime.go
pkg/descheduler/strategies/toomanyrestarts.go
pkg/utils/pod.go
pkg/utils/priority.go
test/e2e/e2e_test.go

Fixes #329 
Introduce a new configuration for each strategies which allows users to define a PriorityClass which is used by PodEvictor to check if a pod is evictable.
TODO:

Allow custom priority threshold

---

pkg/api/types.go
pkg/api/v1alpha1/types.go
pkg/api/v1alpha1/zz_generated.conversion.go
pkg/api/v1alpha1/zz_generated.deepcopy.go
pkg/api/zz_generated.deepcopy.go
pkg/descheduler/strategies/node_affinity.go
pkg/descheduler/strategies/node_taint.go
pkg/descheduler/strategies/pod_antiaffinity.go
pkg/descheduler/strategies/pod_lifetime.go
pkg/descheduler/strategies/toomanyrestarts.go
test/e2e/e2e_test.go

So when the data is serialized into a json, the field is omitted.

Promote Namespaces field to a pointer

---

charts/descheduler/Chart.yaml

Changing the maintainer for the helm chart to SIG scheduling instead of
an individual person.

Update Maintainer Details In Helm Chart

---

pkg/descheduler/evictions/evictions.go
pkg/descheduler/evictions/evictions_test.go
pkg/descheduler/pod/pods.go
pkg/descheduler/strategies/duplicates.go
pkg/descheduler/strategies/lownodeutilization.go
pkg/descheduler/strategies/node_affinity.go
pkg/descheduler/strategies/node_taint.go
pkg/descheduler/strategies/pod_antiaffinity.go
pkg/descheduler/strategies/pod_lifetime.go
pkg/descheduler/strategies/toomanyrestarts.go
pkg/utils/pod.go
test/e2e/e2e_test.go

Use WithXXX methods to extend the list of constraints to also
provide a reasonable error message.

Redefine IsEvictable to be customizable for a particular strategy

---

pkg/descheduler/pod/pods.go
pkg/descheduler/strategies/lownodeutilization_test.go

LowNodeUtilization: use clientset in testing, drop all custom reactors

---

Dockerfile
Makefile
docs/contributor-guide.md
go.mod
hack/update-gofmt.sh
hack/verify-gofmt.sh
pkg/descheduler/node/node_test.go
test/e2e/e2e_test.go

As part of the k8s 1.19 release cycle the Go version is being bumped to
1.15.0. Updating the descheduler to use Go 1.15 prior to the descheduler
v0.19.0 release.
See below issues for reference:
* https://github.com/kubernetes/release/issues/1421
* https://github.com/kubernetes/kubernetes/issues/93484

Update To Go 1.15.0

---

pkg/descheduler/descheduler.go
pkg/descheduler/node/node.go
pkg/descheduler/strategies/duplicates.go
pkg/descheduler/strategies/lownodeutilization.go
pkg/descheduler/strategies/node_affinity.go
pkg/descheduler/strategies/node_taint.go
pkg/descheduler/strategies/pod_antiaffinity.go
pkg/descheduler/strategies/pod_lifetime.go
pkg/descheduler/strategies/toomanyrestarts.go
pkg/utils/pod.go

Part of #347 
There were some logs that probably don't make sense to use structured logging, such as:
https://github.com/kubernetes-sigs/descheduler/blob/9746fd300f4c4bdaf9fdd953c145f05bf07cf721/pkg/descheduler/strategies/lownodeutilization.go#L108
But let me know otherwise.
----
Another remaining part is adding '--logging-format' flag for JSON output. I was thinking of doing that in another PR after  [#92707](https://github.com/kubernetes/kubernetes/pull/92707) gets merged.
Logs when you run:
`./_output/bin/descheduler --kubeconfig ~/.kube/config --policy-config-file ./examples/policy.yaml --v 6
`
[Before](https://gist.github.com/farah/3d136b1ec3e5951ac452c25f436b2e7f) and [After](https://gist.github.com/farah/6e357063e33141013cdda33670f433b4)

Change klog to use structured logging

---

README.md

Updated the README with the link to the official descheduler helm chart
on https://hub.helm.sh. This makes it easier for end users to install the
desceduler using helm.

Add Link To Helm Hub

---

pkg/descheduler/strategies/pod_antiaffinity.go
pkg/descheduler/strategies/pod_antiaffinity_test.go

While non-evictable pods should never be evicted, they should still be
considered when calculating PodAntiAffinity violations. For example, you
may have an evictable pod that should not be running next to a system-critical
static pod. We currently filter IsEvictable before checking for Affinity violations,
so this case would not be caught.
/kind bug

Move IsEvictable check in PodAntiAffinity

---

pkg/descheduler/evictions/evictions.go
pkg/descheduler/strategies/lownodeutilization.go
pkg/descheduler/strategies/node_affinity.go
pkg/utils/predicates.go

Convert logs to use structured logging

---

pkg/descheduler/strategies/lownodeutilization.go

Each time a pod's resource consumption is translated into a fraction (number in (0; 1) interval), some precision is lost. Instead, summing all resource consumption absolutely allows to compute the resource usage precisely (up to rounding losses when using Quantity type).
Storing resources consumption into a map of  Quantities also allows to simplify arguments of functions used in the code.

Refactor low node utilization

---

docs/contributor-guide.md
hack/kind_config.yaml
test/run-e2e-tests.sh

This is a cherry-pick of https://github.com/kubernetes-sigs/descheduler/pull/401 for the `release-1.19` branch.

Update e2e tests to use kind v0.9.0

---

README.md
pkg/descheduler/strategies/duplicates.go

Fixes #405 
This also adds a `parameters` table to each strategy for a quicker reference at what the params are available

Add Namespace filtering to RemoveDuplicates strategy

---

pkg/descheduler/strategies/lownodeutilization.go

The k8s.io/klog/v2 package does not currently support structured logging
for warning level log messages. Therefore update the one call in the
code base using klog.Warningf to instead use klog.InfoS.

Convert Last Log Message To Structured Logging

---

pkg/descheduler/evictions/evictions.go

Update Event Logging to Use Structured Logging

---

charts/descheduler/README.md
charts/descheduler/templates/clusterrole.yaml
charts/descheduler/templates/podsecuritypolicy.yaml
charts/descheduler/values.yaml

This commit adds restrictive PodSecurityPolicy, which can be
optionally created, so descheduler can be deployed on clusters with
PodSecurityPolicy admission controller, but which do not ship default
policies.
Signed-off-by: Mateusz Gozdek <mgozdekof@gmail.com>

charts/descheduler: add PodSecurityPolicy support

---

.github/workflows/release.yaml
README.md
charts/descheduler/Chart.yaml
charts/descheduler/README.md

Now that the [helm/chart-releaser](https://github.com/helm/chart-releaser/releases/tag/v1.1.0) and [helm/chart-releaser-action](https://github.com/helm/chart-releaser-action/releases/tag/v1.1.0) can support creating a custom tag name for helm chart release the _descheduler_ helm chart no longer needs to be named to avoid tag collisions.
This PR updates the CI tooling for helm, renames the _descheduler_ helm chart to `descheduler` from `descheduler-helm-chart` and updates the related documentation.
On applying this merge request the existing helm charts will not be modified or removed and only future releases will be impacted. My suggestion would be to use the [helm/chart-releaser](https://github.com/helm/chart-releaser) with the `--commit` flag to re-create the existing charts with the …

Rename Helm chart

---

Dockerfile
Makefile
cmd/descheduler/app/version.go

Prior to this change the output from the command "descheduler version" when run using the official container images from k8s.gcr.io would always output an empty string. See below for an example.
```
docker run k8s.gcr.io/descheduler/descheduler:v0.19.0 /bin/descheduler version
Descheduler version {Major: Minor: GitCommit: GitVersion: BuildDate:2020-09-01T16:43:23+0000 GoVersion:go1.15 Compiler:gc Platform:linux/amd64}
```
This change makes it possible to pass the descheduler version information to the automated container image build process and also makes it work for local builds too.
Fixes #425

Fix Version Output For Automated Container Builds

---

charts/descheduler/README.md
charts/descheduler/templates/cronjob.yaml
charts/descheduler/values.yaml

Prior to this commit the helm chart used to install the descheduler
CronJob did not set container requests or limits. This is considered
an anti-pattern when deploying applications on k8s.
Set descheduler container resources to make it a burstable pod. This
will ensure a high quality experience for end users when deploying
descheduler into their clusters using the instructions from the README.
The default values choosen for CPU/Memory are not based on any real data.

Set Container Resources In Helm Chart

---

kubernetes/cronjob/cronjob.yaml
kubernetes/job/job.yaml

Prior to this commit the YAML manifests used to install the descheduler
Job and CronJob did not set container requests or limits. This is
considered an anti-pattern when deploying applications on k8s.
Set descheduler container resources to make it a burstable pod. This
will ensure a high quality experience for end users when deploying
descheduler into their clusters using the instructions from the README.
The values choosen for CPU/Memory are not based on any real data.

Set Container Resources In YAML Manifests

---

pkg/descheduler/strategies/lownodeutilization.go

Entry params are in interval <0; 100>. Have logs respect that as well.
To log `usagePercentage=map[cpu:75 memory:0 pods:66.66666666666667]` instead of `usagePercentage=map[cpu:0.75 memory:0 pods:0.6666666666666667]`
```
$ go test -v sigs.k8s.io/descheduler/pkg/descheduler/strategies -run TestLowNodeUtilization
=== RUN   TestLowNodeUtilization
=== RUN   TestLowNodeUtilization/no_evictable_pods
I1124 14:51:07.941383  462893 lownodeutilization.go:268] "Node is underutilized" node="n2" usage=map[cpu:0 memory:0 pods:0] usagePercentage=map[cpu:0 memory:0 pods:0]
I1124 14:51:07.941418  462893 lownodeutilization.go:274] "Node is appropriately utilized" node="n3" usage=map[cpu:0 memory:0 pods:0] usagePercentage=map[cpu:0 memory:0 pods:0]
I1124 14:51:07.941433  462893 lownodeutilization.go:271] …
```

LowNodeUtilization: express usagePercentage multiplied by 100

---

charts/descheduler/README.md
charts/descheduler/templates/cronjob.yaml
charts/descheduler/values.yaml

Allow end users to optionally set the descheduler CronJob
.spec.startingDeadlineSeconds when installing using helm.
Fixes #432

Update Helm Chart To Allow Setting startingDeadlineSeconds

---

pkg/descheduler/strategies/topologyspreadconstraint.go

This adds a simple log message to indicate to users that the topology strategy is running (all other strategies log a message for each node they are processing, but since topology spread processes by namespace rather than node that would be a lot of messages).
Also added a log message when pods are skipped due to node selector/affinity
/priority low
/kind cleanup

Add more topology spread logs

---

Dockerfile

The main k/k repo has updated to Go 1.15.5 for the upcoming k8s v1.20.0
release. See below PR for reference.
https://github.com/kubernetes/kubernetes/pull/95776

Bump To Go 1.15.5

---

Dockerfile
Makefile
cloudbuild.yaml
docs/release-guide.md
docs/user-guide.md

Previous to this change official descheduler container images only
supported the AMD64 hardware architecture. This change enables
building official descheduler container images for multiple
architectures.
The initially supported architectures are AMD64 and ARM64.
Fixes #445

Enable Multi-Arch Container Image Builds

---

pkg/descheduler/strategies/topologyspreadconstraint.go
pkg/descheduler/strategies/topologyspreadconstraint_test.go

This logic is broken, when passing in any list of excluded namespaces it will skip all namespaces since it just looks at the size of include+exclude together. This PR breaks them out into separate checks for sanity
/kind bug
/priority critical-urgent

Fix broken namespace logic in TopologySpreadConstraint

---

.github/workflows/release.yaml
charts/descheduler/Chart.yaml
charts/descheduler/README.md

**IMPORTANT** - This needs to be merged before PR https://github.com/kubernetes-sigs/descheduler/pull/457 and PR https://github.com/kubernetes-sigs/descheduler/pull/459.
This PR will deprecate the existing [descheduler-helm-chart](https://artifacthub.io/packages/helm/descheduler/descheduler-helm-chart) ready for it to renamed to _descheduler_.

Helm chart rename - Step #1

---

.github/workflows/release.yaml
README.md
charts/descheduler/Chart.yaml
charts/descheduler/README.md

IMPORTANT - This needs to be merged after PR #457 and PR #459.
This PR will release the v0.19 chart with the new _descheduler_ name.

Helm chart rename - Step #3

---

charts/descheduler/Chart.yaml
charts/descheduler/README.md
charts/descheduler/templates/cronjob.yaml
charts/descheduler/values.yaml

Allow end users to optionally set the descheduler CronJob `.spec.successfulJobsHistoryLimit` and `.spec.failedJobsHistoryLimit` when installing using helm chart.

Allow setting options successfulJobsHistoryLimit and failedJobsHistoryLimit for cronjob

---

pkg/descheduler/strategies/topologyspreadconstraint.go
pkg/descheduler/strategies/topologyspreadconstraint_test.go

This just adds a shortcut to skip doing all the sorting/balancing calculations if all domains in a topology for a constraint are already within the MaxSkew of each other
/kind cleanup

Skip topology calculations if domains are already balanced

---

Dockerfile
Dockerfile.dev

Can add this to the cronjob/job kubernetes manifests
```
securityContext:
runAsNonRoot: true
readOnlyRootFilesystem: true
```
/cc @seanmalloy

Run as user 1000 so pod can be runAsNonRoot for security purposes

---

pkg/descheduler/descheduler.go
pkg/descheduler/node/node.go
pkg/descheduler/node/node_test.go
test/e2e/e2e_test.go

/kind design
ReadyNodes's  parm about 'stopChannel' is not being used

refactor: remove unused code

---

pkg/descheduler/strategies/topologyspreadconstraint.go
pkg/descheduler/strategies/topologyspreadconstraint_test.go

TopologySpreadConstraint does not properly check if a pod is evictable before calling `EvictPod` (due to the fact that it does not rely on `ListPodsOnNode`, which takes `IsEvictable` as a parameter and does the check there for most of the other strategies).
This breaks the check out explicitly. It could also be refactored to do this check in `balanceDomains`, when building the list of evictable pods.

Fix TopologySpread bug that evicts non-evictable pods

---

README.md
pkg/api/types.go
pkg/api/v1alpha1/types.go
pkg/api/v1alpha1/zz_generated.conversion.go
pkg/descheduler/strategies/topologyspreadconstraint.go

Add a parameter to include soft topology spread constraints

---

README.md
pkg/api/types.go
pkg/api/v1alpha1/types.go
pkg/api/v1alpha1/zz_generated.conversion.go
pkg/api/v1alpha1/zz_generated.deepcopy.go
pkg/api/zz_generated.deepcopy.go
pkg/apis/componentconfig/types.go
pkg/apis/componentconfig/v1alpha1/types.go
pkg/apis/componentconfig/v1alpha1/zz_generated.conversion.go
pkg/descheduler/descheduler.go
pkg/descheduler/evictions/evictions.go
pkg/descheduler/strategies/duplicates_test.go
pkg/descheduler/strategies/lownodeutilization_test.go
pkg/descheduler/strategies/node_affinity_test.go
pkg/descheduler/strategies/node_taint_test.go
pkg/descheduler/strategies/pod_antiaffinity_test.go
pkg/descheduler/strategies/pod_lifetime_test.go
pkg/descheduler/strategies/toomanyrestarts_test.go
pkg/descheduler/strategies/topologyspreadconstraint_test.go
test/e2e/e2e_test.go

Fixes https://github.com/kubernetes-sigs/descheduler/issues/96

Add option to ignore pods with PVCs from eviction

---

pkg/descheduler/strategies/lownodeutilization.go

I have a node with a CPU that can be allocated 3000m. I actually used 2015m. I set the threshold value to 70%. So my node has not reached this threshold, but I check the log and show that the CPU usage is 100% because When calculating usagePercentage, the Value() method is used, so here is the calculation of 3/3 as 100%, I think this may be misleading.

Modify resourceUsage.Value() to resourceUsage.MilliValue()

---

Dockerfile

The main k/k repo was updated to Go 1.15.8 for the upcoming k8s v1.21.0
release. See below PR for reference.
https://github.com/kubernetes/release/issues/1895

Bump To Go 1.15.8

---

pkg/descheduler/descheduler.go
pkg/descheduler/strategies/lownodeutilization.go
pkg/descheduler/strategies/node_affinity.go

This is logging the total pods evicted across all strategies (with the shared `podEvictor`). So, moving it out of node affinity and lowNodeUtilization, and into the main descheduler loop.
/kind bug
fixes https://github.com/kubernetes-sigs/descheduler/issues/501

Move 'total pods evicted' log message to main loop

---

README.md
pkg/descheduler/strategies/lownodeutilization.go

Log and README optimization for LowNodeUtilization

---

README.md
pkg/api/types.go
pkg/api/v1alpha1/types.go
pkg/api/v1alpha1/zz_generated.conversion.go
pkg/api/v1alpha1/zz_generated.deepcopy.go
pkg/api/zz_generated.deepcopy.go
pkg/descheduler/pod/pods.go
pkg/descheduler/pod/pods_test.go
pkg/descheduler/strategies/node_affinity.go
pkg/descheduler/strategies/node_taint.go
pkg/descheduler/strategies/pod_antiaffinity.go
pkg/descheduler/strategies/pod_lifetime.go
pkg/descheduler/strategies/pod_lifetime_test.go
pkg/descheduler/strategies/toomanyrestarts.go
test/e2e/e2e_test.go

Fixes: #195 
TODO:
/kind feature

Filter pods by labelSelector

---

README.md

Fixes https://github.com/kubernetes-sigs/descheduler/issues/514
Clarifies what we mean by "number of pods in terms of percentage" with a link to upstream docs

Clarify resource percentage calculation in README

---

Makefile

Add ARM32v7 in addition to the currently supported architectures. This
will allow running descheduler on Raspberry Pi v3 devices.
Fixes #475

Enable ARM32v7 Container Image Builds

---

Dockerfile
Dockerfile.dev
OWNERS

For roughly the past year damemi has been the only active approver for
the descheduler. Therefore move the inactive approvers to emeritus
status. This will help clarify to contributors who should be assigned to
pull requests.

Move Inactive Maintainers to Emeritus Status

---

pkg/descheduler/strategies/topologyspreadconstraint.go
pkg/descheduler/strategies/topologyspreadconstraint_test.go

Fixes https://github.com/kubernetes-sigs/descheduler/issues/524

(TopologySpread) Evict pods with selectors that match multiple nodes

---

charts/descheduler/README.md

The resources.cpuRequest and resources.memoryRequest varialbes are
not valid in the helm chart values.yaml file. The correct varialbe
name for setting the requests and limits is resources.
Also, fixed white space alignment in the markdown table.

Correct Helm Chart Docs For Container Requests and Limits

---

README.md
pkg/descheduler/evictions/evictions_test.go
test/test_utils.go

Similar to ReplicaSet, ReplicationController, and Jobs pods with a
StatefulSet metadata.ownerReference are considered for eviction.
Document this, so that it is clear to end users.

Document That Descheduler Considers StatefulSets For Eviction

---

Dockerfile
docs/contributor-guide.md
go.mod
go.sum
hack/update-gofmt.sh
hack/verify-gofmt.sh

https://github.com/kubernetes/kubernetes/pull/100106

Bump go to 1.16

---

README.md

The master branch always represents the next release of the
descheduler. Therefore applying the descheduler k8s manifests
from the master branch is not considered stable. It is best for
users to install descheduler using the released tags.
Fixes #532 
/kind documentation

Use Tags In Kustomize Documentation

---

.gitignore
README.md
pkg/api/types.go
pkg/api/v1alpha1/types.go
pkg/descheduler/descheduler.go
pkg/descheduler/evictions/evictions.go
pkg/descheduler/evictions/evictions_test.go
pkg/descheduler/strategies/duplicates_test.go
pkg/descheduler/strategies/lownodeutilization_test.go
pkg/descheduler/strategies/node_affinity_test.go
pkg/descheduler/strategies/node_taint_test.go
pkg/descheduler/strategies/pod_antiaffinity_test.go
pkg/descheduler/strategies/pod_lifetime_test.go
pkg/descheduler/strategies/toomanyrestarts_test.go
pkg/descheduler/strategies/topologyspreadconstraint_test.go
pkg/utils/pod.go
test/e2e/e2e_test.go
test/run-e2e-tests.sh

Fixes #378
The `evictSystemCriticalPods` flag disables priority checking by the descheduler. When this flag is true, pods of any priority are evicted, including system pods like `kube-dns`. Daemonsets, Mirror Pods, Static Pods, and pods without owner references are not evicted when this flag is true. If `thresholdPriority` or `thresholdPriorityClassName` are set, and `evictSystemCriticalPods` is true, then the threshold priority filtering will be disabled.

Added EvictSystemCriticalPods flag to descheduler

---

pkg/api/v1alpha1/zz_generated.conversion.go
pkg/api/v1alpha1/zz_generated.deepcopy.go
pkg/api/zz_generated.deepcopy.go

Ran "make gen" using Go 1.16.1. Some changes were merged, but "make gen"
was not run. This fixes the problem.
See below PR for reference:
https://github.com/kubernetes-sigs/descheduler/pull/523

Update Generated Code

---

test/e2e/e2e_test.go

If the goroutine running the descheduler strategies times out, it will still write to the channel without a reader thus causing a goroutine leak. To fix this, use a buffered channel (c).

e2e_test: fix goroutine leak

---

README.md
pkg/descheduler/strategies/lownodeutilization.go
pkg/descheduler/strategies/lownodeutilization_test.go
test/test_utils.go

Fixes #399 
Support extended/custom resources, so as to evict pods based on generic resource including but not limited to (cpu, memory, pods)

Support extended resources in LowNodeUtilization

---

README.md
pkg/descheduler/strategies/lownodeutilization.go

To avoid:
```
I0210 11:56:04.137956 3309277 lownodeutilization.go:389] "Updated node usage" updatedUsage={node:0xc000460000 usage:map[cpu:0xc00042b480 memory:0xc00042b4c0 pods:0xc00042b500] allPods:[0xc0004a0000 0xc0004a03e8 0xc0004a07d0 0xc0004a0bb8 0xc0004a0fa0 0xc0004a1388 0xc0004a1770 0xc0004a1b58] lowResourceThreshold:map[cpu:0xc00042b540 memory:0xc00042b580 pods:0xc00042b5c0] highResourceThreshold:map[cpu:0xc00042b600 memory:0xc00042b640 pods:0xc00042b680]}
I0210 11:56:04.138829 3309277 lownodeutilization.go:389] "Updated node usage" updatedUsage={node:0xc000460000 usage:map[cpu:0xc00042b480 memory:0xc00042b4c0 pods:0xc00042b500] allPods:[0xc0004a0000 0xc0004a03e8 0xc0004a07d0 0xc0004a0bb8 0xc0004a0fa0 0xc0004a1388 0xc0004a1770 0xc0004a1b58] lowResourceThreshold:map[cpu:0xc00042b540 …
```

LNU: improve nodeUsage logging

---

Makefile
hack/verify-conversions.sh

This PR fixes: https://github.com/kubernetes-sigs/descheduler/issues/483
As part of this change, we want to add steps to ensure that `make gen` has been run and there are no changes being generated during the PR. 
For now, I've tested the code in local for the steps which I've added in the Makefile and below is the output for same,
```
->  make verify-gen
./hack/verify-makegen.sh
Diff in the PR has changed
make: *** [Makefile:112: verify-gen] Error 1
```
Since it's reporting error, which means it's pointing that the generators have been downloaded at the latest in the `_output` directory in my local.

Add verify scripts for make gen to run during PR

---

Makefile
hack/verify-deep-copies.sh

This PR is related to: https://github.com/kubernetes-sigs/descheduler/issues/483
This PR contains changes for verifying deep-copies generator. Below are the logs,
1. When there are no changes,
```
-bash>descheduler(add-verify-script-deep-copies)$
->  make verify-gen
./hack/verify-conversions.sh
Generated conversions verified.
./hack/verify-deep-copies.sh
Generated deep-copies verified.
```
2. After making a change in the api similar to the change mentioned [here](https://github.com/kubernetes-sigs/descheduler/pull/507#issuecomment-792820077) for validating failed scenario,
```
-bash>descheduler(add-verify-script-deep-copies)$
->  ./hack/verify-deep-copies.sh
Generated deep-copies output differs:
diff -Naupr pkg/api/v1alpha1/zz_generated.deepcopy.go …
```

Add verify script for deep-copies generator

---

pkg/descheduler/strategies/duplicates_test.go
pkg/descheduler/strategies/lownodeutilization_test.go
pkg/descheduler/strategies/node_affinity_test.go
pkg/descheduler/strategies/node_taint_test.go
pkg/descheduler/strategies/pod_antiaffinity_test.go
pkg/descheduler/strategies/pod_lifetime_test.go
pkg/descheduler/strategies/toomanyrestarts_test.go

fix eviction APIVersion typo in test case

Updating policy api version used in pod evictor

---

README.md
docs/user-guide.md
kubernetes/cronjob/cronjob.yaml
kubernetes/job/job.yaml

* Added v0.21 references to README
* Update k8s manifests with v0.21.0 references
* Added table with list of supported architectures by release

Update Docs and Manifests for v0.21.0

---

pkg/utils/predicates.go

When `len(taints) == 0`, the `for-loop` will be skipped and return `true` directly.

code cleanup: remove check on length

---

pkg/descheduler/descheduler.go

I noticed this while thinking about the new API options we started discussing in https://github.com/kubernetes-sigs/descheduler/issues/486
Right now we are checking against every strategy function and then seeing if it's enabled. This does 2 things:
1. Wastes time for strategies that aren't enabled
2. Only allows strategies to be run in a fixed order
1. is probably negligible, but 2. is something we should consider providing. I don't know if the current order is hardcoded for a reason. There also hasn't been any demand for this specific functionality that I know of, but while we are considering improvements to the API I think a change like this could make it more flexible.
Either way, this does also add an error for invalid strategy names (where it currently just silently skips them)

Invert main strategy loop for performance and customizability

---

pkg/descheduler/descheduler.go

Always use structured logging. Therefore update klog.Errorf() to instead
use klog.ErrorS().
Here is an example of the new log message.
E0428 23:58:57.048912 586 descheduler.go:145] "skipping strategy" err="unknown strategy name" strategy=ASDFPodLifeTime

Use Structured Logging For Unknown Strategy Log Message

---

Makefile
hack/verify-conversions.sh
hack/verify-deep-copies.sh

The error messages were incorrect, and leave out that the changes must be committed

Update error messages in verify scripts to be more informative

---

pkg/descheduler/strategies/topologyspreadconstraint.go
pkg/descheduler/strategies/topologyspreadconstraint_test.go

Fixes https://github.com/kubernetes-sigs/descheduler/issues/564
/kind bug

Add test cases for soft constraints/multi constraints

---

pkg/descheduler/strategies/topologyspreadconstraint.go
pkg/descheduler/strategies/topologyspreadconstraint_test.go

If a pod does not tolerate a node's taints, then it should not be considered for eviction.
Fixes #566

RemovePodsViolatingTopologySpreadConstraint : Take node's taints into consideration when balancing domains

---

Makefile
hack/verify-govet.sh
pkg/descheduler/descheduler_test.go

We can only use `t.Fatal` in the main test goroutine.
The solution is similar to:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-proxy/app/server_test.go#L501
Thanks for review!

Add verify script for govet & fix pkg/descheduler/descheduler_test.go

---

test/run-e2e-tests.sh
test/run-unit-tests.sh

This PR has two commits.
039742501048b4ab4a3a3f342bc6d6dc74385558 - bump kind version
8480e03e9c9d36efd2cc849014bd22031dac8c1a - fail unit and e2e tests on errors

Bump kind version

---

Makefile
charts/descheduler/templates/tests/test-descheduler-pod.yaml
docs/contributor-guide.md
test/run-helm-tests.sh

This PR Fixes: https://github.com/kubernetes-sigs/descheduler/issues/440
As part of this PR, we are enabling support for `helm test` which will be run as part of CI. A new script to run helm tests has been added under `tests/` directory using the kind cluster. Also, Makefile has been updated to add support for `helm test` as a separate check.

Add helm test

---

README.md
pkg/api/types.go
pkg/api/v1alpha1/types.go
pkg/api/v1alpha1/zz_generated.conversion.go
pkg/descheduler/evictions/evictions.go
pkg/descheduler/evictions/evictions_test.go
pkg/descheduler/node/node.go
pkg/descheduler/node/node_test.go
pkg/descheduler/strategies/duplicates.go
pkg/descheduler/strategies/duplicates_test.go
pkg/descheduler/strategies/lownodeutilization.go
pkg/descheduler/strategies/lownodeutilization_test.go
pkg/descheduler/strategies/node_affinity.go
pkg/descheduler/strategies/node_affinity_test.go
pkg/descheduler/strategies/node_taint.go
pkg/descheduler/strategies/node_taint_test.go
pkg/descheduler/strategies/pod_antiaffinity.go
pkg/descheduler/strategies/pod_antiaffinity_test.go
pkg/descheduler/strategies/pod_lifetime_test.go
pkg/descheduler/strategies/toomanyrestarts.go
pkg/descheduler/strategies/toomanyrestarts_test.go
pkg/descheduler/strategies/topologyspreadconstraint.go
pkg/descheduler/strategies/topologyspreadconstraint_test.go

Implements #529.
This feature adds a `nodeFit` boolean parameter to all descheduler strategies. When `nodeFit` is set to `true`, the descheduler strategy will take "node fit" into account when evicting pods. This increases the probability that pods can be re-scheduled to a new node successfully upon eviction.
For the current implementation, "node fit" is defined by the following criteria:
- A `nodeSelector` on the pod
- Any `Tolerations` on the pod and any `Taints` on the other nodes
- `nodeAffinity` on the pod
- Whether any of the other nodes are marked as `unschedulable`

Working nodeFit feature

---

README.md
pkg/descheduler/evictions/evictions.go
pkg/descheduler/strategies/topologyspreadconstraint.go
pkg/descheduler/strategies/topologyspreadconstraint_test.go

**Problem**:
Some of the strategies in Descheduler allow for filtering pods by labelSelector. It would be great for TopologySpreadConstraint to support this filtering mechanism.
**Solution**:
Add suport for `labelSelector` parameter on `RemovePodsViolatingTopologySpreadConstraint` strategy.
Closes #575

Filter pods by labelSelector during eviction for TopologySpreadConstraint strategy

---

kubernetes/base/rbac.yaml

It's not namespace scoped. This breaks some tools like kpt.

Remove namespace from ClusterRoleBinding

---

README.md
kubernetes/deployment/deployment.yaml
kubernetes/deployment/kustomization.yaml

Changes:
- Add kubernetes YAML files to run descheduler as a long running `Deployment` resource
- Update README to include instructions to deploy descheduler using `kubectl apply` and `kustomize build`

Add run descheduler as deployment

---

charts/descheduler/Chart.yaml
charts/descheduler/README.md
charts/descheduler/templates/cronjob.yaml
charts/descheduler/values.yaml
kubernetes/cronjob/cronjob.yaml
test/run-helm-tests.sh

Kubernetes 1.21: CronJob Reaches GA (group version: `batch/v1`).
Ref: https://kubernetes.io/blog/2021/04/09/kubernetes-release-1.21-cronjob-ga/
WARNING: This PR should not be merged until the new Descheduler version is released.
fyi, I tried to compute the api version but it was using 1.20 for my local Kind cluster of version 1.21 so I decided against it.:
```yaml
{{/*
Return the appropriate apiVersion for CronJob.
*/}}
{{- define "cronjob.apiVersion" -}}
{{- if lt (int .Capabilities.KubeVersion.Minor) 21 -}}
{{- print "batch/v1beta1" -}}
{{- else -}}
{{- print "batch/v1" -}}
{{- end -}}
{{- end -}}
```
```yaml
apiVersion: {{ template "cronjob.apiVersion" . }}
kind: CronJob
```

Use stable batch/v1 API Group for Kubernetes 1.21

---

README.md

the current badge reports as `F` because we aren't pointing to the right image

Update Go report card badge

---

Makefile
hack/verify-conversions.sh
hack/verify-defaulters.sh

This PR is related to: https://github.com/kubernetes-sigs/descheduler/issues/483
This PR contains changes for verifying defaulters generator. Currently I'm facing a SIGSEGV error while trying to run verify-defaulters.sh script from local with below logs,
```
-bash>descheduler(verify-defaulters-gen)$
->  ./hack/verify-defaulters.sh
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x12b69a7]
goroutine 1 [running]:
k8s.io/gengo/examples/defaulter-gen/generators.getManualDefaultingFunctions(0xc0080d6540, 0x0, 0xc009de99e0)
/Users/pravaragrawal/Work/go_work/src/github.com/pravarag/descheduler/_tmp/kube-verify.u8W7BZ/descheduler/vendor/k8s.io/gengo/examples/defaulter-gen/generators/defaulter.go:149 +0xa7 …
```

Add verify scripts for defaulters generator

---

Makefile
test/run-e2e-tests.sh
test/run-helm-tests.sh
test/run-unit-tests.sh

2 issues are currently causing the builds to fail:
1. Wrong placement of the bash shebang. This needs to be at the top of the file
2. Helm does not seem to be installed in the build pipeline so modifying the Makefile to ensure always installed

Place bash shebang at the top of the script + Ensure Helm installed for run-helm-tests

---

hack/e2e-gce/gcloud_create_cluster.sh

Address warning:
```
WARNING: Some requests generated warnings:
- The resource 'projects/ubuntu-os-cloud/global/images/ubuntu-1604-xenial-v20180306' is deprecated. A suggested replacement is 'projects/ubuntu-os-cloud/global/images/ubuntu-1604-xenial-v20210429'.
```

Update GCE images to Ubuntu 18.04 LTS

---

pkg/descheduler/strategies/topologyspreadconstraint.go
pkg/descheduler/strategies/topologyspreadconstraint_test.go

When balancing domains, the above average index (i.e. `j`) should advance when equal ideal average.
Closes issue #601

TopologySpreadConstraint: advance above avg index when at ideal average

---

charts/descheduler/README.md
charts/descheduler/templates/_helpers.tpl
charts/descheduler/templates/cronjob.yaml
charts/descheduler/templates/deployment.yaml
charts/descheduler/values.yaml

Builds off of https://github.com/kubernetes-sigs/descheduler/pull/572 to also add the deployment to helm.
`helm template` yields the following with `kind: Deployment`:
```
apiVersion: apps/v1
kind: Deployment
metadata:
name: RELEASE-NAME-descheduler
labels:
app.kubernetes.io/name: descheduler
helm.sh/chart: descheduler-0.20.0
app.kubernetes.io/instance: RELEASE-NAME
app.kubernetes.io/version: "0.20.0"
app.kubernetes.io/managed-by: Tiller
spec:
replicas: 1
selector:
matchLabels:
app.kubernetes.io/name: descheduler
app.kubernetes.io/instance: RELEASE-NAME
template:
metadata:
labels:
app.kubernetes.io/name: descheduler
app.kubernetes.io/instance: RELEASE-NAME
annotations:
checksum/config: 9fe081cdd7d5c040105f0b817cfded705b3a18c3e4258d0afef86ec00f1cf9ee
spec:
priorityClassName: …
```

Update helm chart for running as deployment

---

README.md

docs: adding clarification to HighNodeUtilization's purpose

---

Dockerfile

The main k/k repo was updated to Go 1.16.7 for k8s
v1.22.0 release. See below PR for reference.
https://github.com/kubernetes/kubernetes/pull/104200

Bump To Go 1.16.7

---

pkg/descheduler/strategies/nodeutilization/highnodeutilization.go
pkg/descheduler/strategies/nodeutilization/lownodeutilization.go

The "numberOfNodes" paramter should take effect as documented, when underutilzed nodes count is above the configured value. Currently it takes also effect, when nodes count is equal the configured value.

nodeutilization strategy: "numberOfNodes" should work as documented

---

hack/e2e-gce/gcloud_create_cluster.sh
hack/kind_config.yaml
test/e2e/e2e_test.go
test/e2e/e2e_topologyspreadconstraint_test.go

TC 1:
- Ensure that TopologySpreadConstraint works for hard constraints (i.e. DoNotSchedule)
TC 2:
- Ensure that TopologySpreadConstraint works for soft constraints (i.e. ScheduleAnyways)
Test Layout:
- Create a RC with 4 Pods
- Create a "Violator" RC with 2 Pods (using same label as above) -- use NodeSelector to control scheduling
- Run strategy
- Observe eviction
Alternatives:
- I thought about cordoning one of the nodes to foce all pods to get scheduled onto one of the nodes exclusively but it seemed hacky and would not work out well in the long run if we run tests in parallel (hence "violator" RC).

Add e2e tests for TopologySpreadConstraint

---

README.md
docs/user-guide.md
kubernetes/cronjob/cronjob.yaml
kubernetes/deployment/deployment.yaml
kubernetes/job/job.yaml

* Added v0.22 references to README
* Update k8s manifests with v0.22.0 references
* Added table with list of supported architectures by release

Update Docs and Manifests for v0.22.0

---

charts/descheduler/templates/cronjob.yaml
charts/descheduler/values.yaml

Added support for cronjob suspend

Added support for cronjob suspend

---

pkg/descheduler/strategies/failedpods.go
pkg/descheduler/strategies/failedpods_test.go
pkg/descheduler/strategies/validation/strategyparams.go
test/e2e/e2e_failedpods_test.go
test/e2e/e2e_test.go
test/e2e/e2e_topologyspreadconstraint_test.go

Closes #630 
Background: Descheduler by default loads all strategies and as a result, the strategy params can be nil. The strategy needs to guard against that.

RemoveFailedPods: guard against nil descheduler strategy (e.g. in case of default that loads all strategies)

---

charts/descheduler/README.md

This is a follow up to #622.
/kind documentation
/assign @damemi @ingvagabund

Document suspend helm chart configuration option

---

test/e2e/e2e_duplicatepods_test.go
test/e2e/e2e_test.go
test/e2e/e2e_toomanyrestarts_test.go

Add duplicatepods strategy into E2E test case :)

Add E2E test case cover duplicatepods strategy

---

README.md
pkg/descheduler/evictions/evictions.go
pkg/descheduler/strategies/failedpods_test.go
pkg/descheduler/strategies/node_affinity_test.go
pkg/descheduler/strategies/pod_antiaffinity_test.go
pkg/descheduler/strategies/pod_lifetime_test.go
pkg/descheduler/strategies/topologyspreadconstraint.go
pkg/utils/pod.go

Enhance ignore Pods With Deletion Timestamp for all strategies  
Issue: https://github.com/kubernetes-sigs/descheduler/issues/638

Ignore Pods With Deletion Timestamp

---

README.md
examples/failed-pods.yaml

Signed-off-by: Abhilash Pallerlamudi <stp.abhi@gmail.com>
This PR fixes typo in examples and README files. [xref](https://github.com/kubernetes-sigs/descheduler/blob/master/pkg/api/v1alpha1/types.go#L110)

fix typo minPodLifeTimeSeconds

---

pkg/descheduler/descheduler.go
pkg/descheduler/descheduler_test.go
pkg/descheduler/pod/pods.go
pkg/descheduler/pod/pods_test.go
pkg/descheduler/strategies/duplicates.go
pkg/descheduler/strategies/duplicates_test.go
pkg/descheduler/strategies/failedpods.go
pkg/descheduler/strategies/failedpods_test.go
pkg/descheduler/strategies/node_affinity.go
pkg/descheduler/strategies/node_affinity_test.go
pkg/descheduler/strategies/node_taint.go
pkg/descheduler/strategies/node_taint_test.go
pkg/descheduler/strategies/nodeutilization/highnodeutilization.go
pkg/descheduler/strategies/nodeutilization/highnodeutilization_test.go
pkg/descheduler/strategies/nodeutilization/lownodeutilization.go
pkg/descheduler/strategies/nodeutilization/lownodeutilization_test.go
pkg/descheduler/strategies/nodeutilization/nodeutilization.go
pkg/descheduler/strategies/pod_antiaffinity.go
pkg/descheduler/strategies/pod_antiaffinity_test.go
pkg/descheduler/strategies/pod_lifetime.go
pkg/descheduler/strategies/pod_lifetime_test.go
pkg/descheduler/strategies/toomanyrestarts.go
pkg/descheduler/strategies/toomanyrestarts_test.go
pkg/descheduler/strategies/topologyspreadconstraint.go
pkg/descheduler/strategies/topologyspreadconstraint_test.go
test/e2e/e2e_duplicatepods_test.go
test/e2e/e2e_failedpods_test.go
test/e2e/e2e_test.go
test/e2e/e2e_toomanyrestarts_test.go
test/e2e/e2e_topologyspreadconstraint_test.go

**What this PR does / why we need it**:
Now there is a perf problem about the way we list pods that assigned to a node. When the cluster is large scale, like 3k+ nodes and 90k+ pods. The descheduler is not able to work because every interval it will request kube-apiserver for almost 30k+ times(enable 10 plugins and every plugins request for 3k+ times) with a FieldSelector. Meanwhile, it leads to a lot of pressure for kube-apiserver. So I try to make a revision by using pod informer cache.
**Which issue(s) this PR fixes**:
Fixes #671
**Special notes for your reviewer**:
I'm afraid the PR is too large to review (beacause listing pods is a really basic action and the function is called everywhere in strategy files and test files). So I separate this PR into 3 commits in order to make code …

list pods assigned to a node by pod informer cache

---

Makefile

install golangci using the install.sh script from the golangci repo
Ref: https://golangci-lint.run/usage/install/#other-ci
```
❯ make lint
curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b ./_output/bin v1.30.0
golangci/golangci-lint info checking GitHub for tag 'v1.30.0'
golangci/golangci-lint info found version: 1.30.0 for v1.30.0/darwin/amd64
golangci/golangci-lint info installed ./_output/bin/golangci-lint
golangci/golangci-lint err this script is deprecated, please do not use it anymore. check https://github.com/goreleaser/godownloader/issues/207
./_output/bin/golangci-lint run
```

fix: install golangci using from the golangci repo

---

cmd/descheduler/descheduler.go

Also, one needs to set --logtostderr=false to properly log into the stdout.
Fixes: https://github.com/kubernetes-sigs/descheduler/issues/676
Testing locally while redirecting the stdout:
```
$ ./_output/bin/descheduler --kubeconfig ~/.kube/config --policy-config-file examples/policy.yaml --v=1 --descheduling-interval 10s --logtostderr=false 2>/dev/null
Flag --logtostderr has been deprecated, will be removed in a future release, see https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/2845-deprecate-klog-specific-flags-in-k8s-components
I1216 11:24:15.663767 2350329 secure_serving.go:200] Serving securely on [::]:10258
I1216 11:24:15.663856 2350329 tlsconfig.go:240] "Starting DynamicServingCertificateController"
I1216 11:24:17.294796 2350329 …
```

Set the klog output to stdout by default

---

pkg/descheduler/strategies/failedpods.go
pkg/descheduler/strategies/failedpods_test.go

Hello,
I noticed that `RemoveFailedPods` strategy is actually not checking reason in pod status.
This causes that pods in the state like in the example below are ignored by the policy.
```yaml
status:
message: Node is shutting, evicting pods
phase: Failed
reason: Shutdown
```
This MR updates the reasons so descheduler can evict Shutdown pods.
Example of the policy:
```yaml
strategies:
"RemoveFailedPods":
enabled: true
params:
failedPods:
excludeOwnerKinds:
- Job
includingInitContainers: true
reasons:
- Shutdown
```

Add pod.Status.Reason to the list of reasons

---

metrics/metrics.go

Updated comment to reflect actual value, i think this was supposed to be error based on this [line](https://github.com/kubernetes-sigs/descheduler/blob/master/pkg/descheduler/evictions/evictions.go#L134)

Comment update for metrics

---

test/e2e/e2e_test.go

This PR fixes a bug in the E2E tests involving a race condition that can occur in some `Kind` clusters.
This bug occurs because the first E2E test (currently `TestRemoveDuplicates`) lists the nodes. Since the E2E automation builds a `Kind` cluster and then immediately executes the tests, the nodes may or may not be ready at the time the first test lists them. This can cause unpredictable behavior, because if one or more nodes are not ready when the test lists them, the nodes the test case sees will be tainted with `node.kubernetes.io/not-ready`. This ultimately results in the Deschedulder avoiding evictions because it only has knowledge of tainted nodes, which causes the test case to fail.
To fix this, I've added a `waitForNodesReady()` function which is called by the `initializeClient()` …

Eliminated race condition in E2E tests

---

pkg/descheduler/descheduler.go

Use [NonSlidingUntil](https://pkg.go.dev/k8s.io/apimachinery/pkg/util/wait#NonSlidingUntil) over Until in order to account for function duration.  
Trying to make the run times on more of an interval in order to make executions times more predictable. 
Using NonSlidingWindow will make the deployment behave more like the cronjob timing wise.

NonSlidingUntil for deployment

---

charts/descheduler/templates/cronjob.yaml
charts/descheduler/templates/deployment.yaml
charts/descheduler/values.yaml
kubernetes/deployment/deployment.yaml
kubernetes/job/job.yaml

Addresses 2 inconsistencies from #685 :
+ `livenessProbe.periodSeconds` was not consistent across manifests (`10` in one, `3` in others)
+ `charts/descheduler/templates/cronjob.yaml` was missing livenessProbe but `kubernetes/cronjob/cronjob.yaml` had it
Also:
+ Makes it possible to override via `values.yaml` for Helm

make livenessprobe consistent across manifests

---

pkg/descheduler/descheduler.go
pkg/descheduler/evictions/evictions.go
pkg/descheduler/evictions/evictions_test.go
pkg/descheduler/strategies/duplicates_test.go
pkg/descheduler/strategies/failedpods_test.go
pkg/descheduler/strategies/node_affinity_test.go
pkg/descheduler/strategies/node_taint_test.go
pkg/descheduler/strategies/nodeutilization/highnodeutilization_test.go
pkg/descheduler/strategies/nodeutilization/lownodeutilization_test.go
pkg/descheduler/strategies/pod_antiaffinity_test.go
pkg/descheduler/strategies/pod_lifetime_test.go
pkg/descheduler/strategies/toomanyrestarts_test.go
pkg/descheduler/strategies/topologyspreadconstraint_test.go
test/e2e/e2e_duplicatepods_test.go
test/e2e/e2e_test.go
test/e2e/e2e_toomanyrestarts_test.go

Currently, when the descheduler is running with the --dry-run on, no strategy actually evicts a pod so every strategy always starts with a complete list of pods. E.g. when the PodLifeTime strategy evicts few pods, the RemoveDuplicatePods strategy still takes into account even the pods eliminated by the PodLifeTime strategy. Which does not correspond to the real case scenarios as the same pod can be evicted multiple times. Instead, use a fake client and evict/delete the pods from its cache so the strategies evict each pod at most once as it would be normally done in a real cluster.

Use a fake client when evicting pods by individual strategies to accumulate the evictions

---

charts/descheduler/templates/serviceaccount.yaml
charts/descheduler/values.yaml

It would be useful to have annotations on the service account as it's required to use things such as WLI in Google Cloud (https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity)

Updates to include annotations to the service account

---

charts/descheduler/templates/cronjob.yaml
charts/descheduler/templates/deployment.yaml
charts/descheduler/values.yaml

I want to add 'affinity' support in order to fine tune where 'descheduler' should run.
My current use case: I want to prefer "spot" instances over "ondemand" instances

Adding 'affinity' support to run 'descheduler' in CronJob or Deployment

---

charts/descheduler/templates/clusterrole.yaml
kubernetes/base/rbac.yaml

fix bug #711 
before code we don't have namespaceInformer, so we not need to watch permission for namespace. but now we need it, so add watch permission for namespace

fix helmchart fail to watch namespace issue

---

charts/descheduler/Chart.yaml
docs/user-guide.md
kubernetes/cronjob/cronjob.yaml
kubernetes/deployment/deployment.yaml
kubernetes/job/job.yaml

bump helm chart version to v0.23.1

[release-1.23.1] Update helm chart version to v0.23.1

---

OWNERS

Per @ingvagabund adding myself as a code reviewer

OWNERS: add a7i as a reviewer

---

charts/descheduler/templates/deployment.yaml
charts/descheduler/values.yaml

Signed-off-by: emin.aktas <eminaktas34@gmail.com>
Co-authored-by: yasintahaerol <yasintahaerol@gmail.com>
Co-authored-by: Dentrax <furkan.turkal@trendyol.com>

fix: add imagePullSecrets for deployment resource

---

pkg/descheduler/evictions/evictions.go

Currently it's hard to tell where the pod is being evicted from in the `RemovePodsViolatingTopologySpreadConstraint` strategy. This should make it easier to debug for any strategy.

Eviction Logs

---

README.md

Adding these as it is a frequent source of confusion for users as to why Descheduler is showing different consumption values than kubelet

Clarify resource calculations in NodeUtilization strategy Readmes

---

cmd/descheduler/app/server.go
pkg/descheduler/descheduler.go
pkg/descheduler/descheduler_test.go
test/e2e/e2e_test.go

Removed the stop channel and just use ctx.
Fixes https://github.com/kubernetes-sigs/descheduler/issues/728

Bugfix: Cronjob ctx cancel

---

README.md
docs/user-guide.md

remove MostRequestedPriority from doc since already deprecated

---

Dockerfile
charts/descheduler/Chart.yaml
cmd/descheduler/app/server.go
pkg/descheduler/descheduler.go
pkg/descheduler/descheduler_test.go
test/e2e/e2e_test.go

Backports https://github.com/kubernetes-sigs/descheduler/pull/731 and preps for a v0.23.1 app release to address this
Fixes https://github.com/kubernetes-sigs/descheduler/issues/743
ref #741 #728

[release-1.23] Backport context cancel panic + Go version update

---

README.md
charts/descheduler/values.yaml

In #658, maxNoOfPodsToEvictPerNamespace policy was added, but it is not documented. This PR adds it.

Update docs for maxNoOfPodsToEvictPerNamespace

---

test/e2e/e2e_toomanyrestarts_test.go

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_descheduler/758/pull-descheduler-test-e2e-k8s-master-1-23/1501991622580113408:
```
=== RUN   TestTooManyRestarts
e2e_toomanyrestarts_test.go:50: Creating testing namespace TestTooManyRestarts
e2e_toomanyrestarts_test.go:86: Creating deployment restart-pod
--- FAIL: TestTooManyRestarts (5.16s)
panic: runtime error: index out of range [0] with length 0 [recovered]
panic: runtime error: index out of range [0] with length 0
goroutine 1040 [running]:
testing.tRunner.func1.2({0x1c01380, 0xc00080c588})
/usr/local/go/src/testing/testing.go:1209 +0x24e
testing.tRunner.func1()
/usr/local/go/src/testing/testing.go:1212 +0x218
panic({0x1c01380, 0xc00080c588})
/usr/local/go/src/runtime/panic.go:1038 +0x215 …
```

[e2e] TestTooManyRestarts: check err and len before accessing pod items

---

test/e2e/e2e_toomanyrestarts_test.go

From https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_descheduler/759/pull-descheduler-test-e2e-k8s-master-1-23/1502212010236973056:
```
=== RUN   TestTooManyRestarts
e2e_toomanyrestarts_test.go:50: Creating testing namespace TestTooManyRestarts
e2e_toomanyrestarts_test.go:86: Creating deployment restart-pod
--- FAIL: TestTooManyRestarts (5.14s)
panic: runtime error: index out of range [0] with length 0 [recovered]
panic: runtime error: index out of range [0] with length 0
goroutine 1222 [running]:
testing.tRunner.func1.2({0x1c01380, 0xc00140ac78})
/usr/local/go/src/testing/testing.go:1209 +0x24e
testing.tRunner.func1()
/usr/local/go/src/testing/testing.go:1212 +0x218
panic({0x1c01380, 0xc00140ac78})
/usr/local/go/src/runtime/panic.go:1038 +0x215 …
```

[e2e] TestTooManyRestarts: check if container status is set before accessing

---

pkg/descheduler/strategies/nodeutilization/highnodeutilization.go
pkg/descheduler/strategies/nodeutilization/lownodeutilization.go
pkg/descheduler/strategies/nodeutilization/nodeutilization.go

Refactoring the code so it is easier to replace the code computing the lower/higher thresholds. Also, the `getNodeUsage` is currently evaluating the thresholds which is out of what a usage means. With this PR a developer can wrap the threshold computation around the new `NodeThresholds` data type and implement a different mechanism of pre-computing them.
To help ease integration with https://github.com/kubernetes-sigs/descheduler/pull/751

Promote NodeUsage to NodeInfo, evaluate thresholds separately

---

README.md
pkg/api/types.go
pkg/api/v1alpha1/types.go
pkg/api/v1alpha1/zz_generated.conversion.go
pkg/api/v1alpha1/zz_generated.deepcopy.go
pkg/api/zz_generated.deepcopy.go
pkg/descheduler/strategies/node_taint.go
pkg/descheduler/strategies/node_taint_test.go

Add taint exclusion to RemovePodsViolatingNodeTaints. This permits node
taints to be ignored by allowing users to specify ignored taint keys or
ignored taint key=value pairs.
Fixes #772

Add RemovePodsViolatingNodeTaints taint exclusion

---

README.md
pkg/api/types.go
pkg/api/v1alpha1/types.go
pkg/api/v1alpha1/zz_generated.conversion.go
pkg/descheduler/strategies/nodeutilization/highnodeutilization.go
pkg/descheduler/strategies/nodeutilization/lownodeutilization.go
pkg/descheduler/strategies/nodeutilization/lownodeutilization_test.go
pkg/descheduler/strategies/nodeutilization/nodeutilization.go

This is duplicate of #473 
Because the last PR was done over a year ago, the code-base has changed a lot, it was easier to do a new PR.
Thanks to @AmoVanB, 
https://github.com/kubernetes-sigs/descheduler/pull/473#issue-769030153

feat: Add DeviationThreshold Paramter for LowNodeUtilization, (Previous attempt - #473 )

---

pkg/descheduler/strategies/nodeutilization/highnodeutilization.go
pkg/descheduler/strategies/nodeutilization/lownodeutilization.go
pkg/descheduler/strategies/nodeutilization/nodeutilization.go
pkg/descheduler/strategies/nodeutilization/nodeutilization_test.go

Sort nodes in ascending order for HighNodeUtilization. 
This fixes the issue reported in https://github.com/kubernetes-sigs/descheduler/issues/756 and a part of issue in https://github.com/kubernetes-sigs/descheduler/issues/725

Sort nodes in ascending order for HighNodeUtilization

---

docs/user-guide.md

A small pr to fix missing parameter field in the following document: https://github.com/kubernetes-sigs/descheduler/blob/master/docs/user-guide.md#balance-cluster-by-pod-age
Related issue:  https://github.com/kubernetes-sigs/descheduler/issues/780

Fix missing param in user-guide for PodLifeTime strategy

---

README.md
docs/user-guide.md
kubernetes/cronjob/cronjob.yaml
kubernetes/deployment/deployment.yaml
kubernetes/job/job.yaml

Changes covered as part of this PR are:

Update Docs and Manifests for v0.24.0

---

go.mod
go.sum
vendor/golang.org/x/crypto/cryptobyte/builder.go
vendor/golang.org/x/crypto/internal/poly1305/sum_generic.go
vendor/golang.org/x/crypto/internal/poly1305/sum_s390x.go
vendor/modules.txt

Addresses a [CVE-2022-27191](https://access.redhat.com/security/cve/CVE-2022-27191), see upstream https://github.com/kubernetes/kubernetes/pull/109552

bump: golang.org/x/crypto

---

go.mod
go.sum
vendor/golang.org/x/crypto/cryptobyte/builder.go
vendor/golang.org/x/crypto/internal/poly1305/sum_generic.go
vendor/golang.org/x/crypto/internal/poly1305/sum_s390x.go
vendor/modules.txt

Addresses a [CVE-2022-27191](https://access.redhat.com/security/cve/CVE-2022-27191), see upstream https://github.com/kubernetes/kubernetes/pull/109552
(we may want to backport this further too)

[release-1.24] bump: golang.org/x/crypto

---

charts/descheduler/templates/_helpers.tpl
charts/descheduler/templates/clusterrole.yaml
charts/descheduler/values.yaml

Also, add the missing update verb in the ClusterRole and adds required time units to `leaseDuration`, `renewDeadline`, and `retryPeriod` in the Chart example.
Closes #812

Arguments must be strings, not bool or number

---

charts/descheduler/README.md
charts/descheduler/templates/_helpers.tpl
charts/descheduler/templates/clusterrole.yaml
charts/descheduler/values.yaml

This cherry-picks the changes from https://github.com/kubernetes-sigs/descheduler/pull/814 and https://github.com/kubernetes-sigs/descheduler/pull/813 to fix helm chart changes that should have been included in 1.24

[release-1.24] helm chart fixes

---

README.md
charts/descheduler/Chart.yaml
docs/user-guide.md
kubernetes/cronjob/cronjob.yaml
kubernetes/deployment/deployment.yaml
kubernetes/job/job.yaml

This prepares the v0.24.1 release
(this branch already tagged with `v0.24.1`, so after this merges we should be able to do the image promotion)

[release-1.24] Update helm chart for v0.24.1

---

Makefile
cloudbuild.yaml
pkg/version/version.go

Porting https://github.com/kubernetes-sigs/descheduler/pull/823 to 1.24

[release-1.24] Fix version command to parse helm chart tags

---

pkg/descheduler/strategies/nodeutilization/lownodeutilization.go

Reverts kubernetes-sigs/descheduler#805

Revert "cleanup lownodeutilization code"

---

go.mod
pkg/descheduler/pod/pods.go
pkg/descheduler/pod/pods_test.go
pkg/descheduler/strategies/pod_lifetime.go
pkg/descheduler/strategies/pod_lifetime_test.go
test/e2e/e2e_duplicatepods_test.go
test/e2e/e2e_failedpods_test.go
test/e2e/e2e_leaderelection_test.go
test/e2e/e2e_test.go
test/e2e/e2e_toomanyrestarts_test.go

Closes #816 
In the event that PDB or settings such maxNoOfPodsToEvictPer* prevent too much eviction, we need to make sure that oldest pod is evicted first.

PodLifeTime: sort pods by creation timestamp

---

README.md
charts/descheduler/Chart.yaml
docs/user-guide.md
kubernetes/cronjob/cronjob.yaml
kubernetes/deployment/deployment.yaml
kubernetes/job/job.yaml

https://github.com/kubernetes-sigs/descheduler/pull/820 was never applied to master branch

Update docs, manifests for 0.24.1 on master

---

pkg/descheduler/strategies/topologyspreadconstraint.go
pkg/descheduler/strategies/topologyspreadconstraint_test.go

We need to check v1.TopologySpreadConstraint deepEquality because two v1.TopologySpreadConstraints are not the same (even with same content) since they have one field that is a pointer (LabelSelector). So when we do the namespaceTopologySpreadConstraints[constraint] = struct{}{} we are creating a new key every time. Now that we check their deep equality, v1.TopologySpreadConstraints with same content will be inserted as the same key in the assignment.
(recreated it, again)

Check existing constraints before assigning

---

pkg/descheduler/descheduler.go
pkg/descheduler/evictions/evictions.go
pkg/descheduler/evictions/evictions_test.go
pkg/descheduler/strategies/duplicates.go
pkg/descheduler/strategies/duplicates_test.go
pkg/descheduler/strategies/failedpods.go
pkg/descheduler/strategies/failedpods_test.go
pkg/descheduler/strategies/node_affinity.go
pkg/descheduler/strategies/node_affinity_test.go
pkg/descheduler/strategies/node_taint.go
pkg/descheduler/strategies/node_taint_test.go
pkg/descheduler/strategies/nodeutilization/highnodeutilization.go
pkg/descheduler/strategies/nodeutilization/highnodeutilization_test.go
pkg/descheduler/strategies/nodeutilization/lownodeutilization.go
pkg/descheduler/strategies/nodeutilization/lownodeutilization_test.go
pkg/descheduler/strategies/pod_antiaffinity.go
pkg/descheduler/strategies/pod_antiaffinity_test.go
pkg/descheduler/strategies/pod_lifetime.go
pkg/descheduler/strategies/pod_lifetime_test.go
pkg/descheduler/strategies/toomanyrestarts.go
pkg/descheduler/strategies/toomanyrestarts_test.go
pkg/descheduler/strategies/topologyspreadconstraint.go
pkg/descheduler/strategies/topologyspreadconstraint_test.go
test/e2e/e2e_duplicatepods_test.go
test/e2e/e2e_failedpods_test.go
test/e2e/e2e_test.go
test/e2e/e2e_toomanyrestarts_test.go
test/e2e/e2e_topologyspreadconstraint_test.go

The evictor filter is planned to be moved under a plugin. In order to initialize the evictor filter outside of the strategies, the `PodEvictor` is split into a pod evictor (responsible for actually evicting pods) and an evictor filter (responsible for deciding whether a pod can be evicted).
Pre-requisite for https://github.com/kubernetes-sigs/descheduler/issues/837

Split pod evictor and evictor filter

---

.github/ci/ct.yaml
.github/workflows/helm.yaml
.gitignore
Makefile
docs/contributor-guide.md

Main thing here is to have a way to see if changes to charts are at least valid in the PR. 
I see ./test/run-helm-tests.sh, but I am not sure how this is being called. In the docs it says that this is being used by the CI, but  I don't see it. Can we remove it?

Improving helm setup

---

pkg/descheduler/strategies/topologyspreadconstraint.go
pkg/descheduler/strategies/topologyspreadconstraint_test.go

Closes #835 #839
TopologySpreadConstraint should only evaluate nodes below ideal avg when balancing domains to prevent eviction loop when nodes aboveAvg are taken into account.

TopologySpreadConstraint: only evaluate nodes below ideal avg when balancing domains

---

charts/descheduler/templates/clusterrole.yaml

This PR makes the lease name of Helm value and the ClusterRole's lease resource name consistent.

Use lease resource name from Helm value

---

pkg/descheduler/descheduler.go
pkg/descheduler/evictions/evictions.go
pkg/descheduler/strategies/duplicates.go
pkg/descheduler/strategies/failedpods.go
pkg/descheduler/strategies/node_affinity.go
pkg/descheduler/strategies/node_taint.go
pkg/descheduler/strategies/nodeutilization/nodeutilization.go
pkg/descheduler/strategies/pod_antiaffinity.go
pkg/descheduler/strategies/pod_lifetime.go
pkg/descheduler/strategies/toomanyrestarts.go
pkg/descheduler/strategies/topologyspreadconstraint.go

- Pass the strategy name into evictor through context to reduce the list of parameters to miminum
- Drop node parameter as it can be retrieved from the pod object
- EvictPod: stop returning error and have higher processes decide when is the right time to exit a strategy loop
Pre-requisite for https://github.com/kubernetes-sigs/descheduler/issues/837

Prepare pod evictor for the descheduling framework plugin

---

charts/descheduler/templates/clusterrole.yaml

Ref. #876 #881
This PR adds the default value for the lease resource name in Helm chart's ClusterRole.

Add default lease resource name in Helm chart's ClusterRole

---

pkg/descheduler/descheduler.go
pkg/descheduler/evictions/evictions.go
pkg/descheduler/strategies/duplicates.go
pkg/descheduler/strategies/failedpods.go
pkg/descheduler/strategies/node_affinity.go
pkg/descheduler/strategies/node_taint.go
pkg/descheduler/strategies/nodeutilization/nodeutilization.go
pkg/descheduler/strategies/pod_antiaffinity.go
pkg/descheduler/strategies/pod_lifetime.go
pkg/descheduler/strategies/toomanyrestarts.go
pkg/descheduler/strategies/topologyspreadconstraint.go

Following up from https://github.com/kubernetes-sigs/descheduler/pull/846#discussion_r917295575, this proposes adding an `EvictOptions` struct, which can be used to optionally pass additional information to `EvictPod()`.
Since `EvictPod()` is the public wrapper around the internal `evictPod` function which actually does the eviction, I think it makes sense to do logging/metrics in this function. An options struct allows us to give users the option to pass this info in a structured format, while abstracting that format enough to maintain a consistent function signature. So, this could be expanded in the future to allow more customization around `EvictPod` as well.

Add EvictOptions struct to EvictPod()

---

cmd/descheduler/app/options/options.go
kubernetes/base/rbac.yaml
pkg/descheduler/client/client.go
pkg/descheduler/descheduler.go
pkg/descheduler/descheduler_test.go
pkg/descheduler/evictions/evictions.go
pkg/descheduler/strategies/duplicates_test.go
pkg/descheduler/strategies/failedpods_test.go
pkg/descheduler/strategies/node_affinity_test.go
pkg/descheduler/strategies/nodeutilization/highnodeutilization_test.go
pkg/descheduler/strategies/nodeutilization/lownodeutilization_test.go
pkg/descheduler/strategies/pod_antiaffinity_test.go
pkg/descheduler/strategies/pod_lifetime_test.go
pkg/descheduler/strategies/toomanyrestarts_test.go
pkg/descheduler/strategies/topologyspreadconstraint_test.go
pkg/framework/plugins/removepodsviolatingnodetaints/node_taint_test.go
pkg/utils/events.go
test/e2e/e2e_duplicatepods_test.go
test/e2e/e2e_test.go
test/e2e/e2e_toomanyrestarts_test.go

Fixes #884 
I was trying something around #887 but that did not do it. There I just mistakenly removed `StartRecordingToSink` which when reintroduced would cause the leak again. So you can just ignore that. (just mentioning to document attempts)
Shutting down eventBroadcaster seems to do the trick. If we look back to the [pprof top report for in use objects](https://github.com/kubernetes-sigs/descheduler/issues/884#issuecomment-1180547263) we see that we have something getting accumulated in k8s.io/apimachinery/pkg/watch.(*Broadcaster).Watch. I am guessing every time we call StartRecordingToSink that is when we start accumulating it.
Shutting down the eventBroadcaster right after we publish the event seems to stop this accumulation and it also seems to not affect the publication of the …

fix: events memory leak. Using new events implementation and take recorder out of EvictPod

---

.github/ci/ct.yaml
.github/workflows/helm.yaml
Makefile
docs/contributor-guide.md
test/run-e2e-tests.sh

First step, see https://github.com/kubernetes-sigs/descheduler/pull/895#issuecomment-1203608848
Ater this PR is merged we can check it prow considers gh-actions when deciding to merge. After that we can go forward with the other changes from https://github.com/kubernetes-sigs/descheduler/pull/895

add helm ct install. 

---

pkg/apis/componentconfig/types_pluginargs.go
pkg/apis/componentconfig/validation/validation_pluginargs.go
pkg/apis/componentconfig/validation/validation_pluginargs_test.go
pkg/framework/plugins/removefailedpods/failedpods.go

tiny PR to re-use the existing validation funcs

NodeAffinity plugin to use the existing validation methods

---

.github/workflows/security.yaml

part of https://github.com/kubernetes-sigs/descheduler/issues/897
summarize here:
This workflow scans:
Every push to the main and master branch
The default branch every day at 0:30 UTC
security result can be see:
For scheduler result is on GitHub Security tab.

add security scan into gh-actions

---

pkg/descheduler/node/node.go

SSIA
Fixes: https://github.com/kubernetes-sigs/descheduler/issues/873

NodeFit: do not check whether node fitsRequest when a pod is already assigned to the node

---

README.md

Signed-off-by: Amir Alavi <amiralavi7@gmail.com>
Add a ~footnote~ column to indicate which version `states` will be supported and `podStatusPhases` was deprecated in.
Feedback: https://github.com/kubernetes-sigs/descheduler/pull/834#discussion_r956608971

clarify which version PodLifeTime introduced states parameter and deprecated podStatusPhases

---

charts/descheduler/values.yaml

This does the following:
1. Enables RemovePodsHavingTooManyRestarts when using Helm by default (it is not currently)
2. Adds RemovePodsHavingTooManyRestarts to the values.yaml for clearer configs

feat: add RemovePodsHavingTooManyRestarts to values.yaml

---

README.md
docs/user-guide.md
kubernetes/cronjob/cronjob.yaml
kubernetes/deployment/deployment.yaml
kubernetes/job/job.yaml

Changes covered as part of this PR are:
-  Added v0.24 references to README
-  Update k8s manifests with v0.24.0 references
-  Added table with list of supported architectures by release
https://github.com/kubernetes-sigs/descheduler/issues/844

Update docs & manifests for v0.25.0

---

charts/descheduler/values.yaml
kubernetes/cronjob/cronjob.yaml

- Descheduler promises 3 version skew
- The batch/v1beta1 API version of CronJob will no longer be served in v1.25.

remove TODO comments for cronjob v1beta1 support

---

metrics/metrics.go

This commit changes build_info metric labels
- AppVersion label will show major+minor version for example 0.24.1
It will be seen like this
```bash
descheduler_build_info{AppVersion="0.24.1",GitBranch="metric-label-fix",GitSha1="0317be1b7672c511f5e2e53acaea1dd5cb74fd77",DeschedulerVersion="v20220909-v0.24.1-188-g0317be1b7",GoVersion="go1.19"} 0
```
Signed-off-by: eminaktas <eminaktas34@gmail.com>

feat: change DeschedulerVersion and GitVersion labels

---

docs/contributor-guide.md

Change `make lint-helm` to `make lint-chart`.

Fix wrong command on contributor-guide.md

---

pkg/descheduler/descheduler.go
pkg/framework/fake/fake.go
pkg/framework/plugins/defaultevictor/defaultevictor.go
pkg/framework/plugins/defaultevictor/defaultevictor_test.go
pkg/framework/plugins/nodeutilization/nodeutilization.go
pkg/framework/plugins/podlifetime/pod_lifetime.go
pkg/framework/plugins/removeduplicates/removeduplicates.go
pkg/framework/plugins/removefailedpods/failedpods.go
pkg/framework/plugins/removepodshavingtoomanyrestarts/toomanyrestarts.go
pkg/framework/plugins/removepodsviolatinginterpodantiaffinity/pod_antiaffinity.go
pkg/framework/plugins/removepodsviolatingnodeaffinity/node_affinity.go
pkg/framework/plugins/removepodsviolatingnodetaints/node_taint.go
pkg/framework/plugins/removepodsviolatingtopologyspreadconstraint/topologyspreadconstraint.go
pkg/framework/types.go

As per https://github.com/kubernetes-sigs/descheduler/issues/640#issuecomment-1248167067 I am just moving nodefit check to the preEvictionFilter extension point of the DefaultEvictor plugin. Follow ups would include those other options of that issue (and namespace selectors, etc).
Let me know if the evocation of the extension point shouldn't be done in the way that I did.
Also related to https://github.com/kubernetes-sigs/descheduler/issues/924, https://github.com/kubernetes-sigs/descheduler/issues/753#issuecomment-1227422028,

add PreEvictionFilter extension to DefaultEvictor Plugin

---

pkg/descheduler/evictions/evictions.go

Include pod node name into 'Descheduled' events.

feat: show nodename in evicted events

---

pkg/descheduler/descheduler.go
pkg/descheduler/node/node.go
pkg/descheduler/node/node_test.go
pkg/descheduler/pod/pods.go
pkg/descheduler/pod/pods_test.go
pkg/framework/plugins/defaultevictor/defaultevictor.go
pkg/framework/plugins/defaultevictor/defaultevictor_test.go
pkg/framework/plugins/nodeutilization/highnodeutilization_test.go
pkg/framework/plugins/nodeutilization/lownodeutilization_test.go
pkg/framework/plugins/podlifetime/pod_lifetime_test.go
pkg/framework/plugins/removeduplicates/removeduplicates_test.go
pkg/framework/plugins/removefailedpods/failedpods_test.go
pkg/framework/plugins/removepodshavingtoomanyrestarts/toomanyrestarts_test.go
pkg/framework/plugins/removepodsviolatinginterpodantiaffinity/pod_antiaffinity_test.go
pkg/framework/plugins/removepodsviolatingnodeaffinity/node_affinity_test.go
pkg/framework/plugins/removepodsviolatingnodetaints/node_taint_test.go
pkg/framework/plugins/removepodsviolatingtopologyspreadconstraint/topologyspreadconstraint_test.go
test/e2e/e2e_test.go

sharedInformerFactory should register resource before call `sharedInformerFactory.Start()`
I get logs `Node lister returned empty list, now fetch directly`

fix sharedInformerFactory register

---

pkg/descheduler/strategy_migration.go

Backporting https://github.com/kubernetes-sigs/descheduler/pull/961 into release-1.25

backport 7349b39 (issue 960) into release-1.25

---

README.md
docs/user-guide.md
kubernetes/cronjob/cronjob.yaml
kubernetes/deployment/deployment.yaml
kubernetes/job/job.yaml

Following [release guide](https://github.com/kubernetes-sigs/descheduler/blob/master/docs/release-guide.md#flowchart), we'll merge these changes, tag `v0.25.1` on the `release-1.25` branch, then merge the Helm chart update to v0.25.1 and publish the release.
This commit (and the helm update) should also be brought to master just to keep that in sync with the latest docs

[release-1.25] Doc updates for v0.25.1

---

.github/ci/ct.yaml
.github/workflows/helm.yaml

Based on the docs, it seems that `helm-extra-set-args` is only available as [an inline arg](https://github.com/helm/chart-testing/blob/main/doc/ct_install.md#options) but not as a [config](https://github.com/helm/chart-testing/blob/main/pkg/config/config.go#L44).
Closes #949

set helm-extra-set-args as inline command arg

---

README.md

While exploring the repo, found out the link to kustomize is broken and perhaps it was referencing to "kustomize build" page since it is where descheduler installation instructions are about that makes use of it. 
Additional note: it might be beneficial to automate broken link checking in the repo by adding GA for markdown link checks. One example could be: https://github.com/gaurav-nelson/github-action-markdown-link-check

📖 Fix broken kustomize reference in the root README

---

README.md

README: be more explicit about scope of the descheduler.alpha.kubernetes.io/evict annotation

---

charts/descheduler/Chart.yaml
charts/descheduler/templates/clusterrole.yaml

This will publish a new helm chart when it merges
Fixes https://github.com/kubernetes-sigs/descheduler/issues/986
Fixes #959

[release-1.25] Update helm chart rolebinding to use events.k8s.io

---

test/e2e/e2e_duplicatepods_test.go
test/e2e/e2e_leaderelection_test.go
test/e2e/e2e_test.go
test/e2e/e2e_toomanyrestarts_test.go

While running e2e tests on k8s v1.24+, the test logs are filled with privileged security context warning messages. Also some of the tests are failing because pods can't be started with privileged security context. This PR will add restricted context to the e2e pods.

add restricted security policy to e2e test pods

---

hack/verify-conversions.sh
hack/verify-deep-copies.sh
hack/verify-defaulters.sh

In https://github.com/kubernetes-sigs/descheduler/pull/958 we are noticing odd behavior with the `verify` tools for our generator scripts, specifically conversions. CI is [failing to verify the conversion-gen](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_descheduler/958/pull-descheduler-verify-master/1580431724137943040) saying there are changes missing. But, running these generators on some local environments (and containers) produces no diff, while other environments do produce the generated output that the tests are expecting.
https://github.com/kubernetes-sigs/descheduler/pull/954/commits/96c03a3f97b6440c1622a9e09606785fdbb4de87 and https://github.com/kubernetes-sigs/descheduler/pull/954/commits/2b1746cda8883c199329510ac021b1c6badf4984 update the …

Update verify scripts to use the generation scripts directly

---

charts/descheduler/templates/clusterrole.yaml

Patch PR: https://github.com/kubernetes-sigs/descheduler/pull/989
ref #986 #959

Update helm chart rolebinding to use events.k8s.io

---

cmd/descheduler/app/server.go

today I upgraded to `0.25.2` version and noticed that the `json` format is not working
after a quick scan of the code I noticed that `factory` is always `nil`.
some related problems #991 and #965 
I'm sure there is a much more elegant solution to this problem.

correct JSON log format

---

README.md
pkg/framework/plugins/nodeutilization/highnodeutilization.go
pkg/framework/plugins/nodeutilization/lownodeutilization.go
pkg/framework/plugins/nodeutilization/lownodeutilization_test.go
pkg/framework/plugins/nodeutilization/nodeutilization.go
pkg/framework/plugins/nodeutilization/types.go
pkg/framework/plugins/nodeutilization/validation.go
pkg/framework/plugins/nodeutilization/zz_generated.deepcopy.go

add namespace filter to nodeutilization

---

charts/descheduler/templates/NOTES.txt
charts/descheduler/values.yaml
pkg/descheduler/descheduler.go

Signed-off-by: Furkan <furkan.turkal@trendyol.com>
Co-authored-by: Emin <emin.aktas@trendyol.com>
We've tried to install Descheduler using Helm chart and enabled both `dryRun` and `leaderElection` mode in `values.yaml`. And noticed leader election does not work due to `dryRun` activated. So thought a warning might be useful in this case.

add warning when enabling both dryRun and leaderElection

---

charts/descheduler/README.md
charts/descheduler/values.yaml
docs/user-guide.md
kubernetes/cronjob/cronjob.yaml
kubernetes/deployment/deployment.yaml
kubernetes/job/job.yaml

This updates references from `k8s.gcr.io` to `registry.k8s.io`. More info at https://github.com/kubernetes/k8s.io/wiki/New-Registry-url-for-Kubernetes-(registry.k8s.io)

Switch to registry.k8s.io

---

charts/descheduler/README.md
charts/descheduler/templates/cronjob.yaml
charts/descheduler/values.yaml

Allow end users to optionally set the descheduler CronJob `.spec.jobTemplate.spec.ttlSecondsAfterFinished` using helm chart.
ref: https://kubernetes.io/docs/concepts/workloads/controllers/job/#clean-up-finished-jobs-automatically
and correct & fmt `README.md` because  `successfulJobsHistoryLimit, failedJobsHistoryLimit` have [the default values](https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/#jobs-history-limits).

Allow a setting option `ttlSecondsAfterFinished` for job

---

Makefile
cloudbuild.yaml

Builds have been timing out since we run them sequentially [here](https://github.com/kubernetes-sigs/descheduler/blob/9f6afd4d2526cc31e1486d25e2f1ecd1d7476de5/Makefile#L89)
Sample failed build: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-descheduler-push-images/1602480325080911872

parallelize docker build for each arch

---

cloudbuild.yaml

increase cloudbuild timeout to 30 minutes until we figure out proper optimizations

---

cloudbuild.yaml

Doing this as a last resort until we can sort out parallel builds as asked in https://github.com/kubernetes/test-infra/issues/28258, hoping this will unblock our release

Increase cloud build timeout to 1 hour

---

pkg/descheduler/policyconfig.go

The io/ioutil package has been deprecated from go 1.16:https://go.dev/doc/go1.16#ioutil
/kind cleanup

cleanup: remove ioutil for new go version

---

Dockerfile
Dockerfile.dev
charts/descheduler/templates/cronjob.yaml
charts/descheduler/templates/deployment.yaml
kubernetes/cronjob/cronjob.yaml
kubernetes/deployment/deployment.yaml
kubernetes/job/job.yaml

--help is now an CMD which means explicitly providing a command override in kubernetes is no longer required. You can now simply provide the necessary arguments
With this change it's now possible to simply override the --help argument by providing explicit arguments instead.
Therefore explicitly using `command` in kubernetes resources is no longer required.
It might make seem like a trivial change, but this way it fits way better in my deployment automation and I'd appreciate if you could merge this.

Split CMD into ENTRYPOINT and CMD for Dockerfile

---

charts/descheduler/Chart.yaml

Fixes https://github.com/kubernetes-sigs/descheduler/issues/1020

Update helm chart to v0.26.0

---

metrics/metrics.go
pkg/descheduler/descheduler.go

This PR enables collection of metrics around the following
1. Amount of time taken for each loop of descheduler operation
2. Amount of time taken for each strategy operation to complete
This represents the values mentioned above as a Histogram with measurements tracked as a factor of seconds in time unit.
Closes #1037

metrics: enable loop duration and strategy duration metrics

---

pkg/framework/plugins/removepodsviolatingnodetaints/node_taint.go

After the skipNode, the outer loop is not doing anything, there is no need to execute continue.

remove some logic useless

---

charts/descheduler/templates/configmap.yaml
charts/descheduler/values.yaml

This PR adds the option to specify descheduler policy API version. Currently the version is hardcoded in helm template/manifest and points to deprecated v1alpha1.
This PR fixes the issue: https://github.com/kubernetes-sigs/descheduler/issues/1069

Adding descheduler policy API Version option in helm templates

---

pkg/framework/plugins/nodeutilization/types.go

Fix typo in nodeutilization types

---

README.md

Fixes https://github.com/kubernetes-sigs/descheduler/issues/1073
GKE doesn't let users customize the scheduler config, but this autoscaling profile has the same effect on the config. This requires cluster autoscaling to be enabled, but it is the only workaround for GKE besides running a second scheduler. Besides, if someone is using bin-packing, there's a good chance they are also using autoscaling anyway.

Add note to HighNodeUtilization readme for GKE users

---

charts/descheduler/templates/cronjob.yaml
charts/descheduler/templates/deployment.yaml
charts/descheduler/values.yaml

enhance: https://github.com/kubernetes-sigs/descheduler/issues/1065

expose security context from helm chart

---

.github/workflows/helm.yaml

Rationale:
1. e2e tests are not executed against a Descheduler install. If anything, we could end up with a race condition between a Descheduler run and the e2e tests. For example, notice [here](https://github.com/kubernetes-sigs/descheduler/blob/master/test/e2e/e2e_leaderelection_test.go#L105) that the test runs Descheduler itself.
2. We already run e2e tests against 3 Kubernetes Versions

remove e2e tests from helm github action

---

pkg/api/v1alpha1/conversion.go
pkg/descheduler/descheduler.go

enhance issue : https://github.com/kubernetes-sigs/descheduler/issues/1062
i have already test on my local kubernetes platform

Add k8s compatibility warnings to logs

---

cmd/descheduler/app/options/options.go
docs/cli/descheduler.md

dry-run cli flag to use uppercase

---

pkg/framework/plugins/defaultevictor/defaults.go

fix if condition for the right value of EvictLocalStoragePods

fix default value assignment of EvictLocalStoragePods

---

pkg/descheduler/policyconfig.go

// Deprecated: As of Go 1.16, this function simply calls os.ReadFile.
At the same time , We should not use "io/ioutil" , and replaced by "io" and "os" package.

Delete "io/ioutil" package.

---

.github/workflows/manifests.yaml
kubernetes/base/configmap.yaml
pkg/api/types.go
test/kind-config.yaml
test/manifests/v1alpha1/configmap.yaml
test/manifests/v1alpha2/configmap.yaml

Fixes #1121 
Plugin arg objects refer to the internal API type for some settings, but those types don't have json tags which causes an error trying to decode the config. This adds json tags to those types and sets up a new github workflow for testing that the descheduler is deployed in a kind cluster and starts running successfully.
As a follow up, we should expand the test suite to cover all possible plugin configurations (ie, a big config file that uses every setting possible) for both v1alpha1 and v1alpha2.
We also might want to just copy these internal types to the v1alpha2 package and use those, if possible.

Add json tags to internal api fields

---

README.md

The fact that `master` is the development branch and doesn't always work with published releases tends to cause a lot of confusion. This adds a note to the readme directing people to the right docs for the most recent supported versions. This should be especially useful as v1alpha2 is not going to be supported <v0.27

Add note on documentation versions with links

---

README.md
docs/deprecated/v1alpha1.md

k8s 1.27: update docs and README

---

pkg/descheduler/descheduler.go
pkg/descheduler/descheduler_test.go

Follow up to https://github.com/kubernetes-sigs/descheduler/pull/1063  to add unit tests
/cc @JaneLiuL

add unit tests for version compatibility check

---

test/run-e2e-tests.sh

This PR replace references of https://storage.googleapis.com/kubernetes-release with https://dl.k8s.io 
https://github.com/kubernetes/k8s.io/issues/2396

Use dl.k8s.io instead of kubernetes-release bucket

---

charts/descheduler/templates/cronjob.yaml
charts/descheduler/templates/deployment.yaml
charts/descheduler/values.yaml

1. ability to override comand and args from helm value. for example we pipe certain commands and as a result, we're using kustomize to patch it since helm doesn't provide the cmd/args values
2. set args inline to make booleans work.
`$key=$value` as opposed to:
```
- --key
- value
```
Currently this is failing for me:
```
- --dry-run
- false # this is an issue
```
but this works:
```
- --dry-run=false
```

helm: ability to override command and args. set args inline

---

charts/descheduler/templates/deployment.yaml

before fix:
```
❯ helm template descheduler . --set 'imagePullSecrets[0].name=test' --set 'kind=Deployment' | grep imagePullSecrets -B 1 -A 2
serviceAccountName: descheduler
imagePullSecrets:
- name: test
containers:
```
after fix:
```
❯ helm template descheduler . --set 'imagePullSecrets[0].name=test' --set 'kind=Deployment' | grep imagePullSecrets -B 1 -A 2
serviceAccountName: descheduler
imagePullSecrets:
- name: test
containers:
```

fix: imagepullsecrets indentation for kind: Deployment

---

.github/workflows/helm.yaml

Resolve  #1172 
Update `.github/workflows/helm.yaml` to use environment file instead of deprecated `set-output` command. 
For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
I found the workflow files that use `set-output` command through the following command:
```bash
$ find . -name '*.yml' -o -name '*.yaml' | xargs egrep '\bset-output\b'
```
**AS-IS**
```yml
echo "::set-output name=changed::true"
```
**TO-BE**
```yml
echo "changed=true" >> $GITHUB_OUTPUT
```

Replace deprecated command with environment file

---

cmd/descheduler/app/server.go

Huge clusters with thousands of pods can quickly exceed the default watch channel size of the fake clientset. Causing the channel to panic with "channel full".

FakeClientset: bump watch channel size

---

pkg/framework/plugins/podlifetime/pod_lifetime.go
pkg/framework/plugins/removeduplicates/removeduplicates.go
pkg/framework/plugins/removefailedpods/failedpods.go
pkg/framework/plugins/removepodshavingtoomanyrestarts/toomanyrestarts.go
pkg/framework/plugins/removepodsviolatinginterpodantiaffinity/pod_antiaffinity.go
pkg/framework/plugins/removepodsviolatingnodeaffinity/node_affinity.go
pkg/framework/plugins/removepodsviolatingtopologyspreadconstraint/topologyspreadconstraint.go

we run descheduler at log level 1 but still the "Processing" log lines bring too much noise.
if I wanted to debug why a pod on a node/namespace was not behaving correctly, I would temporarily bump the log level and then revert once done.

bump log level for processing info

---

pkg/descheduler/node/node.go

Currently nodeFit unnecessary logs for every nodeFit error. This change will aggregate all errors into one log entry to reduce noise.

nodefit: aggregate errors

---

README.md
pkg/descheduler/node/node.go
pkg/descheduler/node/node_test.go
pkg/framework/plugins/removepodsviolatingnodeaffinity/node_affinity.go
pkg/framework/plugins/removepodsviolatingnodeaffinity/node_affinity_test.go
pkg/utils/pod.go
pkg/utils/predicates.go
pkg/utils/predicates_test.go

Now, the descheduler can detect and evict pods that are not optimally allocated according to the "preferred..." node affinity. It only evicts a pod if it can be scheduled on a node that scores higher in terms of preferred node affinity than the current one.
This can be activated by enabling the RemovePodsViolatingNodeAffinity plugin and passing "preferredDuringSchedulingIgnoredDuringExecution" in the args.
For example, imagine we have a pod that prefers nodes with label "key1: value1" with a weight of 10. If this pod is scheduled on a node that doesn't have "key1: value1" as label but there's another node that has this label and where this pod can potentially run, then the descheduler will evict the pod.
Another effect of this commit is that the
RemovePodsViolatingNodeAffinity plugin will …

feat: Implement preferredDuringSchedulingIgnoredDuringExecution for RemovePodsViolatingNodeAffinity

---

pkg/descheduler/descheduler.go

see golang/go#60048
I learned this change from https://github.com/golang/tools/blob/9abb02c1b5524bf655a0985bc101496a6b53ff71/internal/gocommand/invoke.go#L265, thanks to author https://github.com/heschi 🙏

fix: descheduler_loop_duration_seconds has wrong value

---

.github/workflows/helm.yaml
.github/workflows/manifests.yaml
Dockerfile
Makefile
README.md
docs/deprecated/v1alpha1.md
docs/user-guide.md

closes #1193 
- go-version was missed in 1.28 upgrade
- k8s-version was missed in 1.28 upgrade
update docs before we cut tag

k8s 1.28: update docs and go-version

---

.github/workflows/manifests.yaml
charts/descheduler/Chart.yaml

rebased on top of #1224 
pre-requisites:
- cut release-1.28 branch
- cut v0.28.0 tag and publish image
closes #1196

helm: bump chart to v0.28.0

---

pkg/descheduler/evictions/evictions.go
pkg/framework/plugins/defaultevictor/defaultevictor.go

error logs don't follow correct klog ErrorS syntax
```
func ErrorS(err error, msg string, keysAndValues ...interface{}) {
```
https://github.com/kubernetes/klog/blob/main/klog.go#L1599

fix: structured err logs in eviction

---

charts/descheduler/templates/cronjob.yaml

Fixes https://github.com/kubernetes-sigs/descheduler/issues/1226
Make it match both the deployment parallel
https://github.com/kubernetes-sigs/descheduler/blob/33e9a52385394a3f4b2cb55bdf717fe52f1a852f/charts/descheduler/templates/cronjob.yaml#L71
As well as the documented arg
https://github.com/kubernetes-sigs/descheduler/blob/master/docs/user-guide.md#balance-cluster-by-pod-age

helm: update cronjob args argument to avoid unmarshal error

---

.golangci.yml

timeout is the current variable name and goimports indentation was off.
[timeout ref](https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml#L14)

fix: golangci config

---

pkg/framework/plugins/defaultevictor/defaultevictor.go

Pods that don't pass the nodeFit condition currently log an unsuppressable error message to logs. This changes the log level to info as it's a normal operating condition.

nodefit: use info log level when pod doesn't fit

---

charts/descheduler/README.md
charts/descheduler/templates/cronjob.yaml
charts/descheduler/values.yaml

closes #1243 
Stable in 1.27 - field is optional
https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#time-zones
Test:
```
helm template deschduler ./descheduler -f ./descheduler/values.yaml --set timeZone=Etc/UTC
...
apiVersion: batch/v1
kind: CronJob
metadata:
name: deschduler-descheduler
namespace: default
labels:
app.kubernetes.io/name: descheduler
helm.sh/chart: descheduler-0.28.0
app.kubernetes.io/instance: deschduler
app.kubernetes.io/version: "0.28.0"
app.kubernetes.io/managed-by: Helm
spec:
schedule: "*/2 * * * *"
concurrencyPolicy: "Forbid"
timeZone: Etc/UTC
jobTemplate:
spec:
...
```

helm: support of `timeZone` for CronJob

---

charts/descheduler/templates/cronjob.yaml
charts/descheduler/templates/deployment.yaml
charts/descheduler/values.yaml

Changes:
- add ability to specify dnsConfig in helm chart for Deployment and CronJob resources
This allows specifying dnsConfig block like mentioned in the [kubernetes documentation](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-dns-config)
One example of what's in use at @myfitnesspal is 
```yaml
dnsConfig:
options:
- name: ndots
value: "2"
- name: single-request-reopen
- name: use-vc
```
screenshot of how the dns configuration is rendered on the cronjob resource

helm: ability to specify `dnsConfig`

---

cmd/descheduler/app/options/options.go
cmd/descheduler/app/server.go
docs/cli/descheduler.md

Backporting https://github.com/kubernetes-sigs/descheduler/pull/1270

[1.27] CVE 2023 44487 fixes

---

test/e2e/e2e_duplicatepods_test.go
test/e2e/e2e_leaderelection_test.go
test/e2e/e2e_test.go
test/e2e/e2e_toomanyrestarts_test.go
test/run-e2e-tests.sh

Backporting https://github.com/kubernetes-sigs/descheduler/pull/1166 to 1.26

[1.26] update pause image from 'kubernetes/pause' to 'registry.k8s.io/pause'

---

README.md
hack/kind_config.yaml
pkg/framework/plugins/removepodsviolatingtopologyspreadconstraint/topologyspreadconstraint.go
pkg/framework/plugins/removepodsviolatingtopologyspreadconstraint/topologyspreadconstraint_test.go
test/e2e/e2e_failedpods_test.go
test/e2e/e2e_test.go
test/e2e/e2e_topologyspreadconstraint_test.go
test/test_utils.go

Closes #1171 
In Kubernetes 1.27, this feature flag was graduated to beta and it respects topology spread constraints during rolling upgrades. Descheduler currently does not honor this and apps could get unnecessary evictions during rolling upgrade
Ref: https://github.com/kubernetes/enhancements/issues/3243

topologyspreadconstraint: support `matchLabelKeys`

---

pkg/framework/plugins/removeduplicates/removeduplicates.go

Logs from `RemoveDuplicates` plugin do not display `ownerKey` correctly. Here's an example:
```
"Average occurrence per node" node="<redacted>" ownerKey={} avg=5"
```
The PR adds an implementation of `Stringer` interface for `podOwner` struct. Example of logs after the change:
```
"Average occurrence per node" node="<redacted>" ownerKey="loki/StatefulSet/loki-write/docker.io/grafana/loki:2.8.2" avg=6
```

fix: display ownerKey in the logs correctly

---

cmd/descheduler/app/options/options.go
cmd/descheduler/app/server.go
cmd/descheduler/descheduler.go
docs/cli/descheduler.md
pkg/apis/componentconfig/types.go
pkg/apis/componentconfig/v1alpha1/types.go
pkg/apis/componentconfig/v1alpha1/zz_generated.conversion.go
pkg/apis/componentconfig/v1alpha1/zz_generated.deepcopy.go
pkg/apis/componentconfig/zz_generated.deepcopy.go

Issue initially reported in Slack [[ref](https://kubernetes.slack.com/archives/C09TP78DV/p1700566355255069)]. I noticed that the issue also persists in other projects (e.g. cluster-autsocaler) so perhaps something got changed in kubernetes/kubernetes with base-component
I followed the example from https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/component-base/logs/example/cmd/logger.go
Now onto testing. running locally to just simulate logs...
before (just hangs):
```
❯ timeout 10s go run cmd/descheduler/descheduler.go --logging-format=json
❯ echo $?
124
```
after:
```
❯ go run cmd/descheduler/descheduler.go --logging-format=json
{"ts":1700705698832.446,"caller":"server/secure_serving.go:57","msg":"Forcing use of http/1.1 only\n","v":0} …
```

fix: json logging

---

pkg/framework/plugins/nodeutilization/nodeutilization.go

A cleaner looking log.
Original:
> I1121 15:44:10.570746   47691 nodeutilization.go:198] "Node is underutilized" node="k8s-playground-control-plane" usage={"cpu":"950m","memory":"290Mi","pods":"9"} usagePercentage={"cpu":9.5,"memory":3.696861352760446,"pods":8.181818181818182}
vs.
> I1121 16:37:29.266709   60211 nodeutilization.go:204] "Node is underutilized" node="kind-control-plane" usage={"cpu":"950m","memory":"290Mi","pods":"9"} usagePercentage={"cpu":9.5,"memory":3.7,"pods":8.18}

Make the logged nodeutilization percentages human-readable

---

cmd/descheduler/app/server.go

In #1296 , I moved things around a bit and used defer for `done`. This breaks Job cancel, see comment: https://github.com/kubernetes-sigs/descheduler/pull/731#discussion_r811752424

fix: revert defer of context done

---

charts/descheduler/templates/cronjob.yaml
charts/descheduler/templates/deployment.yaml
charts/descheduler/values.yaml

This pull request adds the ability to specify the security context for the descheduler pod.
Other Kubernetes projects like the [cluster-autoscaler](https://github.com/kubernetes/autoscaler/blob/master/charts/cluster-autoscaler/templates/deployment.yaml#L303-L305) has this ability, useful to define the `fsGroup` setting which is only available at the pod level.
I tested it doing the change below and installing the helm chart in a kind cluster to be sure the schema is valid:
```diff
diff --git a/charts/descheduler/values.yaml b/charts/descheduler/values.yaml
index afc3b8ca3..d47c0a581 100644
--- a/charts/descheduler/values.yaml
+++ b/charts/descheduler/values.yaml
@@ -33,8 +33,8 @@ securityContext:
runAsUser: 1000
-podSecurityContext: {}
-  # fsGroup: 1000
+podSecurityContext:
+  fsGroup: …
```

helm: ability to specify security context for pod

---

pkg/framework/plugins/removepodsviolatingtopologyspreadconstraint/topologyspreadconstraint.go
pkg/framework/plugins/removepodsviolatingtopologyspreadconstraint/topologyspreadconstraint_test.go

There is a problem with the log display due to the use of non-exported fields：
https://github.com/kubernetes-sigs/descheduler/blob/f0f7ebbe9af680b338709391cf1c0da7c2270ce5/pkg/framework/plugins/removepodsviolatingtopologyspreadconstraint/topologyspreadconstraint.go#L220
Without this patch the `tsc` is printed as empty `{}`:
```sh
I1212 08:34:36.666387       1 topologyspreadconstraint.go:230] "Skipping topology constraint because it is already balanced" constraint={}
```
With this patch:
```sh
I1212 08:41:10.178744       1 topologyspreadconstraint.go:221] "Skipping topology constraint because it is already balanced" constraint={"MaxSkew":1,"TopologyKey":"topology.kubernetes.io/zone","Selector":[{}],"NodeAffinityPolicy":"Honor","NodeTaintsPolicy":"Ignore","PodNodeAffinity":{},"PodTolerations …
```

fix: topologySpreadConstraint fields in structured logs

---

README.md
pkg/framework/plugins/podlifetime/pod_lifetime_test.go
pkg/framework/plugins/podlifetime/validation.go

`PodLifeTime` plugin to support pods with container status `ImagePullBackOff`
```yaml
containerStatuses:
- image: test-podlifetime:latest
imageID: ""
lastState: {}
name: test-podlifetime
ready: false
restartCount: 0
started: false
state:
waiting:
message: Back-off pulling image "test-podlifetime:latest"
reason: ImagePullBackOff
```

`PodLifeTime`: consider pods with container status `ImagePullBackOff`

---

.github/workflows/manifests.yaml
Makefile
README.md
charts/descheduler/Chart.yaml
docs/deprecated/v1alpha1.md
docs/user-guide.md
hack/kind_config.yaml
kubernetes/cronjob/cronjob.yaml
kubernetes/deployment/deployment.yaml
kubernetes/job/job.yaml

Needs: https://github.com/kubernetes/k8s.io/pull/6236
Closes #1320 and #1326

v0.29.0: bump helm chart and update manifests/docs

---

pkg/framework/plugins/podlifetime/pod_lifetime.go
pkg/framework/plugins/podlifetime/pod_lifetime_test.go

correct desired pod creation time
"Two pods in the `dev` Namespace, 1 created 605 seconds ago. 1 should be evicted.", the create time stamp should be 605 s before current time

fix(podlifetime): fix failed unittest

---

pkg/api/v1alpha1/conversion.go

in preparation to support removal of `v1alpha1` #974

v1alpha1: log deprecation notice

---

charts/descheduler/README.md
charts/descheduler/templates/cronjob.yaml
charts/descheduler/templates/deployment.yaml
charts/descheduler/values.yaml

Add support for [topologySpreadConstraints](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/)

feat: Add support for topologySpreadConstraints

---

pkg/framework/plugins/removepodshavingtoomanyrestarts/toomanyrestarts.go
pkg/framework/plugins/removepodshavingtoomanyrestarts/toomanyrestarts_test.go

`RemovePodsHavingTooManyRestarts` plugin has a includeInitContainers field but it doesn't actually check for init container status

fix: `RemovePodsHavingTooManyRestarts` to include `InitContainerStatuses`

---

metrics/metrics.go
pkg/descheduler/evictions/evictions.go
pkg/framework/plugins/nodeutilization/highnodeutilization.go
pkg/framework/plugins/nodeutilization/lownodeutilization.go
pkg/framework/plugins/nodeutilization/nodeutilization.go
pkg/framework/plugins/podlifetime/pod_lifetime.go
pkg/framework/plugins/removeduplicates/removeduplicates.go
pkg/framework/plugins/removefailedpods/failedpods.go
pkg/framework/plugins/removepodshavingtoomanyrestarts/toomanyrestarts.go
pkg/framework/plugins/removepodsviolatinginterpodantiaffinity/pod_antiaffinity.go
pkg/framework/plugins/removepodsviolatingnodeaffinity/node_affinity.go
pkg/framework/plugins/removepodsviolatingnodetaints/node_taint.go
pkg/framework/plugins/removepodsviolatingtopologyspreadconstraint/topologyspreadconstraint.go
pkg/framework/profile/profile.go
pkg/framework/profile/profile_test.go

/kind feature
Supports profile name set under the label `profile`  for the metric `pods_evicted`. 
This allows the possibility of alerting different severities for different profiles.
Also, some refactors related to `EvictOptions` to make it more standard.
NONE
~~I really do not think `ProfileName` as a public function was the best idea for `PodEvictor`, but adding to `NewPodEvictor` would require changes over many lines of code. Any suggestions on how to improve it?~~
Already discussed in the comments.
```yaml
apiVersion: "descheduler/v1alpha1"
kind: "DeschedulerPolicy"
strategies:
"PodLifeTime":
enabled: true
params:
podLifeTime:
maxPodLifeTimeSeconds: 5
states:
- "Running"
- "Pending"
- "PodInitializing"
"RemoveFailedPods":
enabled: true
params:
failedPods:
reasons:
- "NodeAffinity" …
```

Improve PodEvictor observability through EvictOptions

---

pkg/framework/plugins/removepodsviolatingnodetaints/node_taint.go

/kind bug
[This PR](https://github.com/kubernetes-sigs/descheduler/pull/1349) introduced extended observability capabilities. One of the strategies (`RemovePodsViolatingNodeTaints`) is [pointing to the wrong field](https://github.com/kubernetes-sigs/descheduler/pull/1349/files#diff-74787e2a818e9f68036e134eee3882d886eaebda722cf297285b0b9d3e715d47R115) (`ProfileName` instead of `StrategyName`). Looks like the only place `profileName` should be set is [here](https://github.com/kubernetes-sigs/descheduler/pull/1349/files#diff-3adf3dff318d6a906144789d65afdeb99231e8eb6d6bc0707dda3ca8278337edR257).
This change fixes it by pointing right struct field.
NONE
NONE
```release-note
NONE
```
```docs
NONE
```

Fix node taint wrong EvictOption field

---

pkg/descheduler/node/node.go

This PR adds some additional language across the three flavors of "does this pod fit on a node?" funcs that are used to inform eviction filters. This can aid debugging so that our logs can tell us at a glance where in the eviction flow we are at.

Disambiguate node fit log messages

---

README.md
pkg/descheduler/node/node.go
pkg/descheduler/node/node_test.go
pkg/descheduler/pod/pods.go
pkg/descheduler/pod/pods_test.go
pkg/framework/plugins/removepodsviolatinginterpodantiaffinity/pod_antiaffinity.go
pkg/framework/plugins/removepodsviolatinginterpodantiaffinity/pod_antiaffinity_test.go
pkg/utils/predicates.go
pkg/utils/predicates_test.go
pkg/utils/priority.go
test/run-e2e-tests.sh
test/test_utils.go

Closes https://github.com/kubernetes-sigs/descheduler/issues/1279
More context: https://github.com/kubernetes-sigs/descheduler/issues/1149
This PR:
* Adds a check so that NodeFit() assesses whether it is possible for a given Pod to be scheduled on a given Node before descheduling it.
* Uses the logic from the plugin [RemovePodsViolatingInterPodAntiAffinity](https://github.com/kubernetes-sigs/descheduler/blob/master/pkg/framework/plugins/removepodsviolatinginterpodantiaffinity/pod_antiaffinity.go) which already contains logic for fetching and comparing the pod anti-affinity rule of pods in [checkPodsWithAntiAffinityExist](https://github.com/kubernetes-sigs/descheduler/blob/6c865fdf32ac8fa9b20fd9a971b2631eabab0b1d/pkg/framework/plugins/removepodsviolatinginterpodantiaffinity/pod_antiaffinity …

Check whether pod matches the inter-pod anti-affinity of another Pod in a given Node in `NodeFit()`

---

README.md
pkg/descheduler/pod/pods.go
pkg/framework/plugins/defaultevictor/defaultevictor.go
pkg/framework/plugins/defaultevictor/defaultevictor_test.go
pkg/framework/plugins/defaultevictor/types.go
pkg/framework/plugins/defaultevictor/validation.go
test/e2e/e2e_duplicatepods_test.go

alternate implementation to #1152
Closes #1058 
/cc @jiangxiaobin96

skip eviction when replica count is below evictor `minReplicas` threshold setting

---

README.md
pkg/api/v1alpha1/types.go
pkg/api/v1alpha1/zz_generated.deepcopy.go
pkg/framework/plugins/removepodsviolatingnodetaints/defaults.go
pkg/framework/plugins/removepodsviolatingnodetaints/defaults_test.go
pkg/framework/plugins/removepodsviolatingnodetaints/node_taint.go
pkg/framework/plugins/removepodsviolatingnodetaints/node_taint_test.go
pkg/framework/plugins/removepodsviolatingnodetaints/types.go
pkg/framework/plugins/removepodsviolatingnodetaints/validation.go
pkg/framework/plugins/removepodsviolatingnodetaints/validation_test.go
pkg/framework/plugins/removepodsviolatingnodetaints/zz_generated.deepcopy.go

Fixes #1353. 
Adds the option to apply the RemovePodsViolatingNodeTaints strategy only for an explicitly allowlisted set of taints.
When a list of includedTaints is provided, a taint will be considered if and only if it matches an included key **or** key=value from the list. Otherwise it will be ignored. Leaving includedTaints unset will include any taint by default.

Add argument to remove only pods violating allowlisted taints

---

README.md
charts/descheduler/values.yaml
docs/deprecated/v1alpha1.md
pkg/api/v1alpha1/conversion.go
pkg/api/v1alpha1/types.go
pkg/api/v1alpha1/zz_generated.deepcopy.go
pkg/apis/componentconfig/types.go
pkg/apis/componentconfig/v1alpha1/types.go
pkg/apis/componentconfig/v1alpha1/zz_generated.conversion.go
pkg/descheduler/policyconfig_test.go
pkg/framework/plugins/defaultevictor/defaultevictor.go
pkg/framework/plugins/defaultevictor/defaults.go
pkg/framework/plugins/defaultevictor/defaults_test.go
pkg/framework/plugins/defaultevictor/types.go
test/e2e/e2e_test.go

/kind feature
Enables eviction of DaemonSet pods with the key `evictDaemonSetPods: true` for evictors
NONE
By default, allowing eviction of pods from daemonsets may be dangerous if misconfigured.
With the release of `v1alpha2` profiles, we got the ability to tune granular specs for eviction profiles.  This means now that it is possible to select specific daemonset to allow pod eviction automatically. This is interesting because reduces toil of pod recreation for specific scenarios.
```release-note
Allow eviction of daemonset pods by `evictDaemonSetPods` key
```
```docs
NONE
```

Allow eviction of DaemonSet pods

---

README.md

The `namespace filtering` section contains errors, and some descriptions are unclear and can be improved. This PR fixes the errors and enhances the descriptions for better clarity.

Fix and improve the namespace filtering description in README

---

README.md
pkg/framework/plugins/removefailedpods/failedpods.go
pkg/framework/plugins/removefailedpods/failedpods_test.go
pkg/framework/plugins/removefailedpods/types.go
pkg/framework/plugins/removefailedpods/zz_generated.deepcopy.go

The current `RemoveFailedPods` strategy includes a parameter `reason` from a terminated container's status (state). In addition to `reason`,  the field `exitCode` in a container's status, which describes the exit status from the last termination of a container, can provide additional and useful information about a container's termination.
A common use case is AI/ML training jobs often inject/run pre-flight health checks in initContainers and take actions according to the `exitCode` value when an initContainer fails, e.g., deleting the scheduled job pod via `Descheduler`.
This PR adds a terminated container's `exitCode` as an additional parameter to the `RemoveFailedPods` strategy. 
Fix https://github.com/kubernetes-sigs/descheduler/issues/1380

Add an extra parameter ExitCode to RemoveFailedPods

---

.github/workflows/helm.yaml
Dockerfile
Makefile
go.mod

https://github.com/kubernetes-sigs/descheduler/security/code-scanning/21

bump to to 1.22.3 to address CVE-2024-24788

---

cmd/descheduler/app/server.go

- use cmd context instead of using context.Background().
cmd *cobra.Command provided the context ctx, we should use this one provided by cmd instead of using context.Background(). We should pass the upstream ctx to the downstream.

use cmd context instead of using context.Background()

---

pkg/descheduler/node/node.go
pkg/descheduler/node/node_test.go
pkg/utils/predicates.go
pkg/utils/priority.go

Currently, the "podMatchesInterPodAntiAffinity" method has an issue. It is unable to check if the pod matches the anti-affinity rule of another pod that is already on the given node.
The root cause is that the "CheckPodsWithAntiAffinityExist" method in "predicate.go" can only check if pods with AntiAffinity issues exist on the same node
This pr can resolve that.

fix the issue that the pod anti-filtering rules are not taking effect

---

.github/workflows/helm.yaml
Makefile
hack/lib/go.sh
hack/update-gofmt.sh
hack/verify-gofmt.sh

when we cut a new release of descheduler, we have to update the go version in multiple places dquote> which presents an opportunity to miss updating one.

chore: reduce repetition of go versions

---

Dockerfile
go.mod

rebased on top of #1432 
[bump go to 1.22.4 for](https://github.com/kubernetes-sigs/descheduler/pull/1433/commits/1aa7ef88e6d572804098b80ed8325549590832d5) https://github.com/advisories/GHSA-49gw-vxvf-fc2g [and](https://github.com/kubernetes-sigs/descheduler/pull/1433/commits/1aa7ef88e6d572804098b80ed8325549590832d5) https://github.com/advisories/GHSA-236w-p7wf-5ph8

bump go to 1.22.4 for CVE-2024-24790 and CVE-2024-24789

---

pkg/utils/qos.go

If the pod's Qos has a value, return the QoS value early. For pods evicted within the descheduler, they are typically already scheduled onto nodes, and in most cases, the QoS value is already present on the pod's status. Therefore, it is unnecessary to start the determination process from scratch.

return pod qos in advance

---

test/e2e/e2e_duplicatepods_test.go
test/e2e/e2e_failedpods_test.go
test/e2e/e2e_leaderelection_test.go
test/e2e/e2e_test.go
test/e2e/e2e_toomanyrestarts_test.go
test/e2e/e2e_topologyspreadconstraint_test.go

/kind cleanup
- Use outer ctx instead of `context.TODO()`
- use `wait.PollUntilContextTimeout` instead of `wait.PollImmediate`

refactor some methods in e2e test

---

charts/descheduler/Chart.yaml
docs/deprecated/v1alpha1.md
docs/user-guide.md
kubernetes/cronjob/cronjob.yaml
kubernetes/deployment/deployment.yaml
kubernetes/job/job.yaml

Cherry pick of #1427 on master.
#1427: helm: upgrade to v0.30.1
For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.
```release-note
```

Automated cherry pick of #1427: helm: upgrade to v0.30.1

---

pkg/descheduler/pod/pods.go

We should return the unmatched cases first,and leave the filter method for last, because it is computationally expensive.

fix: return the unmatched cases first

---

pkg/descheduler/descheduler.go
pkg/descheduler/descheduler_test.go
pkg/descheduler/evictions/evictions.go
pkg/descheduler/evictions/evictions_test.go
pkg/framework/plugins/nodeutilization/highnodeutilization_test.go
pkg/framework/plugins/nodeutilization/lownodeutilization_test.go
pkg/framework/plugins/podlifetime/pod_lifetime_test.go
pkg/framework/plugins/removeduplicates/removeduplicates_test.go
pkg/framework/plugins/removefailedpods/failedpods_test.go
pkg/framework/plugins/removepodshavingtoomanyrestarts/toomanyrestarts_test.go
pkg/framework/plugins/removepodsviolatinginterpodantiaffinity/pod_antiaffinity_test.go
pkg/framework/plugins/removepodsviolatingnodeaffinity/node_affinity_test.go
pkg/framework/plugins/removepodsviolatingnodetaints/node_taint_test.go
pkg/framework/plugins/removepodsviolatingtopologyspreadconstraint/topologyspreadconstraint_test.go
pkg/framework/profile/profile_test.go
test/e2e/e2e_duplicatepods_test.go
test/e2e/e2e_failedpods_test.go
test/e2e/e2e_test.go
test/e2e/e2e_toomanyrestarts_test.go
test/e2e/e2e_topologyspreadconstraint_test.go

Drop nodes parameter from NewPodEvictor and set up the pod evictor only once for all descheduling cycles. While resetting the inner counters at the end of each descheduling cycle.
This is a pre-requisite for implementing eviction requests (https://github.com/kubernetes-sigs/descheduler/issues/1397).

PodEvictor: refactoring and preparation for eviction requests

---

pkg/descheduler/node/node.go
pkg/descheduler/node/node_test.go

There are many filter policies in the current node fit, similar to the filter plugin in the scheduler. The correct logic should be: if any plugin does not meet the conditions, it should be terminated in advance. The current check logic is incomprehensible, and it actually performs all filter check logic, which is not only time-consuming, but also very unnecessary.(https://github.com/kubernetes-sigs/descheduler/blob/master/pkg/descheduler/node/node.go#L107)
Because the default loop time is 5min, this time can be adjusted. The larger the cluster, the longer the nodeFit time, so the full loop time can easily exceed 5min. What if the user sets the loop time to 1 minute? Comparing one by one I think is very, very unnecessary, too time-consuming, we should be the same as the filter policy in …

return node fit error in advance

---

test/test_utils.go

UID is an integral part of every pod.
Even though we don't test for UID in any of the existing test cases, future test cases might rely on it.

test: generate uid when building a pod

---

pkg/descheduler/descheduler.go
pkg/descheduler/evictions/evictions.go
pkg/descheduler/evictions/evictions_test.go
pkg/descheduler/evictions/options.go
pkg/framework/plugins/nodeutilization/highnodeutilization_test.go
pkg/framework/plugins/nodeutilization/lownodeutilization_test.go
pkg/framework/plugins/podlifetime/pod_lifetime_test.go
pkg/framework/plugins/removeduplicates/removeduplicates_test.go
pkg/framework/plugins/removefailedpods/failedpods_test.go
pkg/framework/plugins/removepodshavingtoomanyrestarts/toomanyrestarts_test.go
pkg/framework/plugins/removepodsviolatinginterpodantiaffinity/pod_antiaffinity_test.go
pkg/framework/plugins/removepodsviolatingnodeaffinity/node_affinity_test.go
pkg/framework/plugins/removepodsviolatingnodetaints/node_taint_test.go
pkg/framework/plugins/removepodsviolatingtopologyspreadconstraint/topologyspreadconstraint_test.go
pkg/framework/profile/profile_test.go
test/e2e/e2e_duplicatepods_test.go
test/e2e/e2e_test.go
test/e2e/e2e_toomanyrestarts_test.go

when we add a new option to PodEvictor, it typically ends up touch dozens of files because it requires adding a new arg to the initializer. this is the first step in reducing the number of initializer args

feat: pod evictor options

---

pkg/framework/plugins/defaultevictor/defaultevictor.go
pkg/framework/plugins/defaultevictor/defaultevictor_test.go

It appears that DefaultEvictor is re-initialized, which causes a conflict issue when adding the same indexer again.
closes #1440

fix: indexer cache error when default evictor is re-initialized

---

pkg/api/v1alpha1/conversion.go
pkg/descheduler/evictions/errors.go
pkg/descheduler/evictions/evictions.go
pkg/descheduler/evictions/evictions_test.go
pkg/framework/fake/fake.go
pkg/framework/plugins/nodeutilization/nodeutilization.go
pkg/framework/plugins/podlifetime/pod_lifetime.go
pkg/framework/plugins/removeduplicates/removeduplicates.go
pkg/framework/plugins/removefailedpods/failedpods.go
pkg/framework/plugins/removepodshavingtoomanyrestarts/toomanyrestarts.go
pkg/framework/plugins/removepodsviolatinginterpodantiaffinity/pod_antiaffinity.go
pkg/framework/plugins/removepodsviolatingnodeaffinity/node_affinity.go
pkg/framework/plugins/removepodsviolatingnodetaints/node_taint.go
pkg/framework/plugins/removepodsviolatingtopologyspreadconstraint/topologyspreadconstraint.go
pkg/framework/profile/profile.go
pkg/framework/profile/profile_test.go
pkg/framework/types/types.go

When checking for node limit getting exceeded the pod eviction never fails. Thus, ignoring the metric reporting when a pod fails to be evicted due to node limit constrains.
The error also allows plugin to react on other limits getting exceeded. E.g. the limit on the number of pods evicted per namespace.
To allow other limits (e.g. as https://github.com/kubernetes-sigs/descheduler/pull/1451) to be easily introduced.
Also, resolves https://github.com/kubernetes-sigs/descheduler/pull/1368.

PodEvictor: turn an exceeded limit into an error

---

pkg/descheduler/descheduler_test.go
pkg/descheduler/policyconfig_test.go

- initPluginRegistry as a single way to register all plugins in testing
- Use v1alpha2 descheduling policy
- Set OwnerReferences through GetReplicaSetOwnerRefList
- Define initDescheduler for further use: Can be used by other tests executing individual descheduling cycle explicitly.

descheduler_test.go refactoring

---

pkg/api/types.go
pkg/api/v1alpha1/types.go
pkg/api/v1alpha1/zz_generated.deepcopy.go
pkg/api/v1alpha2/types.go
pkg/api/v1alpha2/zz_generated.conversion.go
pkg/api/v1alpha2/zz_generated.deepcopy.go
pkg/api/zz_generated.deepcopy.go
pkg/descheduler/descheduler.go
pkg/descheduler/evictions/errors.go
pkg/descheduler/evictions/evictions.go
pkg/descheduler/evictions/options.go
pkg/framework/plugins/nodeutilization/lownodeutilization_test.go
pkg/framework/plugins/nodeutilization/nodeutilization.go
pkg/framework/plugins/podlifetime/pod_lifetime.go
pkg/framework/plugins/podlifetime/pod_lifetime_test.go
pkg/framework/plugins/removeduplicates/removeduplicates.go
pkg/framework/plugins/removefailedpods/failedpods.go
pkg/framework/plugins/removepodshavingtoomanyrestarts/toomanyrestarts.go
pkg/framework/plugins/removepodsviolatinginterpodantiaffinity/pod_antiaffinity.go
pkg/framework/plugins/removepodsviolatinginterpodantiaffinity/pod_antiaffinity_test.go
pkg/framework/plugins/removepodsviolatingnodeaffinity/node_affinity.go
pkg/framework/plugins/removepodsviolatingnodeaffinity/node_affinity_test.go
pkg/framework/plugins/removepodsviolatingnodetaints/node_taint.go
pkg/framework/plugins/removepodsviolatingnodetaints/node_taint_test.go
pkg/framework/plugins/removepodsviolatingtopologyspreadconstraint/topologyspreadconstraint.go

The MaxNoOfPodsToEvictTotal serves to prevent scenarios where an unintended issue, such as a software bug or incorrect usage of Pod Disruption Budgets (PDBs), could result in a substantial number of pods being evicted simultaneously, potentially compromising the availability of services.
Fixes #1449

The descheduler supports limiting the total number of pods evicted per rescheduling cycle

---

pkg/descheduler/evictions/evictions.go

Currently, all the plugins are run in a sequence.
No plugin executes evictions in parallel within.
Yet, there's no guarantee a future plugin (e.g. a custom one) will not attemp to evict pods in parallel.

pod evictor: make it thread safe

---

README.md

Update README.md to include information about maxNoOfPodsToEvictTotal.  
see: https://github.com/kubernetes-sigs/descheduler/issues/1449

Update README about maxNoOfPodsToEvictTotal

---

charts/descheduler/README.md
charts/descheduler/templates/_helpers.tpl
charts/descheduler/templates/clusterrolebinding.yaml
charts/descheduler/templates/configmap.yaml
charts/descheduler/templates/cronjob.yaml
charts/descheduler/templates/deployment.yaml
charts/descheduler/templates/service.yaml
charts/descheduler/templates/serviceaccount.yaml
charts/descheduler/templates/servicemonitor.yaml
charts/descheduler/values.yaml

This PR includes changes to allow the descheduler Helm chart to be deployed to a specified namespace.
You can deploy to a specific namespace by setting namespaceOverride in the values.yaml file as follows:
```
namespaceOverride: your-custom-namespace
```

feat: Add namespace override settings in Helm Chart

---

charts/descheduler/templates/_helpers.tpl
charts/descheduler/values.yaml

reported issue: https://kubernetes.slack.com/archives/C09TP78DV/p1718633429179519
Test using `leaderElection.resourceNamescape`
```
helm template deschduler ./descheduler -f ./descheduler/values.yaml --set kind=Deployment --set=leaderElection.enabled=true --set=leaderElection.resourceNamescape=foo
Error: execution error at (descheduler/templates/deployment.yaml:62:16): 'leaderElection.resourceNamescape' is deprecated. instead use 'leaderElection.resourceNamespace'
```
Test using `leaderElection.resourceNamespace`
```
helm template deschduler ./descheduler -f ./descheduler/values.yaml --set kind=Deployment --set=leaderElection.enabled=true --set=leaderElection.resourceNamespace=foo | grep leader-elect-resource-namespace
- --leader-elect-resource-namespace=foo

fix: helm leader-election typo to `resourceNamespace`

---

.github/workflows/helm.yaml
charts/descheduler/tests/.gitignore
charts/descheduler/tests/cronjob_test.yaml
charts/descheduler/tests/deployment_test.yaml

there's been a few issues recently raised about helm chart not working after releases.
this PR proposes a unit test harness and if approved, I can contribute more unit tests
Output: https://github.com/kubernetes-sigs/descheduler/actions/runs/9944911041/job/27471971492?pr=1467
```
PASS  Test Descheduler Deployment	charts/descheduler/tests/deployment_test.yaml
Charts:      1 passed, 1 total
Test Suites: 2 passed, 2 total
Tests:       5 passed, 5 total
Snapshot:    0 passed, 0 total
Time:        27.609379ms
```

helm unit tests

---

Makefile

Get the latest to see if it helps with the timeouts

bump(github.com/golangci/golangci-lint)=v1.59.1

---

test/e2e/e2e_test.go
test/e2e/e2e_toomanyrestarts_test.go

Part or replacing direct invocation of plugins with running an entire descheduler while providing a policy with the expected plugins configured.
To goal is to get closer to running a descheduler in production. The current approach still resembles the way the descheduler is exercises in unit tests.

e2e: TestTooManyRestarts: run descheduler as a whole instead of a single plugin

---

test/e2e/e2e_duplicatepods_test.go

RemoveDuplicates is namespaced scope. Limiting the namespace will avoid unexpected evictions from other namespaces.

e2e: TestRemoveDuplicates: limit the tested namespace

---

keps/1397-evictions-in-background/README.md
keps/1397-evictions-in-background/kep.yaml

**Is your feature request related to a problem? Please describe.**
The descheduler eviction policy is built on top of the eviction API. The API currently does not support eviction requests that are not completed right away. Instead, any eviction needs to either succeed or be rejected in response. Nevertheless, there are cases where an eviction request is expected to only initiate eviction. While getting confirmation or rejection of the eviction initiation (or its promise).
**Describe the solution you'd like**
Utilize [evacuation API](https://github.com/kubernetes/enhancements/pull/4565) as an alternative to eviction API. As an interim solution (until the evacuation API is available) allow to interpret pods with a special annotation as a request for eviction initiation instead of expecting …

KEP-1397: descheduler integration with evacuation API as an alternative to eviction API

---

test/e2e/e2e_leaderelection_test.go

In some random cases none of the deschedulers acquires a lease. Making the test fail due to already existing lease.

e2e: TestLeaderElection: delete the lease and increase the retry period

---

Dockerfile
go.mod

This will address [GO-2024-2887 ](https://pkg.go.dev/vuln/GO-2024-2887 ) and [GO-2024-2963](https://pkg.go.dev/vuln/GO-2024-2963).

bump go to 1.22.5

---

Dockerfile

Add a label for the OCI annotation for image source, as per https://github.com/opencontainers/image-spec/blob/main/annotations.md
This can allow for tools such as "[renovatebot](https://docs.renovatebot.com/modules/datasource/docker/)" to find the source code for a container image via its manifest, and with that, finding changelogs to publish in automated PRs for dependency updates ([example](https://github.com/renovate-reproductions/26286/pull/1)).

docs: Provide OCI annotation for where to find image sources

---

pkg/framework/plugins/nodeutilization/highnodeutilization_test.go
pkg/framework/plugins/nodeutilization/lownodeutilization_test.go
pkg/framework/plugins/podlifetime/pod_lifetime_test.go
pkg/framework/plugins/removeduplicates/removeduplicates_test.go
pkg/framework/plugins/removefailedpods/failedpods_test.go
pkg/framework/plugins/removepodshavingtoomanyrestarts/toomanyrestarts_test.go
pkg/framework/plugins/removepodsviolatinginterpodantiaffinity/pod_antiaffinity_test.go
pkg/framework/plugins/removepodsviolatingnodeaffinity/node_affinity_test.go
pkg/framework/plugins/removepodsviolatingnodetaints/node_taint_test.go
pkg/framework/plugins/removepodsviolatingtopologyspreadconstraint/topologyspreadconstraint_test.go
pkg/framework/profile/profile_test.go
pkg/framework/testing/utils.go
test/e2e/e2e_duplicatepods_test.go
test/e2e/e2e_failedpods_test.go
test/e2e/e2e_test.go
test/e2e/e2e_topologyspreadconstraint_test.go

Initialize a plugin handler at once through a single function invocation. To avoid duplicating the same initialization code throughout the codebase.

tests: de-duplicate framework handle initialization

---

README.md

Remainder from https://github.com/kubernetes-sigs/descheduler/pull/1482
Fixes: #1375

README: drop v1alpha1 descheduler policy mention

---

.github/workflows/manifests.yaml
Makefile
test/run-e2e-tests.sh

Prep for v0.31 release
similar to https://github.com/kubernetes-sigs/descheduler/commit/ac4d576df8831c0c399ee8fff1e85469e90b8c44

descheduler v0.31: update e2e test versions

---

charts/descheduler/templates/cronjob.yaml
charts/descheduler/templates/deployment.yaml

This adds a conditional around `securityContext` in Deployment and CronJob template in order to be able to unset this property. In the same way `podSecurityContext` is handled.

feat(helm): make securityContext conditional in Deployment and CronJob

---

pkg/api/types.go
pkg/framework/plugins/defaultevictor/types.go
pkg/framework/plugins/nodeutilization/types.go
pkg/framework/plugins/podlifetime/types.go
pkg/framework/plugins/removeduplicates/types.go
pkg/framework/plugins/removefailedpods/types.go
pkg/framework/plugins/removepodshavingtoomanyrestarts/types.go
pkg/framework/plugins/removepodsviolatinginterpodantiaffinity/types.go
pkg/framework/plugins/removepodsviolatingnodeaffinity/types.go
pkg/framework/plugins/removepodsviolatingnodetaints/types.go
pkg/framework/plugins/removepodsviolatingtopologyspreadconstraint/types.go

```yaml
- args:
namespaces:
include:
- includedNamespace
```
looks better than
```yaml
- args:
excludedTaints: null
includePreferNoSchedule: false
includedTaints: null
labelSelector: null
namespaces:
exclude: []
include:
- includedNamespace
```

Plugin args: tag arguments with omitempty to reduce the marshalled json size

---

README.md
docs/user-guide.md

Closes https://github.com/kubernetes-sigs/descheduler/issues/1492
Similar to https://github.com/kubernetes-sigs/descheduler/pull/617/

descheduler v0.31: update docs and manifests

---

test/run-e2e-tests.sh

1、Avoid e2e test timeout, after migrating all e2e tests to containers, the execution time may increase, and e2e tests might time out；
2、Modify IMAGE_TAG to fix the version parsing issue;

[e2e] no test timeouts, produce the same image tag as in production

---

.github/workflows/manifests.yaml
README.md
kubernetes/cronjob/cronjob.yaml
kubernetes/deployment/deployment.yaml
kubernetes/job/job.yaml

Note that we can no longer reference tags, because tag is used to create the image and kustomize manifests are out of date on the tag (chicken-egg issue)

descheduler v0.31.0: bump kustomize files

---

.github/workflows/release.yaml

https://github.com/kubernetes-sigs/descheduler/actions/runs/10781069567/job/29898293792
see related issue: https://github.com/helm/chart-releaser-action/issues/110
```
Looking up latest tag...
Discovering changed charts since 'v0.31.0'...
Installing chart-releaser on /opt/hostedtoolcache/cr/v1.6.1/x86_64...
Adding cr directory to PATH...
Packaging chart 'charts/descheduler'...
Successfully packaged chart in /home/runner/work/descheduler/descheduler/charts/descheduler and saved it to: .cr-release-packages/descheduler-0.31.0.tgz
Releasing charts...
Error: error creating GitHub release descheduler-helm-chart-0.31.0: POST https://api.github.com/repos/kubernetes-sigs/descheduler/releases: 403 Resource not accessible by integration []
Usage:
cr upload [flags]
Flags:
-c, --commit string …
```

fix: github action Release Charts to have write permissions

---

test/e2e/e2e_failedpods_test.go
test/e2e/e2e_leaderelection_test.go
test/e2e/e2e_test.go
test/e2e/e2e_toomanyrestarts_test.go
test/e2e/e2e_topologyspreadconstraint_test.go
test/e2e/test_clientconnection_test.go
test/test_utils.go

abstract and aggregate some common methods in E2E tests to avoid redundancy.

[e2e] abstract common methods

---

pkg/descheduler/descheduler.go

This PR addresses that by implementing a more generic resource handling approach, ensuring that dry runs can access all resource types and objects as expected
I discovered an issue with dry-runs only seeing a subset of resources during execution when I was working on adding an option to [filter pods on pod disruption budgets](https://github.com/john7doe/descheduler/tree/john7doe/addPDBOption) (WIP, will PR later).
The root case was the order of the calls to create listers and the call to `WaitForCacheSync`.
I think this bug is the likely reason why this [special casing ](https://github.com/kubernetes-sigs/descheduler/blob/master/pkg/descheduler/node/node.go#L53-L69)was added.  With the new code thats no longer needed (if reviews agree with that, then I can remove it as part of this PR). …

Make sure dry runs sees all the resources a normal run would do

---

pkg/framework/plugins/nodeutilization/highnodeutilization.go
pkg/framework/plugins/nodeutilization/lownodeutilization.go

Prep work for load-aware descheduling: https://github.com/kubernetes-sigs/descheduler/issues/225.

Node utilization refactoring

---

Dockerfile

FIX - CVE-2024-34156 (HIGH), CVE-2024-34155, CVE-2024-34158

Update Dockerfile - GoLang v 1.22.7 FIX - CVE-2024-34156, CVE-2024-34155 and CVE-2024-34158

---

Dockerfile

FIX: CVE-2024-24790 and CVE-2024-34156 [Go:v1.22.7]

---

pkg/framework/plugins/nodeutilization/nodeutilization.go
pkg/framework/plugins/nodeutilization/nodeutilization_test.go

So `sortNodesByUsage` can be invoked over any list of resources

Update nodes sorting function to respect available resources

---

pkg/framework/plugins/nodeutilization/nodeutilization.go

To address https://github.com/kubernetes-sigs/descheduler/pull/1541#discussion_r1840440872

sortNodesByUsage: drop extended resources as they are already counted in

---

pkg/descheduler/node/node.go
pkg/descheduler/pod/pods.go
pkg/framework/plugins/nodeutilization/highnodeutilization.go
pkg/framework/plugins/nodeutilization/lownodeutilization.go
pkg/framework/plugins/nodeutilization/nodeutilization.go

Extracting requested resource is not the only way to get pod's utilization. Consuming actual usage from metrics is another option. Thus, abstracting `NodeUtilization` so the utilization function can be replaced as needed.

nodeutilization: NodeUtilization: make pod utilization extraction configurable

---

pkg/descheduler/node/node.go
pkg/descheduler/pod/pods.go
pkg/framework/plugins/nodeutilization/highnodeutilization.go
pkg/framework/plugins/nodeutilization/lownodeutilization.go
pkg/framework/plugins/nodeutilization/nodeutilization.go

So `evictPodsFromSourceNodes` can process any list of resources.
Built on top of https://github.com/kubernetes-sigs/descheduler/pull/1543.

nodeutilization: evictPodsFromSourceNodes: iterate through existing resources

---

pkg/framework/plugins/nodeutilization/nodeutilization.go

nodeutilization: usage2KeysAndValues for constructing a key:value list for InfoS printing resource usage

---

.github/workflows/release.yaml

Cherry pick of #1514 on release-1.30.
#1514: fix: github action Release Charts to have write permissions
For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.
```release-note
```

Automated cherry pick of #1514: fix: github action Release Charts to have write permissions

---

Dockerfile
docs/contributor-guide.md
go.mod
hack/lib/go.sh

The k/k repo was bumped to Go 1.23.3. See below PR for reference.
https://github.com/kubernetes/kubernetes/pull/128852

Bump to Go 1.23.3

---

.golangci.yml

Sometimes golangci-lint timesout when running in CI. Bump the timeout from 2 minutes to 5 minutes to reduce flakey CI failures.
ref: https://golangci-lint.run/usage/configuration/#run-configurationhttps://golangci-lint.run/usage/configuration/#run-configuration

Bump golangci-lint timeout from 2m to 5m

---

Makefile

The golangci-lint tool gets stuck for a variety of reasons when running in Prow CI. Enabling verbose output in an attempt to make debugging easier.
ref: https://golangci-lint.run/contributing/debug/

Enable golangci-lint Verbose Output

---

charts/descheduler/README.md

Since the parameter strategies don't exist anywhere in the code or docs, I'm removing it from the chart readme as a possible option.
It just makes things more confusing.
Related to issue #1566

docs: Removing deschedulerPolicy.strategies since it does not exist

---

charts/descheduler/templates/cronjob.yaml

Fixed the issue that template rendering failed when the values ​​of successfulJobsHistoryLimit and failedJobsHistoryLimit variables are 0.

Fixed the issue when successfulJobsHistoryLimit and failedJobsHistoryLimit variables are 0.

---

test/run-e2e-tests.sh

The new kind version defaults to k8s v1.32.0 version when creating new clusters.

Bump kind to v0.26.0

---

pkg/api/types.go
pkg/api/v1alpha2/types.go
pkg/api/v1alpha2/zz_generated.conversion.go
pkg/api/v1alpha2/zz_generated.deepcopy.go
pkg/api/zz_generated.deepcopy.go
pkg/descheduler/descheduler.go
pkg/descheduler/evictions/evictions.go
pkg/descheduler/evictions/evictions_test.go
pkg/descheduler/evictions/options.go

/kind feature
- add event when EvictPod failed.
- add unit test coverage
When it comes to eviction, what we really care about are the errors that occur during evictions. So I tend to include events when an eviction fails. Besides metrics and application logs, events are also a valuable source of information. Typically, operations personnel respond to events to manage the cluster effectively.

feature(eviction): add event when EvictPod failed

---

README.md
pkg/api/types.go
pkg/api/v1alpha2/types.go
pkg/api/v1alpha2/zz_generated.conversion.go
pkg/api/v1alpha2/zz_generated.deepcopy.go
pkg/api/zz_generated.deepcopy.go
pkg/descheduler/descheduler.go
pkg/descheduler/evictions/evictions.go
pkg/descheduler/evictions/options.go
test/e2e/e2e_toomanyrestarts_test.go

/kind feature
- add grace_period_seconds for DeschedulerPolicy
Fix https://github.com/kubernetes-sigs/descheduler/issues/1537

feature(descheduler): add grace_period_seconds for DeschedulerPolicy

---

charts/descheduler/templates/clusterrole.yaml

fixes #1595
missing permission 
```
I0103 10:56:41.502794       1 reflector.go:376] Caches populated for *v1.PriorityClass from k8s.io/client-go/informers/factory.go:160
W0103 10:56:41.504105       1 reflector.go:569] k8s.io/client-go/informers/factory.go:160: failed to list *v1.PodDisruptionBudget: poddisruptionbudgets.policy is forbidden: User "system:serviceaccount:kube-system:descheduler" cannot list resource "poddisruptionbudgets" in API group "policy" at the cluster scope
E0103 10:56:41.504128       1 reflector.go:166] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.PodDisruptionBudget: failed to list *v1.PodDisruptionBudget: poddisruptionbudgets.policy is forbidden: User \"system:serviceaccount:kube-system:descheduler\" cannot list resource …
```

charts: add missing permission for policy

---

test/e2e/e2e_toomanyrestarts_test.go

part of issue: https://github.com/kubernetes-sigs/descheduler/issues/1605
I have observed many flaky tests. My current idea is to roll back the e2e test first. Because gracePeriod is indeed effective, but it seems that the e2e test is not stable. I don’t have much time to conduct a deeper investigation at the moment. I will fix this when I have time.

flake: rollback gracePeriod for evict pod in e2e test

---

charts/descheduler/templates/clusterrole.yaml
charts/descheduler/values.yaml

fixes #1597
```
E0103 12:37:27.584970       1 metricscollector.go:128] "Error fetching metrics" err="nodes.metrics.k8s.io \"k3s-node3\" is forbidden: User \"system:serviceaccount:kube-system:descheduler\" cannot get resource \"nodes\" in API group \"metrics.k8s.io\" at the cluster scope" node="k3s-node3"
```

charts: add needed perms if metricsCollector is enabled

---

pkg/tracing/tracing.go
pkg/tracing/tracing_test.go

Looks like this has previously come up in #1428, so add a test this time.
Specifying `--otel-collector-endpoint` currently causes:
```text
E0122 20:09:35.824338  267288 tracing.go:130] "failed to create traceable resource" err=<
1 errors occurred detecting resource:
* conflicting Schema URL: https://opentelemetry.io/schemas/1.24.0 and https://opentelemetry.io/schemas/1.26.0
>
E0122 20:09:35.824366  267288 server.go:108] "failed to create tracer provider" err=<
1 errors occurred detecting resource:
* conflicting Schema URL: https://opentelemetry.io/schemas/1.24.0 and https://opentelemetry.io/schemas/1.26.0
>
```
This appears to address that problem.

tracing: test for and address semconv/SDK version conflicts

---

charts/descheduler/templates/clusterrole.yaml

Cherry pick of #1596 on release-1.32.
#1596: charts: add missing permission for policy at ClusterRole
For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.
```release-note
```

Automated cherry pick of #1596: charts: add missing permission for policy at ClusterRole

---

pkg/api/types.go
pkg/descheduler/metricscollector/metricscollector.go
pkg/descheduler/metricscollector/metricscollector_test.go
pkg/descheduler/node/node.go
pkg/framework/plugins/nodeutilization/highnodeutilization.go
pkg/framework/plugins/nodeutilization/lownodeutilization.go
pkg/framework/plugins/nodeutilization/nodeutilization.go
pkg/framework/plugins/nodeutilization/nodeutilization_test.go
pkg/framework/plugins/nodeutilization/usageclients.go

Too many places where `map[v1.ResourceName]*resource.Quantity` is getting defined.

ReferencedResourceList: alias for map[v1.ResourceName]*resource.Quantity to avoid the type definition duplication

---

pkg/framework/plugins/nodeutilization/validation_test.go

So it can be later extended with non threshold related validation tests.

nodeutilization: invoke ValidateLowNodeUtilizationArgs instead of validateLowNodeUtilizationThresholds to make the test more generic

---

pkg/framework/plugins/nodeutilization/highnodeutilization.go
pkg/framework/plugins/nodeutilization/lownodeutilization.go
pkg/framework/plugins/nodeutilization/nodeutilization.go
pkg/framework/plugins/nodeutilization/nodeutilization_test.go

Classify the nodes based on comparing percentages/thresholds rather then quantities to make the classification more generic. While still keeping the original way of computation available resources for eviction.
Noticeable changes:
- make computation of dynamic thresholds (deviation) separate from the user provided thresholds (static)
- classify nodes based on comparison of thresholds while translating actual node usages into percentages (the original thresholds used for available resource computation are still kept as quantities)

nodeutilization: make the node classification more generic

---

go.mod
pkg/framework/plugins/nodeutilization/highnodeutilization.go
pkg/framework/plugins/nodeutilization/highnodeutilization_test.go
pkg/framework/plugins/nodeutilization/lownodeutilization.go
pkg/framework/plugins/nodeutilization/lownodeutilization_test.go
pkg/framework/plugins/nodeutilization/nodeutilization.go
pkg/framework/plugins/nodeutilization/nodeutilization_test.go
pkg/framework/plugins/nodeutilization/normalizer/normalizer.go
pkg/framework/plugins/nodeutilization/normalizer/normalizer_test.go

this commit refactors the thresholds and usage assessment for the node utilization plugins. both high and low plugins are affected by this change.

feat: refactoring thresholds and usage assessment

---

charts/descheduler/README.md

Surface `cmdOptions.dry-run` value which can be set to prevent descheduler from making changes but still log what it would do.

Mention cmdOptions.dry-run in the helm chart readme

---

OWNERS

What type of PR is this?
/kind documentation
What this PR does / why we need it:
To become more deeply involved in community contributions, I'd like to nominate myself to the list of the descheduler reviewers:
https://github.com/kubernetes/org/issues/4921
[15 PRs merged in descheduler](https://github.com/kubernetes-sigs/descheduler/pulls?q=is%3Amerged+author%3Agoogs1025+is%3Aclosed+)

nominate googs1025 for descheduler reviewers

---

pkg/framework/plugins/nodeutilization/highnodeutilization.go
pkg/framework/plugins/nodeutilization/lownodeutilization.go
pkg/framework/plugins/nodeutilization/nodeutilization.go

when calculating the average an applying the deviations it would be nice to also see the assessed values.
this commit makes the descheduler logs these values when using level 3.

chore: log average and assessed thresholds

---

pkg/framework/plugins/removepodsviolatingtopologyspreadconstraint/topologyspreadconstraint.go
pkg/framework/plugins/removepodsviolatingtopologyspreadconstraint/topologyspreadconstraint_test.go

- fix removepodsviolatingtopologyspreadconstraint plugin sort logic
Fix: https://github.com/kubernetes-sigs/descheduler/issues/1624

fix removepodsviolatingtopologyspreadconstraint plugin sort logic

---

test/e2e/e2e_lownodeutilization_test.go

https://github.com/narmidm/k8s-pod-cpu-stressor/commit/696ac0def8cc9ef7e510b3942b2394c73765827b added validation for the cpu param. Also, it turns out the param was not set correctly previously.

TestLowNodeUtilizationKubernetesMetrics: set the right -cpu value for the cpu stressor

---

README.md
pkg/framework/plugins/nodeutilization/highnodeutilization.go
pkg/framework/plugins/nodeutilization/highnodeutilization_test.go
pkg/framework/plugins/nodeutilization/nodeutilization.go
pkg/framework/plugins/nodeutilization/types.go
pkg/framework/plugins/nodeutilization/validation.go
pkg/framework/plugins/nodeutilization/zz_generated.deepcopy.go

with strict eviction policy the descheduler only evict pods if the pod contains a request for the given threshold. for example, if using a threshold for an extended resource called `example.com/gpu` only pods who request such a resource will be evicted.

feat: introduce strict eviction policy

---

Dockerfile
Dockerfile.dev
charts/descheduler/Chart.yaml
docs/release-guide.md

kubernetes-sig-scheduling@googlegroups.com is deprecated, and a new mailing list would be sig-scheduling@kubernetes.io.
See: https://github.com/kubernetes/community/issues/8437

fix: update the mailing list address

---

charts/descheduler/values.yaml

Since the removal of v1alpha1 descheduler policy config type in https://github.com/kubernetes-sigs/descheduler/pull/1482, some values are now obsolete and shouldn't be referenced in the helm chart since they are not applied anymore

Remove reference to obsolete deschedulerPolicy fields in chart values

---

pkg/framework/plugins/removepodsviolatingnodetaints/node_taint.go

Listing pods was incorrectly changed to listing all pods during code refactoring in https://github.com/kubernetes-sigs/descheduler/commit/0ff8ecb41ecf90ff2cfaa84a3e763ad0c800cb6d#diff-494cd6260fda05699f68c7da810f7814dea797a006afee5380728a6433206fefL82.

RemovePodsViolatingNodeTaints: list only pods that are not failed/suceeded

---

pkg/framework/plugins/defaultevictor/constraints.go
pkg/framework/plugins/defaultevictor/defaultevictor.go

- separate eviction constraints to `constraints.go`
more info base on: https://github.com/kubernetes-sigs/descheduler/pull/1665#pullrequestreview-2848968410

refactor: separate eviction constraints to constraints.go

---

pkg/descheduler/descheduler.go
pkg/framework/fake/plugin/fake.go
pkg/framework/pluginregistry/pluginregistry.go
pkg/framework/plugins/defaultevictor/defaultevictor.go
pkg/framework/plugins/defaultevictor/defaultevictor_test.go
pkg/framework/plugins/example/example.go
pkg/framework/plugins/nodeutilization/highnodeutilization.go
pkg/framework/plugins/nodeutilization/highnodeutilization_test.go
pkg/framework/plugins/nodeutilization/lownodeutilization.go
pkg/framework/plugins/nodeutilization/lownodeutilization_test.go
pkg/framework/plugins/podlifetime/pod_lifetime.go
pkg/framework/plugins/podlifetime/pod_lifetime_test.go
pkg/framework/plugins/removeduplicates/removeduplicates.go
pkg/framework/plugins/removeduplicates/removeduplicates_test.go
pkg/framework/plugins/removefailedpods/failedpods.go
pkg/framework/plugins/removefailedpods/failedpods_test.go
pkg/framework/plugins/removepodshavingtoomanyrestarts/toomanyrestarts.go
pkg/framework/plugins/removepodshavingtoomanyrestarts/toomanyrestarts_test.go
pkg/framework/plugins/removepodsviolatinginterpodantiaffinity/pod_antiaffinity.go
pkg/framework/plugins/removepodsviolatinginterpodantiaffinity/pod_antiaffinity_test.go
pkg/framework/plugins/removepodsviolatingnodeaffinity/node_affinity.go
pkg/framework/plugins/removepodsviolatingnodeaffinity/node_affinity_test.go
pkg/framework/plugins/removepodsviolatingnodetaints/node_taint.go
pkg/framework/plugins/removepodsviolatingnodetaints/node_taint_test.go
pkg/framework/plugins/removepodsviolatingtopologyspreadconstraint/topologyspreadconstraint.go
pkg/framework/plugins/removepodsviolatingtopologyspreadconstraint/topologyspreadconstraint_test.go
pkg/framework/profile/profile.go
pkg/framework/profile/profile_test.go
pkg/framework/testing/utils.go
test/e2e/e2e_test.go

The new context.Context can be later used for passing a contextualized logger. Or, other initialization steps that require the context.

Extend plugin's New with a context.Context

---

pkg/descheduler/pod/pods_test.go
pkg/framework/plugins/defaultevictor/defaultevictor_test.go

- dropping default values assignments in tests
- replacing `descheduler.alpha.kubernetes.io/evict` literal with `evictPodAnnotationKey` const
- `TestSortPodsBasedOnPriorityLowToHigh`: extending the test to check the whole sorted list instead of a single item

Test code refactorings

---

README.md
pkg/descheduler/evictions/utils/utils.go
pkg/descheduler/pod/pods.go
pkg/descheduler/pod/pods_test.go
pkg/framework/plugins/defaultevictor/defaultevictor.go
pkg/framework/plugins/defaultevictor/defaultevictor_test.go
pkg/framework/plugins/defaultevictor/types.go
pkg/framework/plugins/defaultevictor/validation.go
pkg/framework/plugins/defaultevictor/validation_test.go

Define `descheduler.alpha.kubernetes.io/prefer-no-eviction` annotation so pods can  voice their preference not to be evicted. Each plugin decides whether the annotation gets respected or not. When the `DefaultEvictor` plugin sets `noEvictionPolicy` to `Mandatory` all such pods are excluded from eviction. Needs to be used with caution as some plugins may enfore various policies that are expected to be always met.
Alternative for https://github.com/kubernetes-sigs/descheduler/pull/1673.
Fixes: https://github.com/kubernetes-sigs/descheduler/issues/1659

Default evictor no eviction policy

---

pkg/framework/plugins/defaultevictor/validation.go
pkg/framework/plugins/defaultevictor/validation_test.go
pkg/framework/plugins/podlifetime/validation.go
pkg/framework/plugins/podlifetime/validation_test.go
pkg/framework/plugins/removeduplicates/validation.go
pkg/framework/plugins/removeduplicates/validation_test.go
pkg/framework/plugins/removefailedpods/validation.go
pkg/framework/plugins/removefailedpods/validation_test.go
pkg/framework/plugins/removepodshavingtoomanyrestarts/validation.go
pkg/framework/plugins/removepodshavingtoomanyrestarts/validation_test.go
pkg/framework/plugins/removepodsviolatinginterpodantiaffinity/validation.go
pkg/framework/plugins/removepodsviolatinginterpodantiaffinity/validation_test.go
pkg/framework/plugins/removepodsviolatingnodeaffinity/validation.go
pkg/framework/plugins/removepodsviolatingnodeaffinity/validation_test.go
pkg/framework/plugins/removepodsviolatingnodetaints/validation.go
pkg/framework/plugins/removepodsviolatingnodetaints/validation_test.go
pkg/framework/plugins/removepodsviolatingtopologyspreadconstraint/validation_test.go

Improves the validation logic in the `ValidatexxxArgs` by changing it from "returning on the first error" to "collecting all validation errors and returning them together," enhancing the user experience when diagnosing config issues.

Improves the validation logic in the plugins

---

charts/descheduler/templates/cronjob.yaml
charts/descheduler/templates/deployment.yaml
charts/descheduler/templates/serviceaccount.yaml
charts/descheduler/values.yaml

In our Environment all ServiceAccounta are mutatet  to automountServiceAccountToken: false 
And its only allowed to set the automountServiceAccountToken: true in a deployment.
But at the moment descheduler doesnt provide this.
automountServiceAccountToken is necessary for descheduler, for that reason i added it hard coded.
Would be nice if you can go with it.
many thanks

feat(token): automountServiceAccountToken set hard to true on deployment

---

pkg/framework/plugins/defaultevictor/constraints.go
pkg/framework/plugins/defaultevictor/defaultevictor.go
pkg/framework/plugins/defaultevictor/defaultevictor_test.go

fix part of : https://github.com/kubernetes-sigs/descheduler/pull/1665#pullrequestreview-3078443138
Unified the boolean argument semantics for all evictionConstraintsForXXX
functions to consistently represent whether protection is enabled.

standardize protectionEnabled param across eviction constraints

---

charts/descheduler/README.md
charts/descheduler/templates/cronjob.yaml
charts/descheduler/tests/cronjob_annotations_test.yaml
charts/descheduler/values.yaml

This pr implements #1732 suggestion. 
Example result of helm template with default values of new properties ` helm template descheduler . --values values.yaml `:
[output-default-values.yaml.txt](https://github.com/user-attachments/files/21949427/output-default-values.yaml.txt)
Example result of helm template with  test values of new properties ` helm template descheduler . --values test-values.yaml `:
[output-test-values.yaml.txt](https://github.com/user-attachments/files/21949441/output-test-values.yaml.txt)

[1732] chore: add cronjob/job labels and annotations to helm chart

---

test/e2e/e2e_test.go
test/run-e2e-tests.sh

So RunAsUser and RunAsGroup can be either omitted and set to different values.

feat(test/e2e): introduce new flags to override RunAsUser and RunAsGroup security context setting
